INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (1,'AF','Afghanistan','GMT + 4:30','AFA','Afghani','RMEA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (2,'AL','Albania','GMT + 02:00','ALL','Lek','RMED','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (3,'DZ','Algeria','GMT + 1:00','DZD','Algerian Dinar','RMED','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (4,'AS','American Samoa','GMT - 11:00','EUR','Euro','RASO','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (5,'AD','Andorra','GMT - 11:00','EUR','Euro','RMED','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (6,'AO','Angola','GMT + 1:00','AOK','Angolan Kwanza','RSSA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (7,'AI','Anguilla','GMT - 4:00','XCD','East Carribean Dollar','RLAM','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (8,'AG','Antigua & Barbuda','GMT - 4:00','XCD','East Carribean Dollar','RLAM','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (9,'AR','Argentina','GMT - 3:00','ARP','Argentina Peso','RLAM','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (10,'AM','Armenia','GMT + 5:00','AMD','Dram','RECA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (11,'AW','Aruba','GMT - 4:00','ANG','Antilles Guilder','RLAM','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (12,'AU','Australia','GMT + 10:00','AUD','Australian Dollar','RASO','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (13,'AT','Austria','GMT + 2:00','EUR','Euro','RWCE','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (14,'AZ','Azerbaijan','GMT + 4:00','AZM','Manat','RECA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (15,'BS','Bahamas','GMT - 04:00','BSD','Bahamian Dollar','RLAM','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (16,'BH','Baharin','GMT + 3:00','BHD','Baharini Dinar','RMEA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (17,'BD','Bangladesh','GMT + 6:00','BDT','Taka','RASO','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (18,'BB','Barbados','GMT - 4:00','BBD','Barbadian Dollar','RLAM','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (19,'BY','Belarus','GMT + 3:00','BYR','Belarus Ruble','RECA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (20,'BE','Belgium','GMT + 2:00','EUR','Euro','RWCE','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (21,'BZ','Belize','GMT - 6:00','BZD','Belizean Dollar','RLAM','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (22,'BJ','Benin','GMT + 1:00','XOF','CFA Franc','RSSA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (23,'BM','Bermuda','GMT - 03:00','BMD','Bermudian Dollar','RLAM','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (24,'BT','Bhutan','GMT + 6:00','INR','Indian Rupee','RINA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (25,'BO','Bolivia','GMT - 4:00','BOB','Boliviano','RLAM','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (26,'BA','Bosnia & Herzegownia','GMT + 02:00','BAM','Marka','RWCE','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (27,'BW','Botswana','GMT + 2:00','BWP','Pula','RSSA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (28,'BV','Bouvet Island','GMT + 01:00','NOK','Norweigan Kroner','RLAM','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (29,'BR','Brazil','GMT - 03:00','BRL','Brazilian Real','RLAM','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (30,'','British Indian Ocean Territory','GMT + 6:00','USD','US Dollar','RLAM','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (31,'BN','Brunei Darussalam','GMT + 8:00','BND','Bruneian Dollar','RASO','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (32,'BG','Bulgaria','GMT + 3:00','BGL','Lev','RMED','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (33,'BF','Burkina Faso','GMT + 00:00','XOF','CFA Franc','RSSA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (34,'BI','Burundi','GMT + 2:00','BIF','Burundi Franc','RSSA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (35,'KH','Cambodia','GMT + 7:00','KHR','Riel','RASO','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (36,'CM','Cameroon','GMT + 1:00','XAF','CFA Franc','RSSA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (37,'CA','Canada','GMT - 04:00','CAD','Canadian Dollar','RNAM','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (38,'CV','Cape Verde','GMT - 1:00','CVE','Escudo','RSSA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (39,'KY','Cayman Islands','GMT - 5:00','KYD','Caymanian Dollar','RLAM','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (40,'CF','Central African Republic','GMT + 1:00','XAF','CFA Franc','RSSA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (41,'TD','Chad','GMT + 1:00','XAF','CFA Franc','RSSA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (42,'CL','Chile','GMT - 04:00','CLP','Chilean Peso','RLAM','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (43,'CN','China','GMT + 8:00','RMB','Yuan Renminbi','RCNA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (44,'CX','Christmas Island','GMT + 7:00','AUD','Australian Dollar','RASO','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (45,'CC','Cocos Islands','GMT + 06:30','AUD','Australian Dollar','RASO','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (46,'CO','Colombia','GMT - 5:00','COP','Colombia Peso','RLAM','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (47,'KM','Comoros','GMT + 3:00','KMF','Comoran Franc','RSSA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (48,'CG','Congo Republic','GMT + 1:00','XAF','CFA Franc','RSSA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (49,'CD','Congo - Brazaville','GMT + 1:00','CDF','Congolese Franc','RSSA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (50,'CK','Cook Islands','GMT - 8:00','NZD','NewZealand Dollar','RASO','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (51,'CR','Costa Rica','GMT - 6:00','CRC','Costa Rica Colon','RLAM','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (52,'HR','Croatia','GMT + 02:00','HRK','Croatian Dinar','RWCE','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (53,'CU','Cuba','GMT - 04:00','CUP','Cuban Peso','RLAM','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (54,'CY','Cyprus','GMT + 3:00','CYP','Cypriot Pound','RMED','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (55,'CZ','Czech Republic','GMT + 2:00','CZK','Koruna','RWCE','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (56,'DK','Denmark','GMT + 2:00','DKK','Danish Kroner','RECA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (57,'DJ','Djibouti','GMT + 3:00','DJF','Dijboutian Franc','RMEA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (58,'DM','Dominica','GMT - 4:00','XCD','East Carribean Dollar','RLAM','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (59,'DO','Dominican Republic','GMT - 4:00','DOP','Dominican Peso','RLAM','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (60,'','East Timor','GMT + 9:00','IDR','Indonesian Rupiah','RASO','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (61,'EC','Ecuador','GMT - 5:00','ECS','Sucre','RLAM','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (62,'EG','Egypt','GMT + 03:00','EGP','Egyptian Pound','RMEA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (63,'SV','El Salvador','GMT - 6:00','SVC','Salvadoran Colon','RLAM','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (64,'GQ','Equatorial Guinea','GMT + 1:00','XAF','CFA Franc','RSSA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (65,'ER','Eritrea','GMT + 3:00','ERN','Nakfa','RMEA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (66,'EE','Estonia','GMT + 3:00','EEK','Estonian Croon','RECA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (67,'ET','Ethiopia','GMT + 2:00','ETB','Birr','RMEA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (68,'FK','Falkland Islands','GMT - 04:00','FKP','Falkland Pound','RLAM','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (69,'FO','Faroe Islands','GMT + 01:00','DKK','Danish Kroner','RECA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (70,'FJ','Fiji','GMT + 11:00','FJD','Fijian Dollar','RASO','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (71,'FI','Finland','GMT + 3:00','EUR','Euro','RECA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (72,'FR','France','GMT + 2:00','EUR','Euro','RMED','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (73,'GF','French Guiana','GMT - 03:00','EUR','Euro','RLAM','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (74,'PF','French Polynesia','GMT - 10:00','XPF','CFP Franc','RASO','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (75,'TF','French Southern Territories','GMT + 05:00','EUR','Euro','RASO','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (76,'GA','Gabon','GMT + 1:00','XAF','CFA Franc','RSSA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (77,'GM','Gambia','GMT + 00:00','GMD','Dalasi','RSSA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (78,'GE','Georgia','GMT + 4:00','GEL','Lari','RECA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (79,'DE','Germany','GMT + 2:00','EUR','Euro','RWCE','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (80,'GH','Ghana','GMT + 00:00','GHC','Cedi','RSSA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (81,'GI','Gibraltar','GMT + 02:00','GIP','Gibraltar Pound','RMED','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (82,'GR','Greece','GMT + 3:00','EUR','Euro','RMED','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (83,'GL','Greenland','GMT - 02:00','DKK','Danish Kroner','RECA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (84,'GD','Grenada','GMT - 4:00','XCD','East Carribean Dollar','RLAM','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (85,'GP','Guadeloupe','GMT - 04:00','EUR','Euro','RLAM','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (86,'GU','Guam','GMT + 10:00','USD','US Dollar','RASO','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (87,'GT','Guatemala','GMT - 6:00','GTQ','Quetzal','RLAM','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (88,'GN','Guinea','GMT + 1:00','GNF','Guinean Franc','RSSA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (89,'GW','Guinea-Bissau','GMT + 00:00','XOF','CFA Franc','RSSA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (90,'GY','Guyana','GMT - 4:00','GYD','Guyanese Dollar','RLAM','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (91,'HT','Haiti','GMT - 5:00','USD','US Dollar','RLAM','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (92,'HM','Heard&McDonald Islands','GMT + 05:00','AUD','Australian Dollar','RASO','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (93,'HN','Honduras','GMT - 6:00','HNL','Lempira','RLAM','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (94,'','Hong Kong','GMT + 8:00','HKD','Hong Kong Dollar','RCNA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (95,'HU','Hungary','GMT + 2:00','HUF','Forint','RWCE','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (96,'IS','Iceland','GMT + 00:00','ISK','Icelandic Kroner','RECA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (97,'IN','India','GMT + 5:30','INR','Indian Rupee','RINA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (98,'','Indonesia','GMT + 7:00','IDR','Indonesian Rupiah','RASO','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (99,'IR','Iran','GMT + 04:30','IRR','Rial','RMEA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (100,'IQ','Iraq','GMT + 03:00','IQD','Dinar','RMEA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (101,'IE','Ireland','GMT + 1:00','EUR','Euro','RWCE','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (102,'IL','Israel','GMT + 03:00','ILS','Shekel','RMED','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (103,'IT','Italy','GMT + 2:00','EUR','Euro','RMED','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (104,'','Ivory Coast','GMT + 00:00','XOF','CFA Franc','RWCE','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (105,'JM','Jamaica','GMT - 5:00','JMD','Jamaican Dollar','RLAM','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (106,'','Japan','GMT + 9:00','JPY','Yen','RCNA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (107,'JO','Jordan','GMT + 03:00','JOD','Jordainan Dinar','RMEA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (108,'KZ','Kazakhstan','GMT + 6:00','KZT','Tenge','RECA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (109,'KE','Kenya','GMT + 3:00','KES','Kenyan Shilling','RSSA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (110,'KI','Kiribati','GMT + 12:00','AUD','Australian Dollar','RASO','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (111,'KP','Korea','North','GMT ','KPW','RASO','R');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (112,'KR','Korea','South','GMT ','KRW','RASO','R');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (113,'KW','Kuwait','GMT + 3:00','KWD','Kuwaiti Dinar','RMEA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (114,'KG','Kyrgyzstan','GMT + 6:00','KGS','Som','RECA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (115,'LA','Laos','GMT + 7:00','LAK','Kip','RASO','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (116,'LV','Latvia','GMT + 3:00','LVL','Lat','RECA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (117,'LB','Lebanon','GMT + 03:00','LBP','Lebanese Pound','RMEA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (118,'LS','Lesotho','GMT + 2:00','LSL','Loti','RSSA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (119,'LR','Liberia','GMT + 00:00','LRD','Liberian Dollar','RSSA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (120,'LY','Libya','GMT + 2:00','LYD','Libyan Dinar','RMED','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (121,'LI','Liechtenstein','GMT + 02:00','CHF','Swiss Franc','RWCE','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (122,'LT','Lithuania','GMT + 3:00','LTL','Lita','RECA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (123,'LU','Luxembourg','GMT + 2:00','EUR','Euro','RWCE','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (124,'','Macau','GMT + 08:00','MOP','Pataca','RCNA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (125,'MK','Macedonia','GMT + 02:00','MKD','Denar','RMED','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (126,'MG','Madagascar','GMT + 3:00','MGF','Malagasy Franc','RSSA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (127,'MW','Malawi','GMT + 2:00','MWK','Malawian Kwacha','RSSA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (128,'MY','Malaysia','GMT + 8:00','MYR','Ringgit','RASO','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (129,'MV','Maldives','GMT + 5:00','MVR','Rufiyaa','RASO','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (130,'ML','Mali','GMT + 00:00','XOF','CFA Franc','RSSA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (131,'MT','Malta','GMT + 2:00','MTL','Maltese Lira','RMED','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (132,'MH','Marshall Islands','GMT + 00:00','USD','US Dollar','RASO','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (133,'MQ','Martinique','GMT - 04:00','EUR','Euro','RLAM','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (134,'MR','Mauritinia','GMT + 00:00','MRO','Ouguiya','RMED','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (135,'MU','Mauritius','GMT + 4:00','MUR','Mauritian Rupee','RSSA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (136,'YT','Mayotte','GMT + 03:00','EUR','Euro','RSSA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (137,'MX','Mexico','GMT - 05:00','MXP','Mexican Peso','RLAM','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (138,'','Micronesia','GMT + 10:00','USD','US Dollar','RASO','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (139,'FM','Moldova','GMT + 3:00','MDL','Leu','RASO','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (140,'MC','Monaco','GMT + 02:00','EUR','Euro','RMED','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (141,'MN','Mongolia','GMT + 8:00','MNT','Tugrik','RECA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (142,'MS','Montsterrat','GMT - 04:00','XCD','East Carribean Dollar','RLAM','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (143,'MA','Morocco','GMT + 01:00','MAD','Dirham','RMED','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (144,'MZ','Mozambique','GMT + 2:00','MZM','Metical','RSSA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (145,'MM','Myanmar','GMT + 06:30','MMK','Kyat','RASO','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (146,'NA','Namibia','GMT + 01:00','ZAR','South African Rand','RSSA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (147,'NR','Nauru','GMT + 12:00','AUD','Australian Dollar','RASO','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (148,'NP','Nepal','GMT + 05:45','NPR','Nepalese Rupee','RINA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (149,'NL','Netherlands','GMT + 2:00','EUR','Euro','RWCE','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (150,'','Netherlands Antilles','GMT - 04:00','ANG','Antillean Guilder','RWCE','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (151,'NC','New Caledonia','GMT + 11:00','XPF','CFP Franc','RMED','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (152,'NZ','New Zealand','GMT + 12:00','NZD','New Zealand Dollar','RASO','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (153,'NI','Nicaragua','GMT - 6:00','NIO','Cordoba Oro','RLAM','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (154,'NE','Niger','GMT + 1:00','XOF','CFA Franc','RSSA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (155,'NG','Nigeria','GMT + 1:00','NGN','Naira','RSSA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (156,'NU','Niue','GMT - 11:00','NZD','New Zealand Dollar','RASO','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (157,'NF','Norfolk Island','GMT + 11:30','AUD','Australian Dollar','RASO','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (158,'MP','Northern Mariana Island','GMT + 10:00','USD','US Dollar','RASO','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (159,'NO','Norway','GMT + 2:00','NOK','Norwegian Kroner','RECA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (160,'OM','Oman','GMT + 4:00','OMR','Sul Rial','RMEA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (161,'PK','Pakistan','GMT + 5:00','PKR','Pakistan Rupee','RMEA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (162,'PW','Palau','GMT + 9:00','USD','US Dollar','RASO','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (163,'PA','Panama','GMT - 5:00','USD','US Dollar','RLAM','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (164,'PG','Papua New Guinea','GMT + 10:00','PGK','Kina','RASO','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (165,'PY','Paraguay','GMT - 04:00','PYG','Guarani','RLAM','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (166,'PE','Peru','GMT - 5:00','PEN','Nuevo Sol','RLAM','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (167,'PH','Philippines','GMT + 8:00','PHP','Philippines Peso','RASO','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (168,'PN','Pitcairn','GMT - 8:00','NZD','New Zealand Dollar','RASO','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (169,'PL','Poland','GMT + 2:00','PLN','Zloty','RWCE','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (170,'PT','Portugal','GMT + 1:00','EUR','Euro','RMED','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (171,'PR','Puerto Rico','GMT - 4:00','USD','US Dollar','RLAM','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (172,'QA','Qatar','GMT + 3:00','QAR','Rial','RMEA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (173,'RE','Reunion','GMT + 04:00','EUR','Euro','RSSA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (174,'RO','Romania','GMT + 3:00','ROL','Leu','RMED','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (175,'RU','Russian Federation','GMT + 04:00','RUR','Ruble','RECA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (176,'RW','Rwanda','GMT + 2:00','RWF','Rwanda Franc','RSSA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (177,'KN','Saint Kitts','GMT - 04:00','XCD','East Carribean Dollar','RLAM','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (178,'LC','Saint Lucia','GMT - 4:00','XCD','East Carribean Dollar','RLAM','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (179,'VC','Saint Vincent Grenadines','GMT - 04:00','XCD','East Carribean Dollar','RLAM','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (180,'WS','Samoa','GMT - 11:00','WST','Samoan Tala','RASO','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (181,'SM','San Marino','GMT + 02:00','EUR','Euro','RMED','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (182,'ST','Sao Tome & Principe','GMT + 00:00','STD','Dobra','RSSA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (183,'SA','Saudi Arabia','GMT + 3:00','SAR','Riyal','RMEA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (184,'SN','Senegal','GMT + 00:00','XOF','CFA Franc','RSSA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (185,'SC','Seychelles','GMT + 4:00','SCR','Rupee','RSSA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (186,'SL','Sierra Leone','GMT + 00:00','SLL','Leone','RSSA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (187,'SG','Singapore','GMT + 8:00','SGD','Singapore Dollar','RASO','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (188,'SK','Slovakia','GMT + 2:00','SKK','Slovak Koruna','RWCE','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (189,'SI','Slovenia','GMT + 2:00','EUR','Euro','RWCE','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (190,'SB','Solomon Islands','GMT + 11:00','SBD','Solomon Islands Dollar','RASO','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (191,'SO','Somalia','GMT + 3:00','SOS','Shilling','RMEA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (192,'ZA','South Africa','GMT + 2:00','ZAR','South African Rand','RSSA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (193,'','South Georgia','GMT - 2:00','GBP','Pound Sterling','RECA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (194,'ES','Spain','GMT + 2:00','EUR','Euro','RMED','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (195,'LK','Sri Lanka','GMT + 6:00','LKR','Lankan Rupee','RASO','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (196,'SD','Sudan','GMT + 3:00','SDD','Dinar','RMEA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (197,'SR','Suriname','GMT - 3:00','SRG','Surinamese Guilder','RLAM','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (198,'SJ','Svalbard','GMT + 02:00','NOK','Norweigan Kroner','RECA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (199,'SZ','Swaziland','GMT + 2:00','SZL','Lilangeni','RSSA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (200,'S1','Sweden','GMT + 2:00','SEK','Swedish Kroner','RECA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (201,'CH','Switzerland','GMT + 2:00','CHF','Swiss Franc','RWCE','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (202,'SY','Syrian Arab Republic','GMT + 03:00','SYP','Syrian Pound','RMEA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (203,'TW','Taiwan','GMT + 8:00','TWD','Taiwan Dollar','RCNA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (204,'TJ','Tajikistan','GMT + 5:00','TJS','Somoni','RECA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (205,'TZ','Tanzania','GMT + 3:00','TZS','Shilling','RSSA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (206,'TH','Thailand','GMT + 7:00','THB','Baht','RASO','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (207,'TG','Togo','GMT + 00:00','XOF','CFA Franc','RSSA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (208,'TK','Tokelau','GMT - 10:00','NZD','New Zealand Dollar','RASO','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (209,'TO','Tonga','GMT + 13:00','TOP','Pa\'anga','RASO','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (210,'TT','Trinidad & Tobago','GMT - 4:00','TDD','Trinidad & Tobago Dollar','RLAM','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (211,'TN','Tunisia','GMT + 01:00','TND','Tunisian Dinar','RMED','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (212,'TR','Turkey','GMT + 3:00','TRL','Lira','RMEA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (213,'TM','Turkmenistan','GMT + 5:00','TMM','Manat','RECA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (214,'TC','Turks & Caicos Islands','GMT - 04:00','USD','US Dollar','RLAM','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (215,'TV','Tuvalu','GMT + 12:00','AUD','Australian Dollar','RASO','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (216,'UG','Uganda','GMT + 3:00','UGX','Shilling','RSSA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (217,'UA','Ukraine','GMT + 3:00','UAH','Hryvnia','RECA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (218,'AE','United Arab Emirates','GMT + 4:00','AED','Dirham','RMEA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (219,'GB','United Kingdom','GMT + 1:00','GBP','Pound Sterling','RWCE','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (220,'US','United States','GMT - 04:00','USD','US Dollar','RNAM','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (221,'UY','Uruguay','GMT - 03:00','UYU','Uruguay Peso','RLAM','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (222,'UZ','Uzbekistan','GMT + 5:00','UZS','Som','RECA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (223,'VU','Vanuatu','GMT + 11:00','VUV','Vatu','RASO','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (224,'','Vatican City State','GMT + 02:00','EUR','Euro','RMED','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (225,'VE','Venezuela','GMT - 4:00','VEB','Bolivar','RLAM','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (226,'VN','Vietnam','GMT + 7:00','USD','US Dollar','RASO','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (227,'VI','Virgin Islands','GMT - 4:00','USD','US Dollar','RLAM','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (228,'WF','Wallis & Futuna Islands','GMT + 12:00','XPF','CFP Franc','RASO','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (229,'EH','Western Sahara','GMT + 08:00','MAD','Moroccan Dirham','RMED','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (230,'YE','Yemen','GMT + 3:00','YER','Yemen Rial','RMEA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (231,'','Yugoslavia','','YUN','New Dinar','RWCE','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (232,'ZM','Zambia','GMT + 2:00','ZMK','Kwacha','RSSA','Y');
INSERT INTO Country (CountryID,CountryCode,CountryName,TimeZone,CurrencyCode,CurrencyName,Region,Active) VALUES (233,'ZW','Zimbabwe','GMT + 2:00','ZWD','Zimbabwe Dollar','RSSA','Y');