INSERT INTO JobRole (JobRoleID,Role) VALUES (1,'JOB LEVEL 4'
);
INSERT INTO JobRole (JobRoleID,Role) VALUES (2,'JOB LEVEL 5'
);
INSERT INTO JobRole (JobRoleID,Role) VALUES (3,'JOB LEVEL 6'
);
INSERT INTO JobRole (JobRoleID,Role) VALUES (4,'JOB LEVEL 7'
);
INSERT INTO JobRole (JobRoleID,Role) VALUES (5,'JOB LEVEL 8'
);
INSERT INTO JobRole (JobRoleID,Role) VALUES (6,'JOB LEVEL 9'
);