/*
-- Query: SELECT * FROM IT_MSSP_UAT.ServiceElement
LIMIT 0, 1000

-- Date: 2014-05-09 11:22
*/
/*
INSERT INTO `ServiceElement` (`ServiceElementID`,`ServiceElementName`,`ServiceElementDescription`,`ServiceFunctionName`,`ServiceFunctionCode`,`Active`,`HasServiceScope`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`) VALUES (1,'Program Management','Program Management deals with overall coordination of the projects belonging to a program. It ensures to successfully meet all objectives in terms of scope, time, cost and quality. Additionally, it deals with managing client meetings, reporting and communication, escalation path, acceptance tracking and reporting, change control, quality management, risk/ issue management (limited to the project/program execution scope).','ADM Support Process','ADM_SUPP','Y','N','Admin','2014-04-28 00:00:00',NULL,'2014-04-28 00:00:00');
INSERT INTO `ServiceElement` (`ServiceElementID`,`ServiceElementName`,`ServiceElementDescription`,`ServiceFunctionName`,`ServiceFunctionCode`,`Active`,`HasServiceScope`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`) VALUES (2,'Release Management','Release Management deals with installation and distribution of a Software Release, defining rollout plan and overseeing the rollout of software and related hardware. It ensures that hardware and software being changed are traceable as well as that only correct, authorised and tested versions are installed, working and linked to Configuration Management and Change Management.','ADM Support Process','ADM_SUPP','Y','N','Admin','2014-04-28 00:00:00',NULL,'2014-04-28 00:00:00');
INSERT INTO `ServiceElement` (`ServiceElementID`,`ServiceElementName`,`ServiceElementDescription`,`ServiceFunctionName`,`ServiceFunctionCode`,`Active`,`HasServiceScope`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`) VALUES (3,'Change Management','Change Management ensures that standardised methods and procedures are used for efficient and prompt handling of all Changes. It also manages the Requirement Traceability Matrix  for new requirements, fixing and improving tasks.','ADM Support Process','ADM_SUPP','Y','N','Admin','2014-04-28 00:00:00',NULL,'2014-04-28 00:00:00');
INSERT INTO `ServiceElement` (`ServiceElementID`,`ServiceElementName`,`ServiceElementDescription`,`ServiceFunctionName`,`ServiceFunctionCode`,`Active`,`HasServiceScope`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`) VALUES (4,'Capacity Management','Capacity Management deals with preparation of models for the estimation of volume growth and planning/designing the future needs in terms of hardware and software licenses.','ADM Support Process','ADM_SUPP','Y','N','Admin','2014-04-28 00:00:00',NULL,'2014-04-28 00:00:00');
INSERT INTO `ServiceElement` (`ServiceElementID`,`ServiceElementName`,`ServiceElementDescription`,`ServiceFunctionName`,`ServiceFunctionCode`,`Active`,`HasServiceScope`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`) VALUES (5,'Configuration Management','Configuration Management deals with the tasks to identify, control, maintain and verify the versions of Configuration Items (CIs) in existence (for software items, infrastructure and documents). It provides accurate information on configurations and their documentation to support Incident Management, Problem Management, Change Management and Release Management.','ADM Support Process','ADM_SUPP','Y','N','Admin','2014-04-28 00:00:00',NULL,'2014-04-28 00:00:00');
INSERT INTO `ServiceElement` (`ServiceElementID`,`ServiceElementName`,`ServiceElementDescription`,`ServiceFunctionName`,`ServiceFunctionCode`,`Active`,`HasServiceScope`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`) VALUES (6,'Security Management','Security Management deals with managing the definition, implementation and compliance verification of policies, standards, procedures and guidelines in order to avoid unauthorized access to the applications and relevant information.','ADM Support Process','ADM_SUPP','Y','N','Admin','2014-04-28 00:00:00',NULL,'2014-04-28 00:00:00');
INSERT INTO `ServiceElement` (`ServiceElementID`,`ServiceElementName`,`ServiceElementDescription`,`ServiceFunctionName`,`ServiceFunctionCode`,`Active`,`HasServiceScope`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`) VALUES (7,'Availability Management','Availability Management guarantees the Application systems availability managing the planned outage and avoiding system faults or data corruption by managing risks that could seriously impact IT Services.','ADM Support Process','ADM_SUPP','Y','N','Admin','2014-04-28 00:00:00',NULL,'2014-04-28 00:00:00');
INSERT INTO `ServiceElement` (`ServiceElementID`,`ServiceElementName`,`ServiceElementDescription`,`ServiceFunctionName`,`ServiceFunctionCode`,`Active`,`HasServiceScope`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`) VALUES (8,'Access Management','Access Management deals with managing the IT User access rights (CRUD), and creating and deleting users.','Application Maintenance','APP_MAIN','Y','N','Admin','2014-04-28 00:00:00',NULL,'2014-04-28 00:00:00');
INSERT INTO `ServiceElement` (`ServiceElementID`,`ServiceElementName`,`ServiceElementDescription`,`ServiceFunctionName`,`ServiceFunctionCode`,`Active`,`HasServiceScope`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`) VALUES (9,'Demand Support','Demand Support deals with requirements gathering, technical feasibility analysis, release workplan and effort estimation.','Application Development','APP_DEV','Y','N','Admin','2014-04-28 00:00:00',NULL,'2014-04-28 00:00:00');
INSERT INTO `ServiceElement` (`ServiceElementID`,`ServiceElementName`,`ServiceElementDescription`,`ServiceFunctionName`,`ServiceFunctionCode`,`Active`,`HasServiceScope`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`) VALUES (10,'Design & Build','Design & Build deals with detailed technical design, test cycles/cases, functional specifications, Software coding/configuring, Unit/Component test, Release notes, Capacity planning (hardware/software licenses), Creation of a User and Operation & Maintenance Manuals.','Application Development','APP_DEV','Y','N','Admin','2014-04-28 00:00:00',NULL,'2014-04-28 00:00:00');
INSERT INTO `ServiceElement` (`ServiceElementID`,`ServiceElementName`,`ServiceElementDescription`,`ServiceFunctionName`,`ServiceFunctionCode`,`Active`,`HasServiceScope`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`) VALUES (11,'Build','Design & Build deals with detailed technical design, test cycles/cases, functional specifications, Software coding/configuring, Unit/Component test, Release notes, Capacity planning (hardware/software licenses), Creation of a User and Operation & Maintenance Manuals.','Application Development','APP_DEV','N','N','Admin','2014-04-28 00:00:00',NULL,'2014-04-28 00:00:00');
INSERT INTO `ServiceElement` (`ServiceElementID`,`ServiceElementName`,`ServiceElementDescription`,`ServiceFunctionName`,`ServiceFunctionCode`,`Active`,`HasServiceScope`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`) VALUES (12,'Deployment/Roll Out','Deployment Roll out deals with Training, Deployment & SW installation plan, and Installation execution.','Application Development','APP_DEV','Y','N','Admin','2014-04-28 00:00:00',NULL,'2014-04-28 00:00:00');
INSERT INTO `ServiceElement` (`ServiceElementID`,`ServiceElementName`,`ServiceElementDescription`,`ServiceFunctionName`,`ServiceFunctionCode`,`Active`,`HasServiceScope`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`) VALUES (13,'Post-Release Activities','Post-release activities deal with resolving issues immediately after release installation, supporting business simulations on request and manage the switch on of  the interfaces in a staggered way, performance tune-up, post installation communication to users.','Application Development','APP_DEV','Y','N','Admin','2014-04-28 00:00:00',NULL,'2014-04-28 00:00:00');
INSERT INTO `ServiceElement` (`ServiceElementID`,`ServiceElementName`,`ServiceElementDescription`,`ServiceFunctionName`,`ServiceFunctionCode`,`Active`,`HasServiceScope`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`) VALUES (14,'Service Support','Service Support deals with planning/designing/development of scripts/data needed for the execution of technical jobs (recursive/ one shot) requested by customers on a daily basis, coordinating the scripts execution with Application Operation team, collecting and analyzing results.','Application Maintenance','APP_MAIN','Y','Y','Admin','2014-04-28 00:00:00',NULL,'2014-04-28 00:00:00');
INSERT INTO `ServiceElement` (`ServiceElementID`,`ServiceElementName`,`ServiceElementDescription`,`ServiceFunctionName`,`ServiceFunctionCode`,`Active`,`HasServiceScope`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`) VALUES (15,'Reactive Assurance','Reactive Assurance deals with Help Desk (Single point of contact for IT users, in order to manage in a very efficient/effective way the trouble tickets of the restoration of normal operational service), Incident Management (Restoring normal service operation, within SLA limits, as quickly as possible while minimizing the impact on business operations), Problem Management (TT management and root cause troubleshooting for Incidents in order to initiate actions to improve or correct the situation), Technical Impact analysis for service interruption and incident reporting, Execution of data alignment procedure only for single Tts, Bug fixing, Measurement and reporting on KPIs/SLAs.','Application Maintenance','APP_MAIN','Y','N','Admin','2014-04-28 00:00:00',NULL,'2014-04-28 00:00:00');
INSERT INTO `ServiceElement` (`ServiceElementID`,`ServiceElementName`,`ServiceElementDescription`,`ServiceFunctionName`,`ServiceFunctionCode`,`Active`,`HasServiceScope`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`) VALUES (16,'E2E Process Quality','E2E process quality deals with planning/designing/development of scripts in order to monitor the business processes KPIs (volumes/ performances), planning/designing/development of scripts in order to monitor the data quality and data alignment, analysis of business process KPIs and data quality outcomes, troubleshooting and designing/managing the relevant improvement or resolution processes or massive data re-alignment, analysis of the root causes driving trouble tickets volume, and reports preparation.','Application Maintenance','APP_MAIN','Y','N','Admin','2014-04-28 00:00:00',NULL,'2014-04-28 00:00:00');
INSERT INTO `ServiceElement` (`ServiceElementID`,`ServiceElementName`,`ServiceElementDescription`,`ServiceFunctionName`,`ServiceFunctionCode`,`Active`,`HasServiceScope`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`) VALUES (17,'E2E Test & Validation','E2E test and validation deals with System test & Integration test, Performance/Stress/Long Run tests, Operational & Security tests, User acceptance test .','Application Testing','APP_TEST','Y','N','Admin','2014-05-26 00:00:00',NULL,'2014-05-26 00:00:00');
INSERT INTO `ServiceElement` (`ServiceElementID`,`ServiceElementName`,`ServiceElementDescription`,`ServiceFunctionName`,`ServiceFunctionCode`,`Active`,`HasServiceScope`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`) VALUES (1000,'Non CCM','Just for mapping with Jobrole ','TEST','TEST','N','N','Admin','2014-05-26 00:00:00',NULL,'2014-05-26 00:00:00');
INSERT INTO `ServiceElement` (`ServiceElementID`, `ServiceElementName`,`ServiceElementDescription`, `ServiceFunctionName`, `ServiceFunctionCode`, `Active`, `HasServiceScope`, `CreatedBy`, `CreatedTimestamp`, `UpdatedTimestamp`) VALUES (18, 'CBIO','Ericsson Product', 'Ericsson Product', 'Product', 'Y', 'Y', 'Admin', '2014-08-18', '2014-08-18');
*/

# For ADM_PRE_DEV Database
INSERT INTO `ServiceElement` (`ServiceElementID`,`ServiceElementName`,`ServiceElementDescription`,`ServiceFunctionName`,`ServiceFunctionCode`,`Active`,`HasServiceScope`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`) VALUES (1,'Project Management Office','Project Management Office deals with overall coordination of the projects belonging to a program. It ensures to successfully meet all objectives in terms of scope, time, cost and quality. Additionally, it deals with managing client meetings, reporting and communication, escalation path, acceptance tracking and reporting, change control, quality management, risk/ issue management (limited to the project/program execution scope).','Application Management','APP_MGMT','Y','N','Admin',now(),NULL,now());
INSERT INTO `ServiceElement` (`ServiceElementID`,`ServiceElementName`,`ServiceElementDescription`,`ServiceFunctionName`,`ServiceFunctionCode`,`Active`,`HasServiceScope`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`) VALUES (2,'Change Management','Change Management ensures that standardised methods and procedures are used for efficient and prompt handling of all Changes. It also manages the Requirement Traceability Matrix  for new requirements, fixing and improving tasks.','Application Management','ADM_SUPP','Y','N','Admin','2014-04-28 00:00:00',NULL,'2014-04-28 00:00:00');
INSERT INTO `ServiceElement` (`ServiceElementID`,`ServiceElementName`,`ServiceElementDescription`,`ServiceFunctionName`,`ServiceFunctionCode`,`Active`,`HasServiceScope`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`) VALUES (3,'Configuration Management','Configuration Management deals with the tasks to identify, control, maintain and verify the versions of Configuration Items (CIs) in existence (for software items, infrastructure and documents). It provides accurate information on configurations and their documentation to support Incident Management, Problem Management, Change Management and Release Management.','Application Management','APP_MGMT','Y','N','Admin',now(),NULL,now());
INSERT INTO `ServiceElement` (`ServiceElementID`,`ServiceElementName`,`ServiceElementDescription`,`ServiceFunctionName`,`ServiceFunctionCode`,`Active`,`HasServiceScope`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`) VALUES (4,'SLA Management','SLA Management deals with measures and reports on KPIs/SLAs in order to evaluate the project performances.','Application Management','APP_MGMT','Y','N','Admin',now(),NULL,now());
INSERT INTO `ServiceElement` (`ServiceElementID`,`ServiceElementName`,`ServiceElementDescription`,`ServiceFunctionName`,`ServiceFunctionCode`,`Active`,`HasServiceScope`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`) VALUES (5,'Release Management','Release Management defines the content of releases and plan those accordingly to the business priorities, track the product roadmaps and provides input to change management in case on new product releases available.','Application Management','APP_MGMT','Y','N','Admin','2014-04-28 00:00:00',NULL,'2014-04-28 00:00:00');
INSERT INTO `ServiceElement` (`ServiceElementID`,`ServiceElementName`,`ServiceElementDescription`,`ServiceFunctionName`,`ServiceFunctionCode`,`Active`,`HasServiceScope`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`) VALUES (6,'Fast Track Requests','Simple configurations  to apply directly to production environment, Plan/design/development of scripts needed for the execution of technical jobs (recursive/ one shot) requested by customers on a daily basis, Support the Operation team for the scripts execution , Development and test of data alignment /data cleaning procedure','Application Management','APP_MGMT','Y','N','Admin',now(),NULL,now());
INSERT INTO `ServiceElement` (`ServiceElementID`,`ServiceElementName`,`ServiceElementDescription`,`ServiceFunctionName`,`ServiceFunctionCode`,`Active`,`HasServiceScope`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`) VALUES (7,'Demand Support & Requirements Management','Demand Support & Requirement Management deals with Business requirements collection, and impact analysis, Technical feasibility study and effort /cost estimation, Use cases design, Requirement Traceability Matrix update.','Application Development','APP_DEV','Y','N','Admin',now(),NULL,now());
INSERT INTO `ServiceElement` (`ServiceElementID`,`ServiceElementName`,`ServiceElementDescription`,`ServiceFunctionName`,`ServiceFunctionCode`,`Active`,`HasServiceScope`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`) VALUES (8,'High Level Design','High Level Design deals with High level functional analisys, Interface design (i..e. WSDL), User manual and training materials','Application Development','APP_DEV','Y','N','Admin','2014-04-28 00:00:00',NULL,'2014-04-28 00:00:00');
INSERT INTO `ServiceElement` (`ServiceElementID`,`ServiceElementName`,`ServiceElementDescription`,`ServiceFunctionName`,`ServiceFunctionCode`,`Active`,`HasServiceScope`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`) VALUES (9,'Technical Design','Technical Design deals with detailed technical design, Logical and physical data model design, IT infrastructure design (HW, OS) and sizing, Release notes, Operation&Maintanance manual.','Application Development','APP_DEV','Y','N','Admin',now(),NULL,now());
INSERT INTO `ServiceElement` (`ServiceElementID`,`ServiceElementName`,`ServiceElementDescription`,`ServiceFunctionName`,`ServiceFunctionCode`,`Active`,`HasServiceScope`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`) VALUES (10,'Build & Unit Test','Build & Unit Test deals with Software coding/configuring, Unit/Component test design and execution.','Application Development','APP_DEV','Y','N','Admin',now(),NULL,now());
INSERT INTO `ServiceElement` (`ServiceElementID`,`ServiceElementName`,`ServiceElementDescription`,`ServiceFunctionName`,`ServiceFunctionCode`,`Active`,`HasServiceScope`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`) VALUES (11,'App Testing','Application Testing deals with E2E Test plan and overall coordination of test execution, System Test, Integration Test, Non Functional, Operational, User Acceptance, Regression','Application Development','APP_DEV','Y','N','Admin',now(),NULL,now());
INSERT INTO `ServiceElement` (`ServiceElementID`,`ServiceElementName`,`ServiceElementDescription`,`ServiceFunctionName`,`ServiceFunctionCode`,`Active`,`HasServiceScope`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`) VALUES (12,'Deployment Rollout and Operation Support','Deployment Rollout and Operation Support deals with Training to business users and  operations team, Deploy & SW installation plan, Installation execution, sw distribution and double check after installation, First monitoring and performance tune-up, Deployment report, Support operation team  for script development','Application Development','APP_DEV','Y','N','Admin',now(),NULL,now());
INSERT INTO `ServiceElement` (`ServiceElementID`,`ServiceElementName`,`ServiceElementDescription`,`ServiceFunctionName`,`ServiceFunctionCode`,`Active`,`HasServiceScope`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`) VALUES (13,'Design & Execution','E2E Test plan and overall coordination of test execution.','Application Testing','APP_TEST','N','N','Admin',now(),NULL,now());
INSERT INTO `ServiceElement` (`ServiceElementID`,`ServiceElementName`,`ServiceElementDescription`,`ServiceFunctionName`,`ServiceFunctionCode`,`Active`,`HasServiceScope`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`) VALUES (14,'System Testing','System Testing deals with detailed test cycle/case desing and execution of the solution in scope with no interfaces involvement.','Application Testing','APP_TEST','Y','N','Admin',now(),NULL,now());
INSERT INTO `ServiceElement` (`ServiceElementID`,`ServiceElementName`,`ServiceElementDescription`,`ServiceFunctionName`,`ServiceFunctionCode`,`Active`,`HasServiceScope`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`) VALUES (15,'Integration Testing','Integration Testing deals with E2E test cycle/case design and execution based on business use cases involving interfaced systems.','Application Testing','APP_TEST','Y','N','Admin',now(),NULL,now());
INSERT INTO `ServiceElement` (`ServiceElementID`,`ServiceElementName`,`ServiceElementDescription`,`ServiceFunctionName`,`ServiceFunctionCode`,`Active`,`HasServiceScope`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`) VALUES (16,'UAT Testing','UAT Testing deals with support to business users test','Application Testing','APP_TEST','Y','N','Admin','2014-04-28 00:00:00',NULL,'2014-04-28 00:00:00');
INSERT INTO `ServiceElement` (`ServiceElementID`,`ServiceElementName`,`ServiceElementDescription`,`ServiceFunctionName`,`ServiceFunctionCode`,`Active`,`HasServiceScope`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`) VALUES (17,'Non-Functional Testing','Non-Functional Testing deals with test cycle/case design and execution for Performance, Stress, Long Run, Availability tests.','Application Testing','APP_TEST','Y','N','Admin',now(),NULL,now());
INSERT INTO `ServiceElement` (`ServiceElementID`,`ServiceElementName`,`ServiceElementDescription`,`ServiceFunctionName`,`ServiceFunctionCode`,`Active`,`HasServiceScope`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`) VALUES (18,'Operational Testing','Operational Testing deals with validation of operational and securty requirements done by supporting operation team','Application Testing','APP_TEST','Y','N','Admin',now(),NULL,now());
INSERT INTO `ServiceElement` (`ServiceElementID`,`ServiceElementName`,`ServiceElementDescription`,`ServiceFunctionName`,`ServiceFunctionCode`,`Active`,`HasServiceScope`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`) VALUES (19,'Regression Testing','Regression Testing deals with set of functional and non-functional  test cycles able to check  the  of functionalities.','Application Testing','APP_TEST','Y','N','Admin',now(),NULL,now());
INSERT INTO `ServiceElement` (`ServiceElementID`,`ServiceElementName`,`ServiceElementDescription`,`ServiceFunctionName`,`ServiceFunctionCode`,`Active`,`HasServiceScope`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`) VALUES (20,'1st Level Support/Service Desk','Single point of contact for business users,  operation team for the applications in scope and other operation teams by phone, email, chat, Provides how-to-use informations to bus users, Customer problem tracking, TT opening, on-call analysis and first online testing/troubleshooting, Fast track request (order) handling, Customer problems and orders reporting.','Application Maintenance','APP_MAIN','Y','N','Admin',now(),NULL,now());
INSERT INTO `ServiceElement` (`ServiceElementID`,`ServiceElementName`,`ServiceElementDescription`,`ServiceFunctionName`,`ServiceFunctionCode`,`Active`,`HasServiceScope`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`) VALUES (21,'2nd Level Support/Analysis','TT management and root cause troubleshooting; incidents-problem correlation; analysis of the root causes driving trouble tickets volume, Restores normal service operation (within SLA limits) as quickly as possible while minimizing the impact on business operations (patching, together with operation team), Technical impact analysis for service interruption and incident/problem reporting','Application Maintenance','APP_MAIN','Y','N','Admin',now(),NULL,now());
INSERT INTO `ServiceElement` (`ServiceElementID`,`ServiceElementName`,`ServiceElementDescription`,`ServiceFunctionName`,`ServiceFunctionCode`,`Active`,`HasServiceScope`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`) VALUES (22,'Bug fixing (Adaptaion/Integration Layer)','TT analisys and bug replication on internal env, Fix of a sw bug in the adaptation/integration layer, E2E coordination of all parties involved in the bug fixing process (E/// product portfolio or 3rd party product owners), Data cleaning procedure development, Release notes for fixes.','Application Maintenance','APP_MAIN','Y','N','Admin',now(),NULL,now());
INSERT INTO `ServiceElement` (`ServiceElementID`,`ServiceElementName`,`ServiceElementDescription`,`ServiceFunctionName`,`ServiceFunctionCode`,`Active`,`HasServiceScope`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`) VALUES (23,'Bug fixing (Ericsson Portfolio)','Supports bug analysis and troubleshooting, Fix of a sw bug located either into product customisation or product kernel layers, Release notes for fixes.','Application Maintenance','APP_MAIN','Y','N','Admin','2014-05-26 00:00:00',NULL,'2014-05-26 00:00:00');
INSERT INTO `ServiceElement` (`ServiceElementID`,`ServiceElementName`,`ServiceElementDescription`,`ServiceFunctionName`,`ServiceFunctionCode`,`Active`,`HasServiceScope`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`) VALUES (24,'Bug fixing (Non Ericsson Portfolio)','Supporst bug analysis and troubleshooting with 3° party products, Manages the E2E interactions 3rd parties for every analysis, troubleshooting and bug fixing activities involving the kernel of a 3rd party product, Release notes for fixes.','Application Maintenance','APP_MAIN','Y','N','Admin',now(),NULL,now());
INSERT INTO `ServiceElement` (`ServiceElementID`,`ServiceElementName`,`ServiceElementDescription`,`ServiceFunctionName`,`ServiceFunctionCode`,`Active`,`HasServiceScope`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`) VALUES (25,'Business Activity Monitoring','Plan/design/development of scripts to monitor the business KPIs, Business process KPIs monitoring and analysis/ trend analysis  from performances, quality and volume perspective, Reporting.','Application Maintenance','APP_MAIN','Y','N','Admin',now(),NULL,now());

INSERT INTO `ServiceElement` (`ServiceElementID`,`ServiceElementName`,`ServiceElementDescription`,`ServiceFunctionName`,`ServiceFunctionCode`,`Active`,`HasServiceScope`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`) VALUES (1000,'Non CCM','Just for mapping with Jobrole ','TEST','TEST','N','N','Admin','2014-05-26 00:00:00',NULL,'2014-05-26 00:00:00');



