/*
-- Query: SELECT * FROM IT_MSSP_UAT.ServiceScope
LIMIT 0, 1000

-- Date: 2014-05-08 15:07
*/
/*
INSERT INTO `ServiceScope` (`ServiceScopeID`,`ServiceScopeCategory`,`ServiceScopeName`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`,`ServiceElementID`,`ServiceScopeDescription`,`Active`,`ServiceElementDefaultValue`) VALUES (1,'Service Support','Service Desk','Admin','2014-04-28 00:00:00','','2014-04-28 00:00:00',14,'A Service Desk is a functional unit within IT Operations framework comprising staff from 1st Level Operations team that will be dealing with a variety of Service Events. The solution design for the Service Desk tower is based on technical, cultural, behavioral and soft-skill characteristics as desired by Customer in its IT model. Typical \'Service Desk\' function includes provide a single point of contact through Vendor provided toll free numbers (where possible), e-mail addresses and web access via a web-enabled interface, as approved by client, Support for planned contract volume overflow i.e. to provide support for handling increased contact volumes resulting from planned business initiatives and new programs, Data recording & retention, Provide on going maintenance support for web-based portal for functions including: reporting Incidents, user self-help information, password reset, and self-heal etc, Level1 Service Desk support (e.g. Incident detection, recording and reporting), Record and classify Service Requests, Provide reporting requirement support by design, develop, maintain and deliver Service Desk reports as approved by client','Y',null);
INSERT INTO `ServiceScope` (`ServiceScopeID`,`ServiceScopeCategory`,`ServiceScopeName`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`,`ServiceElementID`,`ServiceScopeDescription`,`Active`,`ServiceElementDefaultValue`) VALUES (2,'Service Support','1st Level Support','Admin','2014-04-28 00:00:00','','2014-04-28 00:00:00',14,'The function of IT Operations is to execute ongoing activities and procedures required to manage and maintain the IT infrastructure so as to deliver and support IT services at agreed levels. Level 1 consists mainly of Less- skilled resources executing actions based on prescribed processes and instructions. The Level 1 Service function comprises the following service elements, each of them performing a specific set of tasks. The activities carried out by these service elements have been elaborated upon in below sections - Access Management (provide the right for users to be able to access the service), Service Request resolution (responsible for managing the lifecycle of all service requests from the end-users), Event Management (process that monitors all events that occur through the IT landscape and also detects and escalates exception conditions), L1 Operations (performing corrective or preventive activities as coordinated by L2 Operations, e.g. Billing operations) , L1 Service Assurance (The 1st level Service Assurance element will act as the Service Desk to all channels through which Service Requests, Incidents, Problems etc. are raised by End User. typical sub-functions include L1 Preventive Maintenance, L1 Change Execution, L1 Routine Operations, L1 Performance Reporting, L1 Release and Deployment) & L1 Incident Resolution (Whenever any incident is raised, the 1st Level Operations will investigate the cause of the incident and will attempt to fix the same)','Y',null);
INSERT INTO `ServiceScope` (`ServiceScopeID`,`ServiceScopeCategory`,`ServiceScopeName`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`,`ServiceElementID`,`ServiceScopeDescription`,`Active`,`ServiceElementDefaultValue`) VALUES (3,'Service Support','2nd Level Support','Admin','2014-04-28 00:00:00','','2014-04-28 00:00:00',14,'Level 2 IT Operations s a level above the Level 1 operation in the hierarchy and acts as an escalation point for issues which cannot be taken care at Level 1. Level 2 operations ideally should have  resources with higher domain knowledge on technical and application specific areas. It is the responsibility of Level 2 operations to prescribe processes and define instructions which are eventually carried out by Level 1 team. Services delivered under the proposed scope of work as part of Level-2 IT-Operations are categorized under different service elements - L2 Operations (routine operations like managing billing data transfer, processing and define corrective or preventive activities around the same)  , L2 Service Assurance (The L2 Service Assurance service element will be responsible for managing system generated data, testing system performance, performing backups, analyzing fault records & system logs and resolving  known bugs in the system.  L2 Service Assurance consists of the following sub-elements like L2 Preventive Maintenance, L2 Change Analysis, L2 Routine Operations, L2 Performance Reporting),  L2 Incident Support (Represents the activities carried out in 2nd Level operations to restore normal service as quickly as possible and minimize the adverse impact on business operations, thus ensuring that the agreed SLA are maintained) , Availability Management ( To ensure that the level of Servi','Y',null);
INSERT INTO `ServiceScope` (`ServiceScopeID`,`ServiceScopeCategory`,`ServiceScopeName`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`,`ServiceElementID`,`ServiceScopeDescription`,`Active`,`ServiceElementDefaultValue`) VALUES (4,'Service Support','3rd Level Support','Admin','2014-04-28 00:00:00','','2014-04-28 00:00:00',14,'This scope element typically termed as Level 3 Problem Resolution & Level3 Enhancement. Level3 problem resolution constitutes support estimates for the effort required to create and complete typical change request orders (CRO) either triggered through 2nd level operations layer or invoked separately.CROs include supporting a new patch, fixing a data integrity issue or  addressing application updates that require migration. Enhancement stands for third level development support that estimates the effort required to maintain the existing interfaces, extensions/conversions, eScripts, reports/forms/views, and workflows that are used with the packaged software application.  This maintenance effort may be initiated by change request orders, but it is planned for and estimated separately. This support also includes additional specialized skills that may be needed for bolt on applications, such as tax software, computer telephony integration, or enterprise integration software etc.','N',null);
INSERT INTO `ServiceScope` (`ServiceScopeID`,`ServiceScopeCategory`,`ServiceScopeName`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`,`ServiceElementID`,`ServiceScopeDescription`,`Active`,`ServiceElementDefaultValue`) VALUES (5,'ADM & Testing','Development / Enhancement','Admin','2014-04-28 00:00:00','','2014-04-28 00:00:00',14,'This scope element typically termed as Level 3 Problem Resolution & Level3 Enhancement. Level3 problem resolution constitutes support estimates for the effort required to create and complete typical change request orders (CRO) either triggered through 2nd level operations layer or invoked separately.CROs include supporting a new patch, fixing a data integrity issue or  addressing application updates that require migration. Enhancement stands for third level development support that estimates the effort required to maintain the existing interfaces, extensions/conversions, eScripts, reports/forms/views, and workflows that are used with the packaged software application.  This maintenance effort may be initiated by change request orders, but it is planned for and estimated separately. This support also includes additional specialized skills that may be needed for bolt on applications, such as tax software, computer telephony integration, or enterprise integration software etc.','N',null);
INSERT INTO `ServiceScope` (`ServiceScopeID`,`ServiceScopeCategory`,`ServiceScopeName`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`,`ServiceElementID`,`ServiceScopeDescription`,`Active`,`ServiceElementDefaultValue`) VALUES (6,'ADM & Testing','MS TAAS','Admin','2014-04-28 00:00:00','','2014-04-28 00:00:00',14,'This scope element has two dimensions. One being testing as a percentage of Development & enhancement effort and other being full end to end testing  or testing as a service. In the first case percentage of functional and regression testing will be key input. Testing as a service typically has following service elements - End-To-End System Integration Testing (System Integration Testing of Front office, Middleware, and Back-Office cross-applications & End-to-end business flow testing), User Acceptance Testing / Production Testing Support, Automation Testing ( intended to Increase regression automation coverage), Performance Testing , Environment Mgmt (Maintaining the Test Environment Systems to meet business and technical requirements , Assist in test data management & for applications in testing scope) etc.','N',null);
INSERT INTO `ServiceScope` (`ServiceScopeID`,`ServiceScopeCategory`,`ServiceScopeName`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`,`ServiceElementID`,`ServiceScopeDescription`,`Active`,`ServiceElementDefaultValue`) VALUES (7,'Discretionary Services','Governance & PMO','Admin','2014-04-28 00:00:00','','2014-04-28 00:00:00',14,'This scope element typically represents the proportion of Governance & Overheads in engagements of varying sizes. This percentage should be ideally applied based on EGI guidelines as published. The guideline on the Governance Overheads are available for different engagements mapped against the GSC-I Rate Card Roles during Steady State and Transformation','N',null);
INSERT INTO `ServiceScope` (`ServiceScopeID`,`ServiceScopeCategory`,`ServiceScopeName`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`,`ServiceElementID`,`ServiceScopeDescription`,`Active`,`ServiceElementDefaultValue`) VALUES (8,'Discretionary Services','Transition & Transformation','Admin','2014-04-28 00:00:00','','2014-04-28 00:00:00',14,'The scope element follows Ericsson\'s Best Practices of Global Transformation, this enable user to prepare for operations readiness prior to commencement of Services. The entire knowledge transfer process may be divided into several distinct and self-contained stages: Analysis , Planning, Learn, Assist,Perform,Deliver,Stabilization Phase & Steady State. This section allow use to develop Application specific transfer plans in conjunction with the Region/EGI Transition Manager/customer/incumbent vendor teams.  The focus of this plan is to identify critical application areas and allocate time appropriately across these key areas. The key components are - Detailed training plans which constitutes the application level blue print for knowledge transfer sessions, Staffing Plan identifies skills requirements mapping of Region/EGI resources to incumbent supplier resources for Knowledge Transfer, staff ramp up and ramp down , Details of in-flight projects and plans to address them during migration with clear definition of transition points, Application specific risks and mitigation plans. EGI guideline is available which defines the proposed duration of each phase of transformation, the key adjusting levers, proportion of short term travels during knowledge transfer and associated ramp up/down','N',null);
INSERT INTO `ServiceScope` (`ServiceScopeID`,`ServiceScopeCategory`,`ServiceScopeName`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`,`ServiceElementID`,`ServiceScopeDescription`,`Active`,`ServiceElementDefaultValue`) VALUES (9,'Discretionary Services','Other Miscellaneous','Admin','2014-04-28 00:00:00','','2014-04-28 00:00:00',14,'This scope element allow users to document and estimate all other miscellaneous scope defination not listed in the standard IT Managed Service scope. Solution Manager has the discretion to add additional FTEs to support additional roles. Separate estimation needs to be carried out for these additional roles.','N',null);
INSERT INTO `ServiceScope` (`ServiceScopeID`,`ServiceScopeCategory`,`ServiceScopeName`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`,`ServiceElementID`,`ServiceScopeDescription`,`Active`,`ServiceElementDefaultValue`) VALUES (10,'Program Management','Program Management','Admin','2014-04-28 00:00:00','','2014-04-28 00:00:00',1,'','Y',20);
INSERT INTO `ServiceScope` (`ServiceScopeID`,`ServiceScopeCategory`,`ServiceScopeName`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`,`ServiceElementID`,`ServiceScopeDescription`,`Active`,`ServiceElementDefaultValue`) VALUES (11,'Release Management','Release Management','Admin','2014-04-28 00:00:00','','2014-04-28 00:00:00',2,'','Y',20);
INSERT INTO `ServiceScope` (`ServiceScopeID`,`ServiceScopeCategory`,`ServiceScopeName`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`,`ServiceElementID`,`ServiceScopeDescription`,`Active`,`ServiceElementDefaultValue`) VALUES (12,'Change Management','Change Management','Admin','2014-04-28 00:00:00','','2014-04-28 00:00:00',3,'','Y',20);
INSERT INTO `ServiceScope` (`ServiceScopeID`,`ServiceScopeCategory`,`ServiceScopeName`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`,`ServiceElementID`,`ServiceScopeDescription`,`Active`,`ServiceElementDefaultValue`) VALUES (13,'Capacity Management','Capacity Management','Admin','2014-04-28 00:00:00','','2014-04-28 00:00:00',4,'','Y',5);
INSERT INTO `ServiceScope` (`ServiceScopeID`,`ServiceScopeCategory`,`ServiceScopeName`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`,`ServiceElementID`,`ServiceScopeDescription`,`Active`,`ServiceElementDefaultValue`) VALUES (14,'Configuration Management','Configuration Management','Admin','2014-04-28 00:00:00','','2014-04-28 00:00:00',5,'','Y',20);
INSERT INTO `ServiceScope` (`ServiceScopeID`,`ServiceScopeCategory`,`ServiceScopeName`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`,`ServiceElementID`,`ServiceScopeDescription`,`Active`,`ServiceElementDefaultValue`) VALUES (15,'Security Management','Security Management','Admin','2014-04-28 00:00:00','','2014-04-28 00:00:00',6,'','Y',5);
INSERT INTO `ServiceScope` (`ServiceScopeID`,`ServiceScopeCategory`,`ServiceScopeName`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`,`ServiceElementID`,`ServiceScopeDescription`,`Active`,`ServiceElementDefaultValue`) VALUES (16,'Availability Management','Availability Management','Admin','2014-04-28 00:00:00','','2014-04-28 00:00:00',7,'','Y',5);
INSERT INTO `ServiceScope` (`ServiceScopeID`,`ServiceScopeCategory`,`ServiceScopeName`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`,`ServiceElementID`,`ServiceScopeDescription`,`Active`,`ServiceElementDefaultValue`) VALUES (17,'Access Management','Access Management','Admin','2014-04-28 00:00:00','','2014-04-28 00:00:00',8,'','Y',5);
INSERT INTO `ServiceScope` (`ServiceScopeID`,`ServiceScopeCategory`,`ServiceScopeName`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`,`ServiceElementID`,`ServiceScopeDescription`,`Active`,`ServiceElementDefaultValue`) VALUES (18,'Demand Support','Demand Support','Admin','2014-04-28 00:00:00','','2014-04-28 00:00:00',9,'','Y',null);
INSERT INTO `ServiceScope` (`ServiceScopeID`,`ServiceScopeCategory`,`ServiceScopeName`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`,`ServiceElementID`,`ServiceScopeDescription`,`Active`,`ServiceElementDefaultValue`) VALUES (19,'Design','Design & Build','Admin','2014-04-28 00:00:00','','2014-04-28 00:00:00',10,'','Y',null);
INSERT INTO `ServiceScope` (`ServiceScopeID`,`ServiceScopeCategory`,`ServiceScopeName`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`,`ServiceElementID`,`ServiceScopeDescription`,`Active`,`ServiceElementDefaultValue`) VALUES (20,'Build','Build','Admin','2014-04-28 00:00:00','','2014-04-28 00:00:00',11,'','N',null);
INSERT INTO `ServiceScope` (`ServiceScopeID`,`ServiceScopeCategory`,`ServiceScopeName`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`,`ServiceElementID`,`ServiceScopeDescription`,`Active`,`ServiceElementDefaultValue`) VALUES (21,'Deployment Roll Out','Deployment/Rollout','Admin','2014-04-28 00:00:00','','2014-04-28 00:00:00',12,'','Y',null);
INSERT INTO `ServiceScope` (`ServiceScopeID`,`ServiceScopeCategory`,`ServiceScopeName`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`,`ServiceElementID`,`ServiceScopeDescription`,`Active`,`ServiceElementDefaultValue`) VALUES (22,'Post-Release Activities','Post-Release Activities','Admin','2014-04-28 00:00:00','','2014-04-28 00:00:00',13,'','Y',null);
INSERT INTO `ServiceScope` (`ServiceScopeID`,`ServiceScopeCategory`,`ServiceScopeName`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`,`ServiceElementID`,`ServiceScopeDescription`,`Active`,`ServiceElementDefaultValue`) VALUES (23,'Reactive Assurance','Reactive Assurance','Admin','2014-04-28 00:00:00','','2014-04-28 00:00:00',15,'','Y',null);
INSERT INTO `ServiceScope` (`ServiceScopeID`,`ServiceScopeCategory`,`ServiceScopeName`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`,`ServiceElementID`,`ServiceScopeDescription`,`Active`,`ServiceElementDefaultValue`) VALUES (24,'E2e Process Quality','E2e Process Quality','Admin','2014-04-28 00:00:00','','2014-04-28 00:00:00',16,'','Y',null);
INSERT INTO `ServiceScope` (`ServiceScopeID`,`ServiceScopeCategory`,`ServiceScopeName`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`,`ServiceElementID`,`ServiceScopeDescription`,`Active`,`ServiceElementDefaultValue`) VALUES (25,'E2e Test & Validation','E2e Test & Validation','Admin','2014-04-28 00:00:00','','2014-04-28 00:00:00',17,'','Y',100);
INSERT INTO `ServiceScope` (`ServiceScopeID`, `ServiceScopeCategory`, `ServiceScopeName`, `ServiceElementID`, `Active`, `CreatedBy`, `CreatedTimestamp`, `UpdatedTimestamp`) VALUES (26, 'CBIO', 'CS', 18, 'Y', 'Admin', '2014-08-18', '2014-08-18');
INSERT INTO `ServiceScope` (`ServiceScopeID`, `ServiceScopeCategory`, `ServiceScopeName`, `ServiceElementID`, `Active`, `CreatedBy`, `CreatedTimestamp`, `UpdatedTimestamp`) VALUES (27, 'CBIO', 'BSCS', 18, 'Y', 'Admin', '2014-08-18', '2014-08-18');
INSERT INTO `ServiceScope` (`ServiceScopeID`, `ServiceScopeCategory`, `ServiceScopeName`, `ServiceElementID`, `Active`, `CreatedBy`, `CreatedTimestamp`, `UpdatedTimestamp`) VALUES (28, 'CBIO', 'EMA', 18, 'Y', 'Admin', '2014-08-18', '2014-08-18');
INSERT INTO `ServiceScope` (`ServiceScopeID`, `ServiceScopeCategory`, `ServiceScopeName`, `ServiceElementID`, `Active`, `CreatedBy`, `CreatedTimestamp`, `UpdatedTimestamp`) VALUES (29, 'CBIO', 'EMM', 18, 'Y', 'Admin', '2014-08-18', '2014-08-18');
*/

# For ADM_PRE_DEV Database
INSERT INTO `ServiceScope` (`ServiceScopeID`,`ServiceScopeCategory`,`ServiceScopeName`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`,`ServiceElementID`,`ServiceScopeDescription`,`Active`,`ServiceElementDefaultValue`) VALUES (1,'Application Management','Project Management Office','Admin',now(),'',now(),1,'Project Management Office deals with overall coordination of the projects belonging to a program. It ensures to successfully meet all objectives in terms of scope, time, cost and quality. Additionally, it deals with managing client meetings, reporting and communication, escalation path, acceptance tracking and reporting, change control, quality management, risk/ issue management (limited to the project/program execution scope).Service Desk function includes provide a single point of contact through Vendor provided toll free numbers (where possible), e-mail addresses and web access via a web-enabled interface, as approved by client, Support for planned contract volume overflow i.e. to provide support for handling increased contact volumes resulting from planned business initiatives and new programs, Data recording & retention, Provide on going maintenance support for web-based portal for functions including: reporting Incidents, user self-help information, password reset, and self-heal etc, Level1 Service Desk support (e.g. Incident detection, recording and reporting), Record and classify Service Requests, Provide reporting requirement support by design, develop, maintain and deliver Service Desk reports as approved by client','Y',null);
INSERT INTO `ServiceScope` (`ServiceScopeID`,`ServiceScopeCategory`,`ServiceScopeName`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`,`ServiceElementID`,`ServiceScopeDescription`,`Active`,`ServiceElementDefaultValue`) VALUES (2,'Application Management','Change Management','Admin',now(),'',now(),2,'Change Management ensures that standardised methods and procedures are used for efficient and prompt handling of all Changes. It also manages the Requirement Traceability Matrix  for new requirements, fixing and improving tasks.','Y',null);
INSERT INTO `ServiceScope` (`ServiceScopeID`,`ServiceScopeCategory`,`ServiceScopeName`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`,`ServiceElementID`,`ServiceScopeDescription`,`Active`,`ServiceElementDefaultValue`) VALUES (3,'Application Management','Configuration Management','Admin',now(),'',now(),3,'Configuration Management deals with the tasks to identify, control, maintain and verify the versions of Configuration Items (CIs) in existence (for software items, infrastructure and documents). It provides accurate information on configurations and their documentation to support Incident Management, Problem Management, Change Management and Release Management.','Y',null);
INSERT INTO `ServiceScope` (`ServiceScopeID`,`ServiceScopeCategory`,`ServiceScopeName`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`,`ServiceElementID`,`ServiceScopeDescription`,`Active`,`ServiceElementDefaultValue`) VALUES (4,'Application Management','SLA Management','Admin',now(),'',now(),4,'SLA Management deals with measures and reports on KPIs/SLAs in order to evaluate the project performances.','Y',null);
INSERT INTO `ServiceScope` (`ServiceScopeID`,`ServiceScopeCategory`,`ServiceScopeName`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`,`ServiceElementID`,`ServiceScopeDescription`,`Active`,`ServiceElementDefaultValue`) VALUES (5,'Application Management','Release Management','Admin',now(),'',now(),5,'Release Management defines the content of releases and plan those accordingly to the business priorities, track the product roadmaps and provides input to change management in case on new product releases available.','Y',null);
INSERT INTO `ServiceScope` (`ServiceScopeID`,`ServiceScopeCategory`,`ServiceScopeName`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`,`ServiceElementID`,`ServiceScopeDescription`,`Active`,`ServiceElementDefaultValue`) VALUES (6,'Application Management','Fast Track Requests','Admin',now(),'',now(),6,'Simple configurations  to apply directly to production environment, Plan/design/development of scripts needed for the execution of technical jobs (recursive/ one shot) requested by customers on a daily basis, Support the Operation team for the scripts execution , Development and test of data alignment /data cleaning procedure','Y',null);
INSERT INTO `ServiceScope` (`ServiceScopeID`,`ServiceScopeCategory`,`ServiceScopeName`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`,`ServiceElementID`,`ServiceScopeDescription`,`Active`,`ServiceElementDefaultValue`) VALUES (7,'Application Development','Demand Support & Requirements Management','Admin',now(),'',now(),7,'Demand Support & Requirement Management deals with Business requirements collection, and impact analysis, Technical feasibility study and effort /cost estimation, Use cases design, Requirement Traceability Matrix update.','Y',null);
INSERT INTO `ServiceScope` (`ServiceScopeID`,`ServiceScopeCategory`,`ServiceScopeName`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`,`ServiceElementID`,`ServiceScopeDescription`,`Active`,`ServiceElementDefaultValue`) VALUES (8,'Application Development','High Level Design','Admin',now(),'',now(),8,'High Level Design deals with High level functional analisys, Interface design (i..e. WSDL), User manual and training materials','Y',null);
INSERT INTO `ServiceScope` (`ServiceScopeID`,`ServiceScopeCategory`,`ServiceScopeName`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`,`ServiceElementID`,`ServiceScopeDescription`,`Active`,`ServiceElementDefaultValue`) VALUES (9,'Application Development','Technical Design','Admin',now(),'',now(),9,'Technical Design deals with detailed technical design, Logical and physical data model design, IT infrastructure design (HW, OS) and sizing, Release notes, Operation&Maintanance manual.','Y',null);
INSERT INTO `ServiceScope` (`ServiceScopeID`,`ServiceScopeCategory`,`ServiceScopeName`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`,`ServiceElementID`,`ServiceScopeDescription`,`Active`,`ServiceElementDefaultValue`) VALUES (10,'Application Development','Build & Unit Test','Admin',now(),'',now(),10,'Build & Unit Test deals with Software coding/configuring, Unit/Component test design and execution.','Y',null);
INSERT INTO `ServiceScope` (`ServiceScopeID`,`ServiceScopeCategory`,`ServiceScopeName`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`,`ServiceElementID`,`ServiceScopeDescription`,`Active`,`ServiceElementDefaultValue`) VALUES (11,'Application Development','App Testing','Admin',now(),'',now(),11,'','Y',null);
INSERT INTO `ServiceScope` (`ServiceScopeID`,`ServiceScopeCategory`,`ServiceScopeName`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`,`ServiceElementID`,`ServiceScopeDescription`,`Active`,`ServiceElementDefaultValue`) VALUES (12,'Application Development','Deployment Rollout and Operation Support','Admin',now(),'',now(),12,'','Y',null);
INSERT INTO `ServiceScope` (`ServiceScopeID`,`ServiceScopeCategory`,`ServiceScopeName`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`,`ServiceElementID`,`ServiceScopeDescription`,`Active`,`ServiceElementDefaultValue`) VALUES (13,'Application Testing','Design & Execution','Admin',now(),'',now(),13,'','N',null);
INSERT INTO `ServiceScope` (`ServiceScopeID`,`ServiceScopeCategory`,`ServiceScopeName`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`,`ServiceElementID`,`ServiceScopeDescription`,`Active`,`ServiceElementDefaultValue`) VALUES (14,'Application Testing','System Testing','Admin',now(),'',now(),14,'','Y',null);
INSERT INTO `ServiceScope` (`ServiceScopeID`,`ServiceScopeCategory`,`ServiceScopeName`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`,`ServiceElementID`,`ServiceScopeDescription`,`Active`,`ServiceElementDefaultValue`) VALUES (15,'Application Testing','Integration Testing','Admin',now(),'',now(),15,'','Y',null);
INSERT INTO `ServiceScope` (`ServiceScopeID`,`ServiceScopeCategory`,`ServiceScopeName`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`,`ServiceElementID`,`ServiceScopeDescription`,`Active`,`ServiceElementDefaultValue`) VALUES (16,'Application Testing','UAT Testing','Admin',now(),'',now(),16,'','Y',null);
INSERT INTO `ServiceScope` (`ServiceScopeID`,`ServiceScopeCategory`,`ServiceScopeName`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`,`ServiceElementID`,`ServiceScopeDescription`,`Active`,`ServiceElementDefaultValue`) VALUES (17,'Application Testing','Non-Functional Testing','Admin',now(),'',now(),17,'','Y',null);
INSERT INTO `ServiceScope` (`ServiceScopeID`,`ServiceScopeCategory`,`ServiceScopeName`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`,`ServiceElementID`,`ServiceScopeDescription`,`Active`,`ServiceElementDefaultValue`) VALUES (18,'Application Testing','Operational Testing','Admin',now(),'',now(),18,'','Y',null);
INSERT INTO `ServiceScope` (`ServiceScopeID`,`ServiceScopeCategory`,`ServiceScopeName`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`,`ServiceElementID`,`ServiceScopeDescription`,`Active`,`ServiceElementDefaultValue`) VALUES (19,'Application Testing','Regression Testing','Admin',now(),'',now(),19,'','Y',null);
INSERT INTO `ServiceScope` (`ServiceScopeID`,`ServiceScopeCategory`,`ServiceScopeName`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`,`ServiceElementID`,`ServiceScopeDescription`,`Active`,`ServiceElementDefaultValue`) VALUES (20,'Application Maintenance','1st Level Support/Service Desk','Admin',now(),'',now(),20,'','Y',null);
INSERT INTO `ServiceScope` (`ServiceScopeID`,`ServiceScopeCategory`,`ServiceScopeName`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`,`ServiceElementID`,`ServiceScopeDescription`,`Active`,`ServiceElementDefaultValue`) VALUES (21,'Application Maintenance','2nd Level Support/Analysis','Admin',now(),'',now(),21,'','Y',null);
INSERT INTO `ServiceScope` (`ServiceScopeID`,`ServiceScopeCategory`,`ServiceScopeName`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`,`ServiceElementID`,`ServiceScopeDescription`,`Active`,`ServiceElementDefaultValue`) VALUES (22,'Application Maintenance','Bug fixing (Adaptaion/Integration Layer)','Admin',now(),'',now(),22,'','Y',null);
INSERT INTO `ServiceScope` (`ServiceScopeID`,`ServiceScopeCategory`,`ServiceScopeName`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`,`ServiceElementID`,`ServiceScopeDescription`,`Active`,`ServiceElementDefaultValue`) VALUES (23,'Application Maintenance','Bug fixing (Ericsson Portfolio)','Admin',now(),'',now(),23,'','Y',null);
INSERT INTO `ServiceScope` (`ServiceScopeID`,`ServiceScopeCategory`,`ServiceScopeName`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`,`ServiceElementID`,`ServiceScopeDescription`,`Active`,`ServiceElementDefaultValue`) VALUES (24,'Application Maintenance','Bug fixing (Non Ericsson Portfolio)','Admin',now(),'',now(),24,'','Y',null);
INSERT INTO `ServiceScope` (`ServiceScopeID`,`ServiceScopeCategory`,`ServiceScopeName`,`CreatedBy`,`CreatedTimestamp`,`UpdatedBy`,`UpdatedTimestamp`,`ServiceElementID`,`ServiceScopeDescription`,`Active`,`ServiceElementDefaultValue`) VALUES (25,'Application Maintenance','Business Activity Monitoring','Admin',now(),'',now(),25,'','Y',null);
/*
INSERT INTO `ServiceScope` (`ServiceScopeID`,`ServiceScopeCategory`,`ServiceScopeName`, `ServiceElementID`, `Active`, `CreatedBy`, `CreatedTimestamp`, `UpdatedTimestamp`) VALUES (26, 'CBIO', 'CS', 18, 'Y', 'Admin', '2014-08-18', '2014-08-18');
INSERT INTO `ServiceScope` (`ServiceScopeID`,`ServiceScopeCategory`,`ServiceScopeName`, `ServiceElementID`, `Active`, `CreatedBy`, `CreatedTimestamp`, `UpdatedTimestamp`) VALUES (27, 'CBIO', 'BSCS', 18, 'Y', 'Admin', '2014-08-18', '2014-08-18');
INSERT INTO `ServiceScope` (`ServiceScopeID`,`ServiceScopeCategory`,`ServiceScopeName`, `ServiceElementID`, `Active`, `CreatedBy`, `CreatedTimestamp`, `UpdatedTimestamp`) VALUES (28, 'CBIO', 'EMA', 18, 'Y', 'Admin', '2014-08-18', '2014-08-18');
INSERT INTO `ServiceScope` (`ServiceScopeID`,`ServiceScopeCategory`,`ServiceScopeName`, `ServiceElementID`, `Active`, `CreatedBy`, `CreatedTimestamp`, `UpdatedTimestamp`) VALUES (29, 'CBIO', 'EMM', 18, 'Y', 'Admin', '2014-08-18', '2014-08-18');
*/