INSERT INTO STAFF_CATEGORY(ID,CATEGORY)VALUES(1,'Contractors');
INSERT INTO STAFF_CATEGORY(ID,CATEGORY)VALUES(2,'GSC India');
INSERT INTO STAFF_CATEGORY(ID,CATEGORY)VALUES(3,'Other GSC');
INSERT INTO STAFF_CATEGORY(ID,CATEGORY)VALUES(4,'Region');
