##Command \. /home/edassri/workspace/IT_MSSP/DB/initData/DMLs/DataCleanup.sql
delete from  APAComplexity;   
delete from  APAWeightage;   
delete from  AdditionalFTE ; 
delete from  CheckLists;     
delete from  CostSummary ;   
delete from  EfficiencyLever;
delete from  FTEStaging;     
delete from  FTESummary;     
delete from  GenericTestingInputs;
delete from  GenericTestingOverhead; 
delete from  InputFields;    
delete from  LESS_EFFORT;  
delete from  LocationBreakup;
delete from  LocationPyramid;
delete from  NonLabourCost;
delete from  OpportunityLocation;
delete from  OpportunityDetail;
delete from  OpportunityScope;
delete from  PEOPLE_STACK;
delete from  PeopleStackResourceDetails;
delete from  PeopleStackStartUpFTE;
delete from  PeopleStackSummary;
delete from  ProductivityLever; 
alter table  ProductivityLever auto_increment=1;
delete from  RegressionLever;
delete from  STAFF_CATEGORY_ALLOCATION;
delete from  SolutionADR;
delete from  SolutionAPA;    
delete from  SolutionEnhanDevFixedDeposite;
delete from  SolutionEnhanDevRICEFW;
delete from  SolutionGovAndPMO;
delete from  SolutionInputDefinition;
delete from  SolutionL1AddServices;
delete from  SolutionL1Operations;
delete from  SolutionL2AddServices;
delete from  SolutionL2Operations;
delete from  SolutionL3AddServices;
delete from  SolutionL3Operations;
delete from  SolutionLever;
delete from  SolutionApproachDimension;
delete from  SolutionApprovalStatus;
delete from  SolutionApprover;
delete from  SolutionComplexity;
delete from  SolutionOtherMisc;
delete from  SolutionServiceDesk;
delete from  Solution_People_Stack;
delete from SolutionTestingAsAService;
alter table SolutionTestingAsAService  auto_increment=1;
delete from  StaffingPlan;
delete from  StartUpFTE;   
delete from  TNTDetail;     
delete from  TNTPartitionDate;
delete from  TestEffReduction;
delete from  TestingService;
delete from  WorkflowTimeline;
delete from  Solution;
delete from  Opportunity;
delete from  Customer;       

truncate APAComplexity;   
truncate APAWeightage;   
truncate AdditionalFTE ; 
truncate CheckLists;     
truncate CostSummary ;   
alter table Customer auto_increment=1;       
truncate EfficiencyLever;
truncate FTEStaging;     
truncate FTESummary;     
truncate GenericTestingInputs;
truncate GenericTestingOverhead; 
alter table InputFields auto_increment=1;    
truncate LESS_EFFORT;  
truncate LocationBreakup;
truncate LocationPyramid;
truncate NonLabourCost;
alter table  Opportunity auto_increment=1;  
alter table  OpportunityDetail auto_increment=1;  
alter table OpportunityLocation auto_increment=1; 
alter table OpportunityScope auto_increment=1; 
truncate PEOPLE_STACK;
truncate PeopleStackResourceDetails;
truncate PeopleStackStartUpFTE;
truncate PeopleStackSummary;
truncate ProductivityLever;
truncate RegressionLever;
truncate STAFF_CATEGORY_ALLOCATION;
alter table Solution auto_increment=1;
truncate SolutionADR;
truncate SolutionAPA;    
alter table  SolutionApproachDimension auto_increment=1;
alter table  SolutionApprovalStatus auto_increment=1;
alter table  SolutionApprover auto_increment=1;
alter table  SolutionComplexity auto_increment=1;
alter table  SolutionEnhanDevFixedDeposite auto_increment=1;
alter table  SolutionEnhanDevRICEFW auto_increment=1;
alter table  SolutionGovAndPMO auto_increment=1;
alter table  SolutionInputDefinition auto_increment=1;
alter table  SolutionL1AddServices auto_increment=1;
alter table  SolutionL1Operations auto_increment=1;
alter table  SolutionL2AddServices auto_increment=1;
alter table  SolutionL2Operations auto_increment=1;
alter table  SolutionL3AddServices auto_increment=1;
alter table  SolutionL3Operations auto_increment=1;
alter table  SolutionLever auto_increment=1;
alter table  SolutionOtherMisc auto_increment=1;
alter table  SolutionServiceDesk auto_increment=1;
alter table  Solution_People_Stack auto_increment=1;
alter table  StaffingPlan auto_increment=1;
alter table  StartUpFTE auto_increment=1;   
alter table  TNTDetail auto_increment=1;     
alter table  TNTPartitionDate auto_increment=1;
alter table  TestEffReduction auto_increment=1;
alter table  TestingService auto_increment=1;
alter table  WorkflowTimeline auto_increment=1;
