####Command \. /home/edassri/workspace/IT_MSSP/DB/initData/DMLs/MasterDataCleanup.sql
truncate ApplicationConfig; 
delete from Opportunity;
delete from OpportunitySource;
alter table OpportunitySource auto_increment=1;
truncate OtherDefaults;
delete from CheckListMaster; 
alter table  CheckListMaster auto_increment=1;
delete from RateCard;
truncate RateCard;
truncate ExchangeRate;
delete from JobRole;
alter table  JobRole auto_increment=1;
delete from CommercialModel;
alter table   CommercialModel auto_increment=1;  
delete from ScopeOfServicesDefinedBy;
alter table   ScopeOfServicesDefinedBy auto_increment=1;
delete from Country;
alter table   Country auto_increment=1;
delete from DealCharacteristics;
alter table   DealCharacteristics auto_increment=1;
delete from STAFF_CATEGORY;
alter table   STAFF_CATEGORY auto_increment=1;
delete from DeliveryModel;
alter table   DeliveryModel auto_increment=1;
delete from Status;
alter table   Status auto_increment=1;
delete from DeliveryType;
alter table   DeliveryType auto_increment=1;
delete from SupportWindowMatrix;
alter table   SupportWindowMatrix auto_increment=1;
delete from InputVolumetricsDefinedBy;
alter table   InputVolumetricsDefinedBy auto_increment=1;
delete from TouchPointChannel;
alter table   TouchPointChannel auto_increment=1;
delete from VolumetricSolutionDefault;
alter table   VolumetricSolutionDefault auto_increment=1;
delete from ServiceScope;
alter table   ServiceScope auto_increment=1;
delete from UserApplicationRole;
truncate UserApplicationRole;
truncate User;
delete from ApplicationRole; 
alter table ApplicationRole auto_increment=1;
truncate ExchangeRate;