package com.ericsson.mssp.common.entity;

// Generated Mar 13, 2013 9:00:05 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Apacomplexity generated by hbm2java
 */
@Entity
@Table(name = "APAComplexity")
public class Apacomplexity implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = -8794591243698329102L;
    private Integer apacomplexityId;
    private Solution solution;
    private DealCharacteristics dealCharacteristics;
    private OpportunityScope opportunityScope;
    private Short complexityAssessed;
    private Short complexityOverride;
    private Float ftepercentage;
    private Float adjustedFte;
    private Float adjustedHrs;

    public Apacomplexity() {
    }

    public Apacomplexity(Solution solution, OpportunityScope opportunityScope) {
	this.solution = solution;
	this.opportunityScope = opportunityScope;
    }

    public Apacomplexity(Solution solution,
	    DealCharacteristics dealCharacteristics,
	    OpportunityScope opportunityScope, Short complexityAssessed,
	    Short complexityOverride, Float ftepercentage, Float adjustedFte,
	    Float adjustedHrs) {
	this.solution = solution;
	this.dealCharacteristics = dealCharacteristics;
	this.opportunityScope = opportunityScope;
	this.complexityAssessed = complexityAssessed;
	this.complexityOverride = complexityOverride;
	this.ftepercentage = ftepercentage;
	this.adjustedFte = adjustedFte;
	this.adjustedHrs = adjustedHrs;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "APAComplexityID", unique = true, nullable = false)
    public Integer getApacomplexityId() {
	return this.apacomplexityId;
    }

    public void setApacomplexityId(Integer apacomplexityId) {
	this.apacomplexityId = apacomplexityId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "SolutionID", nullable = false)
    public Solution getSolution() {
	return this.solution;
    }

    public void setSolution(Solution solution) {
	this.solution = solution;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "DealCharacteristicsID")
    public DealCharacteristics getDealCharacteristics() {
	return this.dealCharacteristics;
    }

    public void setDealCharacteristics(DealCharacteristics dealCharacteristics) {
	this.dealCharacteristics = dealCharacteristics;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "OpportunityScopeID", nullable = false)
    public OpportunityScope getOpportunityScope() {
	return this.opportunityScope;
    }

    public void setOpportunityScope(OpportunityScope opportunityScope) {
	this.opportunityScope = opportunityScope;
    }

    @Column(name = "ComplexityAssessed")
    public Short getComplexityAssessed() {
	return this.complexityAssessed;
    }

    public void setComplexityAssessed(Short complexityAssessed) {
	this.complexityAssessed = complexityAssessed;
    }

    @Column(name = "ComplexityOverride")
    public Short getComplexityOverride() {
	return this.complexityOverride;
    }

    public void setComplexityOverride(Short complexityOverride) {
	this.complexityOverride = complexityOverride;
    }

    @Column(name = "FTEPercentage", precision = 10)
    public Float getFtepercentage() {
	return this.ftepercentage;
    }

    public void setFtepercentage(Float ftepercentage) {
	this.ftepercentage = ftepercentage;
    }

    @Column(name = "AdjustedFTE", precision = 10)
    public Float getAdjustedFte() {
	return this.adjustedFte;
    }

    public void setAdjustedFte(Float adjustedFte) {
	this.adjustedFte = adjustedFte;
    }

    @Column(name = "AdjustedHrs", precision = 10)
    public Float getAdjustedHrs() {
	return this.adjustedHrs;
    }

    public void setAdjustedHrs(Float adjustedHrs) {
	this.adjustedHrs = adjustedHrs;
    }

}
