package com.ericsson.mssp.common.entity;
// Generated Dec 11, 2012 4:20:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.ManyToMany;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ApplicationRole generated by hbm2java
 */
@Entity
@Table(name = "ApplicationRole")
public class ApplicationRole implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7434209688667066245L;
	private Integer applicationRoleId;
	private String roleName;
	private String displayName;
	private Set<User> users = new HashSet<User>(0);

	public ApplicationRole() {
	}

	public ApplicationRole(String roleName, Set<User> users) {
		this.roleName = roleName;
		this.users = users;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ApplicationRoleID", unique = true, nullable = false)
	public Integer getApplicationRoleId() {
		return this.applicationRoleId;
	}

	public void setApplicationRoleId(Integer applicationRoleId) {
		this.applicationRoleId = applicationRoleId;
	}

	@Column(name = "RoleName", length = 20)
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "applicationRoles")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

	public String getDisplayName() {
		return displayName;
	}

	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}

}
