package com.ericsson.mssp.common.entity;

//Generated May 07, 2014 11:53:09 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
* ChangeManagement generated by hbm2java
*/
@Entity
@Table(name = "ChangeManagement")
@NamedQueries({
	@NamedQuery(
	name = "get.changeManagement.bySolutionID",
	query = "from ChangeManagement where SolutionId = ?"
	)
})
public class ChangeManagement implements java.io.Serializable {

/**
* 
*/
private static final long serialVersionUID = -7676448561170657940L;
private Integer changeManagementID;
private Solution solution;
private OpportunityScope opportunityScope;
private float reqGatheringAndAnalysis;
private float feasibilityImpactAndCostAnalysis;
private float approveChangesAndPlanning;
private float ensureStandards;
private float manageTraceability;
private float totalChangeManagementHours;


@Id
@GeneratedValue(strategy = IDENTITY)
@Column(name = "ChangeManagementID", unique = true, nullable = false)
public Integer getChangeManagementID() {
	return this.changeManagementID;
}

public void setChangeManagementID(Integer changeManagementID) {
	this.changeManagementID = changeManagementID;
}

@ManyToOne(fetch = FetchType.LAZY)
@JoinColumn(name = "SolutionID", nullable = false)
public Solution getSolution() {
	return this.solution;
}

public void setSolution(Solution solution) {
	this.solution = solution;
}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OpportunityScopeID")
	public OpportunityScope getOpportunityScope() {
		return opportunityScope;
	}

	/**
	 * @param opportunityScope the opportunityScope to set
	 */
	public void setOpportunityScope(OpportunityScope opportunityScope) {
		this.opportunityScope = opportunityScope;
	}

	@Column(name="ReqGatheringAndAnalysis")
	public float getReqGatheringAndAnalysis() {
		return reqGatheringAndAnalysis;
	}

	public void setReqGatheringAndAnalysis(float reqGatheringAndAnalysis) {
		this.reqGatheringAndAnalysis = reqGatheringAndAnalysis;
	}

	@Column(name="FeasibilityImpactAndCostAnalysis")
	public float getFeasibilityImpactAndCostAnalysis() {
		return feasibilityImpactAndCostAnalysis;
	}

	public void setFeasibilityImpactAndCostAnalysis(
			float feasibilityImpactAndCostAnalysis) {
		this.feasibilityImpactAndCostAnalysis = feasibilityImpactAndCostAnalysis;
	}

	@Column(name="ApproveChangesAndPlanning")
	public float getApproveChangesAndPlanning() {
		return approveChangesAndPlanning;
	}

	public void setApproveChangesAndPlanning(float approveChangesAndPlanning) {
		this.approveChangesAndPlanning = approveChangesAndPlanning;
	}

	@Column(name="EnsureStandards")
	public float getEnsureStandards() {
		return ensureStandards;
	}

	public void setEnsureStandards(float ensureStandards) {
		this.ensureStandards = ensureStandards;
	}

	@Column(name="ManageTraceability")
	public float getManageTraceability() {
		return manageTraceability;
	}

	public void setManageTraceability(float manageTraceability) {
		this.manageTraceability = manageTraceability;
	}

	@Column(name="TotalChangeManagementHours")
	public float getTotalChangeManagementHours() {
		return totalChangeManagementHours;
	}

	public void setTotalChangeManagementHours(float totalChangeManagementHours) {
		this.totalChangeManagementHours = totalChangeManagementHours;
	}	
	
	
}

