package com.ericsson.mssp.common.entity;

// Generated Mar 13, 2013 11:44:56 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CheckListMaster generated by hbm2java
 */
@Entity
@Table(name = "CheckListMaster")
public class CheckListMaster implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 8698920760808988495L;
    private Integer checkListMasterId;
    private String checkListName;
    private String checkListType;
    private String checkListSubType;
    private String checkListDescription;
    private Set<CheckLists> checkListses = new HashSet<CheckLists>(0);

    public CheckListMaster() {
    }

    public CheckListMaster(String checkListName, String checkListType,
	    String checkListSubType, String checkListDescription,
	    Set<CheckLists> checkListses) {
	this.checkListName = checkListName;
	this.checkListType = checkListType;
	this.checkListSubType = checkListSubType;
	this.checkListDescription = checkListDescription;
	this.checkListses = checkListses;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "CheckListMasterID", unique = true, nullable = false)
    public Integer getCheckListMasterId() {
	return this.checkListMasterId;
    }

    public void setCheckListMasterId(Integer checkListMasterId) {
	this.checkListMasterId = checkListMasterId;
    }

    @Column(name = "CheckListName", length = 20)
    public String getCheckListName() {
	return this.checkListName;
    }

    public void setCheckListName(String checkListName) {
	this.checkListName = checkListName;
    }

    @Column(name = "CheckListType", length = 12)
    public String getCheckListType() {
	return this.checkListType;
    }

    public void setCheckListType(String checkListType) {
	this.checkListType = checkListType;
    }

    @Column(name = "CheckListSubType", length = 20)
    public String getCheckListSubType() {
	return this.checkListSubType;
    }

    public void setCheckListSubType(String checkListSubType) {
	this.checkListSubType = checkListSubType;
    }

    @Column(name = "CheckListDescription", length = 100)
    public String getCheckListDescription() {
	return this.checkListDescription;
    }

    public void setCheckListDescription(String checkListDescription) {
	this.checkListDescription = checkListDescription;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "checkListMaster")
    public Set<CheckLists> getCheckListses() {
	return this.checkListses;
    }

    public void setCheckListses(Set<CheckLists> checkListses) {
	this.checkListses = checkListses;
    }

}
