package com.ericsson.mssp.common.entity;

// Generated Mar 13, 2013 11:44:56 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CheckLists generated by hbm2java
 */
@Entity
@Table(name = "CheckLists")
public class CheckLists implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = -6200745194347128248L;
    private Integer checkListsId;
    private Solution solution;
    private CheckListMaster checkListMaster;
    private Integer checkListValue;

    public CheckLists() {
    }

    public CheckLists(Solution solution, CheckListMaster checkListMaster,
	    Integer checkListValue) {
	this.solution = solution;
	this.checkListMaster = checkListMaster;
	this.checkListValue = checkListValue;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "CheckListsID", unique = true, nullable = false)
    public Integer getCheckListsId() {
	return this.checkListsId;
    }

    public void setCheckListsId(Integer checkListsId) {
	this.checkListsId = checkListsId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "SolutionID")
    public Solution getSolution() {
	return this.solution;
    }

    public void setSolution(Solution solution) {
	this.solution = solution;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "CheckListMasterID")
    public CheckListMaster getCheckListMaster() {
	return this.checkListMaster;
    }

    public void setCheckListMaster(CheckListMaster checkListMaster) {
	this.checkListMaster = checkListMaster;
    }

    @Column(name = "CheckListValue")
    public Integer getCheckListValue() {
	return this.checkListValue;
    }

    public void setCheckListValue(Integer checkListValue) {
	this.checkListValue = checkListValue;
    }

}
