package com.ericsson.mssp.common.entity;

//Generated May 22, 2014 11:53:09 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
* ConfigurationManagement generated by hbm2java
*/
@Entity
@Table(name = "ConfigurationManagement")
@NamedQueries({
	@NamedQuery(
	name = "get.configurationManagement.bySolutionID",
	query = "from ConfigurationManagement where SolutionID = ?"
	)
})
public class ConfigurationManagement implements java.io.Serializable {

/**
* 
*/
private static final long serialVersionUID = -7676448561170657940L;
private Integer configurationManagementID;
private Solution solution;
private OpportunityScope opportunityScope;
private float manageConfigurationItems;
private float manageConfigInfoAndDocumentation;
private float fteConfigurationManagement;


@Id
@GeneratedValue(strategy = IDENTITY)
@Column(name = "ConfigurationManagementID", unique = true, nullable = false)
public Integer getConfigurationManagementID() {
	return this.configurationManagementID;
}

public void setConfigurationManagementID(Integer configurationManagementID) {
	this.configurationManagementID = configurationManagementID;
}

@ManyToOne(fetch = FetchType.LAZY)
@JoinColumn(name = "SolutionID", nullable = false)
public Solution getSolution() {
	return this.solution;
}

public void setSolution(Solution solution) {
	this.solution = solution;
}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OpportunityScopeID")
	public OpportunityScope getOpportunityScope() {
		return opportunityScope;
	}

	/**
	 * @param opportunityScope the opportunityScope to set
	 */
	public void setOpportunityScope(OpportunityScope opportunityScope) {
		this.opportunityScope = opportunityScope;
	}

	@Column(name="ManageConfigurationItems")
	public float getManageConfigurationItems() {
		return manageConfigurationItems;
	}

	public void setManageConfigurationItems(float manageConfigurationItems) {
		this.manageConfigurationItems = manageConfigurationItems;
	}

	@Column(name="ManageConfigInfoAndDocumentation")
	public float getManageConfigInfoAndDocumentation() {
		return manageConfigInfoAndDocumentation;
	}

	public void setManageConfigInfoAndDocumentation(
			float manageConfigInfoAndDocumentation) {
		this.manageConfigInfoAndDocumentation = manageConfigInfoAndDocumentation;
	}

	@Column(name="FteConfigurationManagement")
	public float getFteConfigurationManagement() {
		return fteConfigurationManagement;
	}

	public void setFteConfigurationManagement(float fteConfigurationManagement) {
		this.fteConfigurationManagement = fteConfigurationManagement;
	}

}


