package com.ericsson.mssp.common.entity;
// Generated Dec 11, 2012 4:20:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "Customer")
public class Customer implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4409283561911535643L;
	private Integer customerId;
	private Country country;
	private String customerName;
	private Set<Opportunity> opportunities = new HashSet<Opportunity>(0);

	public Customer() {
	}

	public Customer(Country country) {
		this.country = country;
	}

	public Customer(Country country, String customerName, Set<Opportunity> opportunities) {
		this.country = country;
		this.customerName = customerName;
		this.opportunities = opportunities;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "CustomerID", unique = true, nullable = false)
	public Integer getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CountryID", nullable = false)
	public Country getCountry() {
		return this.country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	@Column(name = "CustomerName", length = 100)
	public String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	@JoinColumn(name = "OpportunityID", insertable=false, updatable=false)
	public Set<Opportunity> getOpportunities() {
		return this.opportunities;
	}

	public void setOpportunities(Set<Opportunity> opportunities) {
		this.opportunities = opportunities;
	}

}
