package com.ericsson.mssp.common.entity;

// Generated Mar 13, 2013 12:22:02 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DealCharacteristics generated by hbm2java
 */
@Entity
@Table(name = "DealCharacteristics")
public class DealCharacteristics implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 6545783911850319578L;
    private Integer dealCharacteristicsId;
    private String dealCharacteristicsName;
    private Integer effort;
    private Integer cost;
    private Integer dealIdentifier;
    private Set<Apacomplexity> apacomplexities = new HashSet<Apacomplexity>(0);

    public DealCharacteristics() {
    }

    public DealCharacteristics(String dealCharacteristicsName, Integer effort,
	    Integer cost, Integer dealIdentifier,
	    Set<Apacomplexity> apacomplexities) {
	this.dealCharacteristicsName = dealCharacteristicsName;
	this.effort = effort;
	this.cost = cost;
	this.dealIdentifier = dealIdentifier;
	this.apacomplexities = apacomplexities;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "DealCharacteristicsID", unique = true, nullable = false)
    public Integer getDealCharacteristicsId() {
	return this.dealCharacteristicsId;
    }

    public void setDealCharacteristicsId(Integer dealCharacteristicsId) {
	this.dealCharacteristicsId = dealCharacteristicsId;
    }

    @Column(name = "DealCharacteristicsName", length = 50)
    public String getDealCharacteristicsName() {
	return this.dealCharacteristicsName;
    }

    public void setDealCharacteristicsName(String dealCharacteristicsName) {
	this.dealCharacteristicsName = dealCharacteristicsName;
    }

    @Column(name = "Effort")
    public Integer getEffort() {
	return this.effort;
    }

    public void setEffort(Integer effort) {
	this.effort = effort;
    }

    @Column(name = "Cost")
    public Integer getCost() {
	return this.cost;
    }

    public void setCost(Integer cost) {
	this.cost = cost;
    }

    @Column(name = "DealIdentifier")
    public Integer getDealIdentifier() {
	return this.dealIdentifier;
    }

    public void setDealIdentifier(Integer dealIdentifier) {
	this.dealIdentifier = dealIdentifier;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "dealCharacteristics")
    public Set<Apacomplexity> getApacomplexities() {
	return this.apacomplexities;
    }

    public void setApacomplexities(Set<Apacomplexity> apacomplexities) {
	this.apacomplexities = apacomplexities;
    }

}
