package com.ericsson.mssp.common.entity;

// Generated Mar 13, 2013 1:33:14 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DeliveryModel generated by hbm2java
 */
@Entity
@Table(name = "DeliveryModel")
public class DeliveryModel implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = -6297580640477803704L;
    private Integer deliveryModelId;
    private String name;
    private String description;
   

    public DeliveryModel() {
    }

    public DeliveryModel(String name, String description,
	    Set<OpportunityDetail> opportunityDetails) {
	this.name = name;
	this.description = description;
	}

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "DeliveryModelID", unique = true, nullable = false)
    public Integer getDeliveryModelId() {
	return this.deliveryModelId;
    }

    public void setDeliveryModelId(Integer deliveryModelId) {
	this.deliveryModelId = deliveryModelId;
    }

    @Column(name = "Name", length = 30)
    public String getName() {
	return this.name;
    }

    public void setName(String name) {
	this.name = name;
    }

    @Column(name = "Description", length = 50)
    public String getDescription() {
	return this.description;
    }

    public void setDescription(String description) {
	this.description = description;
    }
}
