package com.ericsson.mssp.common.entity;

// Generated Mar 13, 2013 1:33:14 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DeliveryType generated by hbm2java
 */
@Entity
@Table(name = "DeliveryType")
public class DeliveryType implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1878780698860082885L;
    private Integer deliveryTypeId;
    private String name;
    private String description;
   

    public DeliveryType() {
    }

    public DeliveryType(String name, String description,
	    Set<OpportunityDetail> opportunityDetails) {
	this.name = name;
	this.description = description;
	}

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "DeliveryTypeID", unique = true, nullable = false)
    public Integer getDeliveryTypeId() {
	return this.deliveryTypeId;
    }

    public void setDeliveryTypeId(Integer deliveryTypeId) {
	this.deliveryTypeId = deliveryTypeId;
    }

    @Column(name = "Name", length = 30)
    public String getName() {
	return this.name;
    }

    public void setName(String name) {
	this.name = name;
    }

    @Column(name = "Description", length = 50)
    public String getDescription() {
	return this.description;
    }

    public void setDescription(String description) {
	this.description = description;
    }
}
