package com.ericsson.mssp.common.entity;

// Generated Mar 12, 2013 8:53:41 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EfficiencyLever generated by hbm2java
 */
@Entity
@Table(name = "EfficiencyLever")
public class EfficiencyLever implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = -5021641231749916498L;
    private Integer efficiencyLeverId;
    private Solution solution;
    private String releaseType;
    private String testType;
    private Float avgNoTestCases;
    private Float pcautomationDesign;
    private Float testDesignReuse;
    private Float testExecutionCycles;
    private Float asistestExecutionCycles;

    public EfficiencyLever() {
    }

    public EfficiencyLever(Solution solution, String releaseType,
	    String testType, Float avgNoTestCases, Float pcautomationDesign,
	    Float testDesignReuse, Float testExecutionCycles,
	    Float asistestExecutionCycles) {
	this.solution = solution;
	this.releaseType = releaseType;
	this.testType = testType;
	this.avgNoTestCases = avgNoTestCases;
	this.pcautomationDesign = pcautomationDesign;
	this.testDesignReuse = testDesignReuse;
	this.testExecutionCycles = testExecutionCycles;
	this.asistestExecutionCycles = asistestExecutionCycles;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "EfficiencyLeverID", unique = true, nullable = false)
    public Integer getEfficiencyLeverId() {
	return this.efficiencyLeverId;
    }

    public void setEfficiencyLeverId(Integer efficiencyLeverId) {
	this.efficiencyLeverId = efficiencyLeverId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "SolutionID")
    public Solution getSolution() {
	return this.solution;
    }

    public void setSolution(Solution solution) {
	this.solution = solution;
    }

    @Column(name = "ReleaseType", length = 10)
    public String getReleaseType() {
	return this.releaseType;
    }

    public void setReleaseType(String releaseType) {
	this.releaseType = releaseType;
    }

    @Column(name = "TestType", length = 20)
    public String getTestType() {
	return this.testType;
    }

    public void setTestType(String testType) {
	this.testType = testType;
    }

    @Column(name = "AvgNoTestCases", precision = 10)
    public Float getAvgNoTestCases() {
	return this.avgNoTestCases;
    }

    public void setAvgNoTestCases(Float avgNoTestCases) {
	this.avgNoTestCases = avgNoTestCases;
    }

    @Column(name = "PCAutomationDesign", precision = 10)
    public Float getPcautomationDesign() {
	return this.pcautomationDesign;
    }

    public void setPcautomationDesign(Float pcautomationDesign) {
	this.pcautomationDesign = pcautomationDesign;
    }

    @Column(name = "TestDesignReuse", precision = 10)
    public Float getTestDesignReuse() {
	return this.testDesignReuse;
    }

    public void setTestDesignReuse(Float testDesignReuse) {
	this.testDesignReuse = testDesignReuse;
    }

    @Column(name = "TestExecutionCycles", precision = 10)
    public Float getTestExecutionCycles() {
	return this.testExecutionCycles;
    }

    public void setTestExecutionCycles(Float testExecutionCycles) {
	this.testExecutionCycles = testExecutionCycles;
    }

    @Column(name = "ASISTestExecutionCycles", precision = 10)
    public Float getAsistestExecutionCycles() {
	return this.asistestExecutionCycles;
    }

    public void setAsistestExecutionCycles(Float asistestExecutionCycles) {
	this.asistestExecutionCycles = asistestExecutionCycles;
    }

}
