package com.ericsson.mssp.common.entity;

// Generated Apr 3, 2013 3:37:08 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ExchangeRate generated by hbm2java
 */
@Entity
@Table(name = "ExchangeRate")
public class ExchangeRate implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 3729456076703348377L;
    private Integer exchangeRateId;
    private Date startDate;
    private Date endDate;
    private Float dollarRs;
    private Float poundRs;
    private Float dollarPound;
    private Float poundDollar;
    private Float usd;
    private Float pound;
    private Date createdOn;

    public ExchangeRate() {
    }

    public ExchangeRate(Date startDate, Date endDate, Float dollarRs,Float poundRs, Float usd,
	    Float pound, Date createdOn, Float dollarPound, Float poundDollar) {
	this.startDate = startDate;
	this.endDate = endDate;
	this.dollarRs = dollarRs;
	this.poundRs = poundRs;
	this.usd = usd;
	this.pound = pound;
	this.createdOn = createdOn;
	this.dollarPound = dollarPound;
	this.poundDollar = poundDollar;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "ExchangeRateID", unique = true, nullable = false)
    public Integer getExchangeRateId() {
	return this.exchangeRateId;
    }

    public void setExchangeRateId(Integer exchangeRateId) {
	this.exchangeRateId = exchangeRateId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "StartDate", length = 19)
    public Date getStartDate() {
	return this.startDate;
    }

    public void setStartDate(Date startDate) {
	this.startDate = startDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "EndDate", length = 19)
    public Date getEndDate() {
	return this.endDate;
    }

    public void setEndDate(Date endDate) {
	this.endDate = endDate;
    }

    

    @Column(name = "USD", precision = 10)
    public Float getUsd() {
	return this.usd;
    }

    public void setUsd(Float usd) {
	this.usd = usd;
    }

    @Column(name = "Pound", precision = 10)
    public Float getPound() {
	return this.pound;
    }

    public void setPound(Float pound) {
	this.pound = pound;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "createdOn", length = 19)
    public Date getCreatedOn() {
	return this.createdOn;
    }

    public void setCreatedOn(Date createdOn) {
	this.createdOn = createdOn;
    }

    @Column(name="DollarRs", precision = 10)
	public Float getDollarRs() {
		return dollarRs;
	}

	public void setDollarRs(Float dollarRs) {
		this.dollarRs = dollarRs;
	}

	@Column(name="PoundRs", precision = 10)
	public Float getPoundRs() {
		return poundRs;
	}

	public void setPoundRs(Float poundRs) {
		this.poundRs = poundRs;
	}

	@Column(name="DollarPound" , precision = 10)
	public Float getDollarPound() {
		return dollarPound;
	}

	public void setDollarPound(Float dollarPound) {
		this.dollarPound = dollarPound;
	}

	@Column(name="PoundDollar", precision = 10)
	public Float getPoundDollar() {
		return poundDollar;
	}

	public void setPoundDollar(Float poundDollar) {
		this.poundDollar = poundDollar;
	}

}
