package com.ericsson.mssp.common.entity;
// Generated Dec 11, 2012 4:20:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * JobRole generated by hbm2java
 */
@Entity
@Table(name = "JobRole")
public class JobRole implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5792382226167006254L;
	private Integer jobRoleId;
	private String usedByFA;
	private String HRMSObject;
	private String role;
	private String jobRoleFamily;
	private String jobRoleFamilyNumber;
	private Integer CCMFlag;

	//private Set<RateCard> rateCards = new HashSet<RateCard>(0);
	private Set<StaffingPlan> staffingPlans = new HashSet<StaffingPlan>(0);

	public JobRole() {
	}

	public JobRole(String role, Set<StaffingPlan> staffingPlans,String usedByFA,String HRMSObject,String jobRoleFamily,String jobRoleFamilyNumber) {
		this.role = role;
		this.usedByFA = usedByFA;
		this.HRMSObject = HRMSObject;
		this.jobRoleFamily = jobRoleFamily;
		this.jobRoleFamilyNumber = jobRoleFamilyNumber;
		//this.rateCards = rateCards;
		this.staffingPlans = staffingPlans;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "JobRoleID", unique = true, nullable = false)
	public Integer getJobRoleId() {
		return this.jobRoleId;
	}

	public void setJobRoleId(Integer jobRoleId) {
		this.jobRoleId = jobRoleId;
	}

	@Column(name="UsedByFA", length=50)
	public String getUsedByFA() {
		return usedByFA;
	}

	public void setUsedByFA(String usedByFA) {
		this.usedByFA = usedByFA;
	}

	@Column(name="HRMSObject", length=100)
	public String getHRMSObject() {
		return HRMSObject;
	}

	public void setHRMSObject(String hRMSObject) {
		HRMSObject = hRMSObject;
	}

	@Column(name="RoleName", length=100)
	public String getRole() {
		return role;
	}

	public void setRole(String jobRole) {
		this.role = jobRole;
	}

	@Column(name="JobRoleFamily", length=100)
	public String getJobRoleFamily() {
		return jobRoleFamily;
	}

	public void setJobRoleFamily(String jobRoleFamily) {
		this.jobRoleFamily = jobRoleFamily;
	}

	@Column(name="JobRoleFamilyNumber", length=50)
	public String getJobRoleFamilyNumber() {
		return jobRoleFamilyNumber;
	}

	public void setJobRoleFamilyNumber(String jobRoleFamilyNumber) {
		this.jobRoleFamilyNumber = jobRoleFamilyNumber;
	}

	@Column(name="CCMFlag")
	public Integer getCCMFlag() {
		return CCMFlag;
	}

	public void setCCMFlag(Integer cCMFlag) {
		CCMFlag = cCMFlag;
	}


	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "jobRole")
	public Set<RateCard> getRateCards() {
		return this.rateCards;
	}

	public void setRateCards(Set<RateCard> rateCards) {
		this.rateCards = rateCards;
	}*/

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jobRole")
	public Set<StaffingPlan> getStaffingPlans() {
		return this.staffingPlans;
	}

	public void setStaffingPlans(Set<StaffingPlan> staffingPlans) {
		this.staffingPlans = staffingPlans;
	}

}
