package com.ericsson.mssp.common.entity;
// Generated Dec 11, 2012 4:20:07 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * LocationPyramid generated by hbm2java
 */
@Entity
@Table(name = "LocationPyramid")
public class LocationPyramid implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -307061317483583995L;
	private Integer locationPyramidId;
	private SolutionLever solutionLever;
	private OpportunityScope opportunityScope;
	private JobRoleStages jobRoleStages;
	private String location;
	private Float distributionPc;
	private Float ftecount;
	private Date monthYear;
	private String subLocation;
	
	public LocationPyramid() {
	}
	@Column(name = "MonthYear")
	public Date getMonthYear() {
	    return monthYear;
	}

	public void setMonthYear(Date monthYear) {
	    this.monthYear = monthYear;
	}


	public LocationPyramid(SolutionLever solutionLever,
			OpportunityScope opportunityScope, JobRoleStages jobRoleStages,
			String location, Float distributionPc, Float ftecount, Date monthYear) {
		this.solutionLever = solutionLever;
		this.opportunityScope = opportunityScope;
		this.jobRoleStages = jobRoleStages;
		this.location = location;
		this.distributionPc = distributionPc;
		this.ftecount = ftecount;
		this.monthYear = monthYear;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "LocationPyramidID", unique = true, nullable = false)
	public Integer getLocationPyramidId() {
		return this.locationPyramidId;
	}

	public void setLocationPyramidId(Integer locationPyramidId) {
		this.locationPyramidId = locationPyramidId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SolutionLeverID", nullable = false)
	public SolutionLever getSolutionLever() {
		return this.solutionLever;
	}

	public void setSolutionLever(SolutionLever solutionLever) {
		this.solutionLever = solutionLever;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OpportunityScopeID", nullable = false)
	public OpportunityScope getOpportunityScope() {
		return this.opportunityScope;
	}

	public void setOpportunityScope(OpportunityScope opportunityScope) {
		this.opportunityScope = opportunityScope;
	}

	

	@Column(name = "Location", length = 20)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "DistributionPC", precision = 10)
	public Float getDistributionPc() {
		return this.distributionPc;
	}

	public void setDistributionPc(Float distributionPc) {
		this.distributionPc = distributionPc;
	}

	@Column(name = "FTECount", precision = 10)
	public Float getFtecount() {
		return this.ftecount;
	}

	public void setFtecount(Float ftecount) {
		this.ftecount = ftecount;
	}
	@Column(name = "SubLocation", length = 20)
	public String getSubLocation() {
		return subLocation;
	}
	public void setSubLocation(String subLocation) {
		this.subLocation = subLocation;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "JobRoleStageID", nullable = false)
	public JobRoleStages getJobRoleStages() {
		return jobRoleStages;
	}
	public void setJobRoleStages(JobRoleStages jobRoleStages) {
		this.jobRoleStages = jobRoleStages;
	}

}
