package com.ericsson.mssp.common.entity;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * LocationBreakup generated by hbm2java
 */
@Entity
@Table(name = "LocationBreakup")
public class LocationBreakup implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3121463868837292850L;
	private Integer locationBreakupId;
	private SolutionLever solutionLever;
	private OpportunityScope opportunityScope;
	private Float onshorePc;
	private Float offshorePc;
	private Float onshoreFte;
	private Float offshoreFte;
	private Float onshoreLocalPc;
	private Float onshoreGSCiPc;
	private Float onshore3PPPc;
	private Float onshoreLocalFte;
	private Float onshoreGSCiFte;
	private Float onshore3PPFte;
	private Float nearshorePc;
	private Float nearshoreFte;
	private Date monthYear;

	public LocationBreakup() {
	}

	@Column(name = "MonthYear")
	public Date getMonthYear() {
	    return monthYear;
	}

	public void setMonthYear(Date monthYear) {
	    this.monthYear = monthYear;
	}

	public LocationBreakup(SolutionLever solutionLever,
			OpportunityScope opportunityScope) {
		this.solutionLever = solutionLever;
		this.opportunityScope = opportunityScope;
	}

	public LocationBreakup(SolutionLever solutionLever,
			OpportunityScope opportunityScope, Float onshorePc,
			Float offshorePc, Float onshoreFte, Float offshoreFte, Date monthYear) {
		this.solutionLever = solutionLever;
		this.opportunityScope = opportunityScope;
		this.onshorePc = onshorePc;
		this.offshorePc = offshorePc;
		this.onshoreFte = onshoreFte;
		this.offshoreFte = offshoreFte;
		this.monthYear = monthYear;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "LocationBreakupID", unique = true, nullable = false)
	public Integer getLocationBreakupId() {
		return this.locationBreakupId;
	}

	public void setLocationBreakupId(Integer locationBreakupId) {
		this.locationBreakupId = locationBreakupId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SolutionLeverID", nullable = false)
	public SolutionLever getSolutionLever() {
		return this.solutionLever;
	}

	public void setSolutionLever(SolutionLever solutionLever) {
		this.solutionLever = solutionLever;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OpportunityScopeID", nullable = false)
	public OpportunityScope getOpportunityScope() {
		return this.opportunityScope;
	}

	public void setOpportunityScope(OpportunityScope opportunityScope) {
		this.opportunityScope = opportunityScope;
	}

	@Column(name = "OnshorePC", precision = 10)
	public Float getOnshorePc() {
		return this.onshorePc;
	}

	public void setOnshorePc(Float onshorePc) {
		this.onshorePc = onshorePc;
	}

	@Column(name = "OffshorePC", precision = 10)
	public Float getOffshorePc() {
		return this.offshorePc;
	}

	public void setOffshorePc(Float offshorePc) {
		this.offshorePc = offshorePc;
	}

	@Column(name = "OnshoreFTE", precision = 10)
	public Float getOnshoreFte() {
		return this.onshoreFte;
	}

	public void setOnshoreFte(Float onshoreFte) {
		this.onshoreFte = onshoreFte;
	}

	@Column(name = "OffshoreFTE", precision = 10)
	public Float getOffshoreFte() {
		return this.offshoreFte;
	}

	public void setOffshoreFte(Float offshoreFte) {
		this.offshoreFte = offshoreFte;
	}
	
	@Column(name = "OnshoreLocalPC", precision = 10)
	public Float getOnshoreLocalPc() {
		return onshoreLocalPc;
	}

	public void setOnshoreLocalPc(Float onshoreLocalPc) {
		this.onshoreLocalPc = onshoreLocalPc;
	}
	
	@Column(name = "OnshoreGSCPC", precision = 10)
	public Float getOnshoreGSCiPc() {
		return onshoreGSCiPc;
	}

	public void setOnshoreGSCiPc(Float offshoreGSCiPc) {
		this.onshoreGSCiPc = offshoreGSCiPc;
	}
	
	@Column(name = "Onshore3PPPC", precision = 10)
	public Float getOnshore3PPPc() {
		return onshore3PPPc;
	}

	public void setOnshore3PPPc(Float onshore3ppPc) {
		onshore3PPPc = onshore3ppPc;
	}
	
	@Column(name = "OnshoreLocalFTE", precision = 10)
	public Float getOnshoreLocalFte() {
		return onshoreLocalFte;
	}

	public void setOnshoreLocalFte(Float onshoreLocalFte) {
		this.onshoreLocalFte = onshoreLocalFte;
	}
	
	@Column(name = "OnshoreGSCFTE", precision = 10)
	public Float getOnshoreGSCiFte() {
		return onshoreGSCiFte;
	}

	public void setOnshoreGSCiFte(Float offshoreGSCiFte) {
		this.onshoreGSCiFte = offshoreGSCiFte;
	}
	
	@Column(name = "Onshore3PPFTE", precision = 10)
	public Float getOnshore3PPFte() {
		return onshore3PPFte;
	}

	public void setOnshore3PPFte(Float onshore3ppFte) {
		onshore3PPFte = onshore3ppFte;
	}
	
	@Column(name = "NearShorePC", precision = 10)
	public Float getNearshorePc() {
		return nearshorePc;
	}

	public void setNearshorePc(Float nearshorePc) {
		this.nearshorePc = nearshorePc;
	}

	@Column(name = "NearShoreFTE", precision = 10)
	public Float getNearshoreFte() {
		return nearshoreFte;
	}

	public void setNearshoreFte(Float nearshoreFte) {
		this.nearshoreFte = nearshoreFte;
	}

}
