package com.ericsson.mssp.common.entity;

// Generated Mar 13, 2013 1:33:14 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * OpportunitySource generated by hbm2java
 */
@Entity
@Table(name = "OpportunitySource")
public class OpportunitySource implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = -7629306641316668305L;
    private Integer opportunitySourceId;
    private String name;
    private String description;
    private Integer orderId;
    
    public OpportunitySource() {
    }

    public OpportunitySource(String name, String description, Integer orderId,
	    Set<Opportunity> opportunities) {
	this.name = name;
	this.description = description;
	this.orderId = orderId;
	}

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "OpportunitySourceID", unique = true, nullable = false)
    public Integer getOpportunitySourceId() {
	return this.opportunitySourceId;
    }

    public void setOpportunitySourceId(Integer opportunitySourceId) {
	this.opportunitySourceId = opportunitySourceId;
    }

    @Column(name = "Name", length = 30)
    public String getName() {
	return this.name;
    }

    public void setName(String name) {
	this.name = name;
    }

    @Column(name = "Description", length = 50)
    public String getDescription() {
	return this.description;
    }

    public void setDescription(String description) {
	this.description = description;
    }

    @Column(name = "OrderID")
    public Integer getOrderId() {
	return this.orderId;
    }

    public void setOrderId(Integer orderId) {
	this.orderId = orderId;
    }

}
