package com.ericsson.mssp.common.entity;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Opportunity generated by hbm2java
 */
@Entity
@Table(name = "Opportunity")
public class Opportunity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8938354948474555843L;
	private Integer opportunityId;
	private Customer customer;
	private String opportunityName;
	private String createdBy;
	private OpportunityDetail opportunityDetail;
	private WorkflowTimeline workflowTimeline;
	private String assignedTo;
	private OpportunitySource opportunitySource;
	private CommercialModel commercialModel;
	
	
	private Set<OpportunityScope> opportunityScopes = new HashSet<OpportunityScope>(0);
	private Set<Solution> solutions = new HashSet<Solution>(0);

	public Opportunity() {
	}

	public Opportunity(Customer customer) {
		this.customer = customer;
	}

	public Opportunity(Customer customer, String opportunityName,
			Set<OpportunityScope> opportunityScopes, OpportunityDetail opportunityDetail,
			WorkflowTimeline workflowTimeline, Set<Solution> solutions) {
		this.customer = customer;
		this.opportunityName = opportunityName;
		this.opportunityScopes = opportunityScopes;
		this.opportunityDetail = opportunityDetail;
		this.workflowTimeline = workflowTimeline;
		this.solutions = solutions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "OpportunityID", unique = true, nullable = false)
	public Integer getOpportunityId() {
		return this.opportunityId;
	}

	public void setOpportunityId(Integer opportunityId) {
		this.opportunityId = opportunityId;
	}

	@ManyToOne(fetch = FetchType.EAGER, cascade=CascadeType.ALL)
	@JoinColumn(name = "CustomerID", referencedColumnName="CustomerID", nullable = false)
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@Column(name = "OpportunityName", length = 100)
	public String getOpportunityName() {
		return this.opportunityName;
	}

	public void setOpportunityName(String opportunityName) {
		this.opportunityName = opportunityName;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "opportunity")
	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "opportunity")*/
	public Set<OpportunityScope> getOpportunityScopes() {
		return this.opportunityScopes;
	}

	public void setOpportunityScopes(Set<OpportunityScope> opportunityScopes) {
		this.opportunityScopes = opportunityScopes;
	}

	

	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "opportunity")
	public Set<Solution> getSolutions() {
		return this.solutions;
	}

	public void setSolutions(Set<Solution> solutions) {
		this.solutions = solutions;
	}

	/*@OneToOne(fetch = FetchType.EAGER)*/
	@OneToOne(fetch = FetchType.LAZY, mappedBy = "opportunity" , cascade = CascadeType.ALL)
	@JoinColumn(name = "OpportunityDetailID", nullable = true)
	public OpportunityDetail getOpportunityDetail() {
		return opportunityDetail;
	}
	
	public void setOpportunityDetail(OpportunityDetail opportunityDetail) {
		this.opportunityDetail = opportunityDetail;
	}
	
	@OneToOne(fetch = FetchType.LAZY, mappedBy = "opportunity" , cascade = CascadeType.ALL)
	@JoinColumn(name = "WorkflowTimelineID" , nullable = true)
	public WorkflowTimeline getWorkflowTimeline() {
		return workflowTimeline;
	}

	public void setWorkflowTimeline(WorkflowTimeline workflowTimeline) {
		this.workflowTimeline = workflowTimeline;
	}

	@Column(name="CreatedBy", length=10)
	public String getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name="AssignedTo", length=7)
	public String getAssignedTo() {
		return assignedTo;
	}

	public void setAssignedTo(String assignedTo) {
		this.assignedTo = assignedTo;
	}

	@OneToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "OpportunitySourceID", nullable = true)
	public OpportunitySource getOpportunitySource() {
		return opportunitySource;
	}

	public void setOpportunitySource(OpportunitySource opportunitySource) {
		this.opportunitySource = opportunitySource;
	}

	@OneToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CommercialModelID", nullable = true)
	public CommercialModel getCommercialModel() {
		return commercialModel;
	}

	public void setCommercialModel(CommercialModel commercialModel) {
		this.commercialModel = commercialModel;
	}
	


}
