package com.ericsson.mssp.common.entity;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProductivityLever generated by hbm2java
 */
@Entity
@Table(name = "ProductivityLever")
public class ProductivityLever implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4066830027008151894L;
	private Integer productivityLeverId;
	private SolutionLever solutionLever;
	private OpportunityScope opportunityScope;
	private Date monthYear;
//	private Float orgStructure;
//	private Float process;
//	private Float serviceManagement;
//	private Float teamSourcing;
//	private Float portfolioOptimization;
//	private Float computedProductivity;
	
	private Float productivityPC;
	
	private Float calculatedFte;

	public ProductivityLever() {
	}

	public ProductivityLever(SolutionLever solutionLever,
			OpportunityScope opportunityScope) {
		this.solutionLever = solutionLever;
		this.opportunityScope = opportunityScope;
	}

	public ProductivityLever(SolutionLever solutionLever,
			OpportunityScope opportunityScope, Date monthYear,
			Float orgStructure, Float process, Float serviceManagement,
			Float teamSourcing, Float portfolioOptimization,
			Float computedProductivity, Float calculatedFte) {
		this.solutionLever = solutionLever;
		this.opportunityScope = opportunityScope;
		this.monthYear = monthYear;
		/*this.orgStructure = orgStructure;
		this.process = process;
		this.serviceManagement = serviceManagement;
		this.teamSourcing = teamSourcing;
		this.portfolioOptimization = portfolioOptimization;
		this.computedProductivity = computedProductivity;*/
		this.calculatedFte = calculatedFte;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ProductivityLeverID", unique = true, nullable = false)
	public Integer getProductivityLeverId() {
		return this.productivityLeverId;
	}

	public void setProductivityLeverId(Integer productivityLeverId) {
		this.productivityLeverId = productivityLeverId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SolutionLeverID", nullable = false)
	public SolutionLever getSolutionLever() {
		return this.solutionLever;
	}

	public void setSolutionLever(SolutionLever solutionLever) {
		this.solutionLever = solutionLever;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "OpportunityScopeID", nullable = false)
	public OpportunityScope getOpportunityScope() {
		return this.opportunityScope;
	}

	public void setOpportunityScope(OpportunityScope opportunityScope) {
		this.opportunityScope = opportunityScope;
	}

	@Column(name = "MonthYear")
	public Date getMonthYear() {
		return this.monthYear;
	}

	public void setMonthYear(Date monthYear) {
		this.monthYear = monthYear;
	}

/*	@Column(name = "OrgStructure")
	public Float getOrgStructure() {
		return this.orgStructure;
	}

	public void setOrgStructure(Float orgStructure) {
		this.orgStructure = orgStructure;
	}

	@Column(name = "Process")
	public Float getProcess() {
		return this.process;
	}

	public void setProcess(Float process) {
		this.process = process;
	}

	@Column(name = "ServiceManagement")
	public Float getServiceManagement() {
		return this.serviceManagement;
	}

	public void setServiceManagement(Float serviceManagement) {
		this.serviceManagement = serviceManagement;
	}

	@Column(name = "TeamSourcing")
	public Float getTeamSourcing() {
		return this.teamSourcing;
	}

	public void setTeamSourcing(Float teamSourcing) {
		this.teamSourcing = teamSourcing;
	}

	@Column(name = "PortfolioOptimization")
	public Float getPortfolioOptimization() {
		return this.portfolioOptimization;
	}

	public void setPortfolioOptimization(Float portfolioOptimization) {
		this.portfolioOptimization = portfolioOptimization;
	}

	@Column(name = "ComputedProductivity", precision = 10)
	public Float getComputedProductivity() {
		return this.computedProductivity;
	}

	public void setComputedProductivity(Float computedProductivity) {
		this.computedProductivity = computedProductivity;
	}
*/
	@Column(name = "CalculatedFTE", precision = 10)
	public Float getCalculatedFte() {
		return this.calculatedFte;
	}

	public void setCalculatedFte(Float calculatedFte) {
		this.calculatedFte = calculatedFte;
	}

	@Column(name = "ProductivityPC", precision = 10)
	public Float getProductivityPC() {
		return productivityPC;
	}

	public void setProductivityPC(Float productivityPC) {
		this.productivityPC = productivityPC;
	}

}
