package com.ericsson.mssp.common.entity;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RateCard generated by hbm2java
 */
@Entity
@Table(name = "RateCard")
public class RateCard implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6895894001339863033L;
	
	private Double 			rate;
	private Country 		country;
	private String 			location;
	private String 			createdBy;
	private String 			updatedBy;
	private Integer 		rateCardId;
	private Date 			createdTimestamp;
	private Date 			updatedTimestamp;
	private JobRoleStages 	jobRoleStages;
	private String 			gsc;
	private String 			subLocation;
	private String			statusFlag;
	
	

	public RateCard() {
	}

	
	public RateCard(String location, Double rate,
			String createdBy, Date createdTimestamp, String updatedBy,
			Date updatedTimestamp,String gsc,String subLocation) {
		this.location = location;
		this.rate = rate;
		this.createdBy = createdBy;
		this.createdTimestamp = createdTimestamp;
		this.updatedBy = updatedBy;
		this.updatedTimestamp = updatedTimestamp;
		this.gsc = gsc;
		this.subLocation = subLocation;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "RateCardID", unique = true, nullable = false)
	public Integer getRateCardId() {
		return this.rateCardId;
	}

	public void setRateCardId(Integer rateCardId) {
		this.rateCardId = rateCardId;
	}

	@OneToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "JobRoleStageID", nullable = false)
	public JobRoleStages getJobRoleStages() {
		return jobRoleStages;
	}

	public void setJobRoleStages(JobRoleStages jobRoleStages) {
		this.jobRoleStages = jobRoleStages;
	}
	
	/*@ManyToOne(fetch = FetchType.LAZY)
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "JobRoleID", nullable = false)
	public JobRole getJobRole() {
		return this.jobRole;
	}

	public void setJobRole(JobRole jobRole) {
		this.jobRole = jobRole;
	}
*/
	@Column(name = "Location", length = 50)
	public String getLocation() {
		return this.location;
	}

	

	@OneToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CountryID", nullable = false)
	public Country getCountry() {
		return country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "Rate", precision = 16, scale = 4)
	public Double getRate() {
		return this.rate;
	}

	public void setRate(Double rate) {
		this.rate = rate;
	}

	@Column(name = "CreatedBy", length = 50)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedTimestamp", length = 19)
	public Date getCreatedTimestamp() {
		return this.createdTimestamp;
	}

	public void setCreatedTimestamp(Date createdTimestamp) {
		this.createdTimestamp = createdTimestamp;
	}

	@Column(name = "UpdatedBy", length = 50)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UpdatedTimestamp", length = 19)
	public Date getUpdatedTimestamp() {
		return this.updatedTimestamp;
	}

	public void setUpdatedTimestamp(Date updatedTimestamp) {
		this.updatedTimestamp = updatedTimestamp;
	}

	@Column(name = "Gsc", length = 10)
	public String getGsc() {
		return gsc;
	}


	public void setGsc(String gsc) {
		this.gsc = gsc;
	}


	@Column(name = "SubLocation", length = 30)
	public String getSubLocation() {
		return subLocation;
	}


	public void setSubLocation(String subLocation) {
		this.subLocation = subLocation;
	}

	@Column(name = "StatusFlag", length = 1)
	public String getStatusFlag() {
		return statusFlag;
	}


	public void setStatusFlag(String statusFlag) {
		this.statusFlag = statusFlag;
	}

}
