package com.ericsson.mssp.common.entity;

import java.sql.Timestamp;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ServiceElement generated by hbm2java
 */
@Entity
@Table(name = "ServiceElement")
public class ServiceElement implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -330614778634165293L;
	private Integer serviceElementID;
	private String serviceFunctionName;
	private String serviceFunctionCode;
	private String serviceElementName;
	private String serviceElementDescription;
	private String serviceType;
	private String active;
	private String hasServiceScope;
	private String createdBy;
	private Timestamp createdTimestamp;
	private String updatedBy;
	private Timestamp updatedTimestamp;
	private Set<ServiceScope> serviceScopes = new HashSet<ServiceScope>(0);

	public ServiceElement() {
	}

	public ServiceElement(String serviceFunctionName, String serviceElementName,String serviceFunctionCode,
			String serviceElementDescription, String active, String hasServiceScope,
			String createdBy, Timestamp createdTimestamp, String updatedBy,
			Timestamp updatedTimestamp, Set<ServiceScope> serviceScopes) {
		this.serviceFunctionName = serviceFunctionName;
		this.serviceFunctionCode = serviceFunctionCode;
		this.serviceElementName = serviceElementName;
		this.serviceElementDescription = serviceElementDescription;
		this.active = active;
		this.hasServiceScope = hasServiceScope;
		this.createdBy = createdBy;
		this.createdTimestamp = createdTimestamp;
		this.updatedBy = updatedBy;
		this.updatedTimestamp = updatedTimestamp;
		this.serviceScopes = serviceScopes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ServiceElementID", unique = true, nullable = false)
	public Integer getServiceElementID() {
		return serviceElementID;
	}

	public void setServiceElementID(Integer serviceElementID) {
		this.serviceElementID = serviceElementID;
	}

	@Column(name = "ServiceFunctionName", length = 50)
	public String getServiceFunctionName() {
		return serviceFunctionName;
	}

	public void setServiceFunctionName(String serviceFunctionName) {
		this.serviceFunctionName = serviceFunctionName;
	}
	
	@Column(name= "ServiceFunctionCode", length = 50)
	public String getServiceFunctionCode() {
		return serviceFunctionCode;
	}

	public void setServiceFunctionCode(String serviceFunctionCode) {
		this.serviceFunctionCode = serviceFunctionCode;
	}

	@Column(name = "ServiceElementName", length = 50)
	public String getServiceElementName() {
		return serviceElementName;
	}

	public void setServiceElementName(String serviceElementName) {
		this.serviceElementName = serviceElementName;
	}

	@Column(name = "ServiceElementDescription", length = 500)
	public String getServiceElementDescription() {
		return serviceElementDescription;
	}

	public void setServiceElementDescription(String serviceElementDescription) {
		this.serviceElementDescription = serviceElementDescription;
	}

	@Column(name = "Active", length = 1)
	public String getActive() {
		return active;
	}

	public void setActive(String active) {
		this.active = active;
	}

	@Column(name = "HasServiceScope", length = 1)
	public String getHasServiceScope() {
		return hasServiceScope;
	}

	public void setHasServiceScope(String hasServiceScope) {
		this.hasServiceScope = hasServiceScope;
	}

	@Column(name = "CreatedBy", length = 50)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}
	
	@Column(name = "CreatedTimestamp", length = 19)
	public Timestamp getCreatedTimestamp() {
		return this.createdTimestamp;
	}

	public void setCreatedTimestamp(Timestamp createdTimestamp) {
		this.createdTimestamp = createdTimestamp;
	}

	@Column(name = "UpdatedBy", length = 50)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	
	@Column(name = "UpdatedTimestamp", length = 19)
	public Timestamp getUpdatedTimestamp() {
		return this.updatedTimestamp;
	}

	public void setUpdatedTimestamp(Timestamp updatedTimestamp) {
		this.updatedTimestamp = updatedTimestamp;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "serviceElement")
	public Set<ServiceScope> getServiceScopes() {
		return serviceScopes;
	}

	public void setServiceScopes(Set<ServiceScope> serviceScopes) {
		this.serviceScopes = serviceScopes;
	}

	/**
	 * @return the serviceType
	 */
	@Column(name = "ServiceType", length = 50)
	public String getServiceType() {
		return serviceType;
	}

	/**
	 * @param serviceType the serviceType to set
	 */
	public void setServiceType(String serviceType) {
		this.serviceType = serviceType;
	}

}
