package com.ericsson.mssp.common.entity;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SolutionApproachDimension generated by hbm2java
 */
@Entity
@Table(name = "SolutionApproachDimension")
public class SolutionApproachDimension implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2096261227216461782L;
	private Integer solutionApproachDimensionId;
	private Solution solution;
	private String dimensionName;
	private String dimensionAttributeName;
	

	public SolutionApproachDimension() {
	}

	public SolutionApproachDimension(Solution solution) {
		this.solution = solution;
	}

	public SolutionApproachDimension(Solution solution, String dimensionName,
			String dimensionAttributeName) {
		this.solution = solution;
		this.dimensionName = dimensionName;
		this.dimensionAttributeName = dimensionAttributeName;
		
	}

	@Id
	@GeneratedValue
	@Column(name = "SolutionApproachDimensionID", unique = true, nullable = false)
	public Integer getSolutionApproachDimensionId() {
		return this.solutionApproachDimensionId;
	}

	public void setSolutionApproachDimensionId(
			Integer solutionApproachDimensionId) {
		this.solutionApproachDimensionId = solutionApproachDimensionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SolutionID", insertable=false, updatable=false)
	public Solution getSolution() {
		return this.solution;
	}

	public void setSolution(Solution solution) {
		this.solution = solution;
	}

	@Column(name = "DimensionName", length = 50)
	public String getDimensionName() {
		return this.dimensionName;
	}

	public void setDimensionName(String dimensionName) {
		this.dimensionName = dimensionName;
	}

	@Column(name = "DimensionAttributeName", length = 50)
	public String getDimensionAttributeName() {
		return this.dimensionAttributeName;
	}

	public void setDimensionAttributeName(String dimensionAttributeName) {
		this.dimensionAttributeName = dimensionAttributeName;
	}



}
