package com.ericsson.mssp.common.entity;

// Generated Feb 7, 2013 11:35:07 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SolutionL3addServices generated by hbm2java
 */
@Entity
@Table(name = "SolutionL3AddServices")
public class SolutionL3addServices implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = -2077981490279388618L;
    private Integer solutionL3addServicesId;
    private Solution solution;
    private SolutionApproachDimension solutionApproachDimension;
    private String scopeIntegTest;
    private String scopeRegreTest;
    private String scopeOtherTest;
    private String scopeMisceSupp;
    private String scopePhysicalDatabase;
    private String scopeServerAndVirt;
    private String scopeOtherInfra;
    private String unitIntegTest;
    private String unitRegreTest;
    private String unitOtherTest;
    private String unitMisceSupp;
    private String unitPhysicalDatabase;
    private String unitServerAndVirt;
    private String unitOtherInfra;
    private Float valueIntegTest;
    private Float valueRegreTest;
    private Float valueOtherTest;
    private Float valueMisceSupp;
    private Float valuePhysicalDatabase;
    private Float valueServerAndVirt;
    private Float valueOtherInfra;
    private Float fteintegTest;
    private Float fteregreTest;
    private Float fteotherTest;
    private Float ftemisceSupp;
    private Float ftephysicalDatabase;
    private Float fteserverAndVirt;
    private Float fteotherInfra;
    private Float baseL3serviceFte;
    private Float augmentedL3serviceFte;
	private OpportunityScope opportunityScope;

    public SolutionL3addServices() {
    }

    public SolutionL3addServices(Solution solution,
	    SolutionApproachDimension solutionApproachDimension,
	    String scopeIntegTest, String scopeRegreTest,
	    String scopeOtherTest, String scopeMisceSupp,
	    String scopePhysicalDatabase, String scopeServerAndVirt,
	    String scopeOtherInfra, String unitIntegTest, String unitRegreTest,
	    String unitOtherTest, String unitMisceSupp,
	    String unitPhysicalDatabase, String unitServerAndVirt,
	    String unitOtherInfra, Float valueIntegTest, Float valueRegreTest,
	    Float valueOtherTest, Float valueMisceSupp,
	    Float valuePhysicalDatabase, Float valueServerAndVirt,
	    Float valueOtherInfra, Float fteintegTest, Float fteregreTest,
	    Float fteotherTest, Float ftemisceSupp, Float ftephysicalDatabase,
	    Float fteserverAndVirt, Float fteotherInfra,
	    Float baseL3serviceFte, Float augmentedL3serviceFte) {
	this.solution = solution;
	this.solutionApproachDimension = solutionApproachDimension;
	this.scopeIntegTest = scopeIntegTest;
	this.scopeRegreTest = scopeRegreTest;
	this.scopeOtherTest = scopeOtherTest;
	this.scopeMisceSupp = scopeMisceSupp;
	this.scopePhysicalDatabase = scopePhysicalDatabase;
	this.scopeServerAndVirt = scopeServerAndVirt;
	this.scopeOtherInfra = scopeOtherInfra;
	this.unitIntegTest = unitIntegTest;
	this.unitRegreTest = unitRegreTest;
	this.unitOtherTest = unitOtherTest;
	this.unitMisceSupp = unitMisceSupp;
	this.unitPhysicalDatabase = unitPhysicalDatabase;
	this.unitServerAndVirt = unitServerAndVirt;
	this.unitOtherInfra = unitOtherInfra;
	this.valueIntegTest = valueIntegTest;
	this.valueRegreTest = valueRegreTest;
	this.valueOtherTest = valueOtherTest;
	this.valueMisceSupp = valueMisceSupp;
	this.valuePhysicalDatabase = valuePhysicalDatabase;
	this.valueServerAndVirt = valueServerAndVirt;
	this.valueOtherInfra = valueOtherInfra;
	this.fteintegTest = fteintegTest;
	this.fteregreTest = fteregreTest;
	this.fteotherTest = fteotherTest;
	this.ftemisceSupp = ftemisceSupp;
	this.ftephysicalDatabase = ftephysicalDatabase;
	this.fteserverAndVirt = fteserverAndVirt;
	this.fteotherInfra = fteotherInfra;
	this.baseL3serviceFte = baseL3serviceFte;
	this.augmentedL3serviceFte = augmentedL3serviceFte;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "SolutionL3AddServicesID", unique = true, nullable = false)
    public Integer getSolutionL3addServicesId() {
	return this.solutionL3addServicesId;
    }

    public void setSolutionL3addServicesId(Integer solutionL3addServicesId) {
	this.solutionL3addServicesId = solutionL3addServicesId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "SolutionID")
    public Solution getSolution() {
	return this.solution;
    }

    public void setSolution(Solution solution) {
	this.solution = solution;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "SolutionApproachDimensionID")
    public SolutionApproachDimension getSolutionApproachDimension() {
	return this.solutionApproachDimension;
    }

    public void setSolutionApproachDimension(
	    SolutionApproachDimension solutionApproachDimension) {
	this.solutionApproachDimension = solutionApproachDimension;
    }

    @Column(name = "ScopeIntegTest", length = 3)
    public String getScopeIntegTest() {
	return this.scopeIntegTest;
    }

    public void setScopeIntegTest(String scopeIntegTest) {
	this.scopeIntegTest = scopeIntegTest;
    }

    @Column(name = "ScopeRegreTest", length = 3)
    public String getScopeRegreTest() {
	return this.scopeRegreTest;
    }

    public void setScopeRegreTest(String scopeRegreTest) {
	this.scopeRegreTest = scopeRegreTest;
    }

    @Column(name = "ScopeOtherTest", length = 3)
    public String getScopeOtherTest() {
	return this.scopeOtherTest;
    }

    public void setScopeOtherTest(String scopeOtherTest) {
	this.scopeOtherTest = scopeOtherTest;
    }

    @Column(name = "ScopeMisceSupp", length = 3)
    public String getScopeMisceSupp() {
	return this.scopeMisceSupp;
    }

    public void setScopeMisceSupp(String scopeMisceSupp) {
	this.scopeMisceSupp = scopeMisceSupp;
    }

    @Column(name = "ScopePhysicalDatabase", length = 3)
    public String getScopePhysicalDatabase() {
	return this.scopePhysicalDatabase;
    }

    public void setScopePhysicalDatabase(String scopePhysicalDatabase) {
	this.scopePhysicalDatabase = scopePhysicalDatabase;
    }

    @Column(name = "ScopeServerAndVirt", length = 3)
    public String getScopeServerAndVirt() {
	return this.scopeServerAndVirt;
    }

    public void setScopeServerAndVirt(String scopeServerAndVirt) {
	this.scopeServerAndVirt = scopeServerAndVirt;
    }

    @Column(name = "ScopeOtherInfra", length = 3)
    public String getScopeOtherInfra() {
	return this.scopeOtherInfra;
    }

    public void setScopeOtherInfra(String scopeOtherInfra) {
	this.scopeOtherInfra = scopeOtherInfra;
    }

    @Column(name = "UnitIntegTest", length = 20)
    public String getUnitIntegTest() {
	return this.unitIntegTest;
    }

    public void setUnitIntegTest(String unitIntegTest) {
	this.unitIntegTest = unitIntegTest;
    }

    @Column(name = "UnitRegreTest", length = 20)
    public String getUnitRegreTest() {
	return this.unitRegreTest;
    }

    public void setUnitRegreTest(String unitRegreTest) {
	this.unitRegreTest = unitRegreTest;
    }

    @Column(name = "UnitOtherTest", length = 20)
    public String getUnitOtherTest() {
	return this.unitOtherTest;
    }

    public void setUnitOtherTest(String unitOtherTest) {
	this.unitOtherTest = unitOtherTest;
    }

    @Column(name = "UnitMisceSupp", length = 20)
    public String getUnitMisceSupp() {
	return this.unitMisceSupp;
    }

    public void setUnitMisceSupp(String unitMisceSupp) {
	this.unitMisceSupp = unitMisceSupp;
    }

    @Column(name = "UnitPhysicalDatabase", length = 20)
    public String getUnitPhysicalDatabase() {
	return this.unitPhysicalDatabase;
    }

    public void setUnitPhysicalDatabase(String unitPhysicalDatabase) {
	this.unitPhysicalDatabase = unitPhysicalDatabase;
    }

    @Column(name = "UnitServerAndVirt", length = 20)
    public String getUnitServerAndVirt() {
	return this.unitServerAndVirt;
    }

    public void setUnitServerAndVirt(String unitServerAndVirt) {
	this.unitServerAndVirt = unitServerAndVirt;
    }

    @Column(name = "UnitOtherInfra", length = 20)
    public String getUnitOtherInfra() {
	return this.unitOtherInfra;
    }

    public void setUnitOtherInfra(String unitOtherInfra) {
	this.unitOtherInfra = unitOtherInfra;
    }

    @Column(name = "ValueIntegTest", precision = 10)
    public Float getValueIntegTest() {
	return this.valueIntegTest;
    }

    public void setValueIntegTest(Float valueIntegTest) {
	this.valueIntegTest = valueIntegTest;
    }

    @Column(name = "ValueRegreTest", precision = 10)
    public Float getValueRegreTest() {
	return this.valueRegreTest;
    }

    public void setValueRegreTest(Float valueRegreTest) {
	this.valueRegreTest = valueRegreTest;
    }

    @Column(name = "ValueOtherTest", precision = 10)
    public Float getValueOtherTest() {
	return this.valueOtherTest;
    }

    public void setValueOtherTest(Float valueOtherTest) {
	this.valueOtherTest = valueOtherTest;
    }

    @Column(name = "ValueMisceSupp", precision = 10)
    public Float getValueMisceSupp() {
	return this.valueMisceSupp;
    }

    public void setValueMisceSupp(Float valueMisceSupp) {
	this.valueMisceSupp = valueMisceSupp;
    }

    @Column(name = "ValuePhysicalDatabase", precision = 10)
    public Float getValuePhysicalDatabase() {
	return this.valuePhysicalDatabase;
    }

    public void setValuePhysicalDatabase(Float valuePhysicalDatabase) {
	this.valuePhysicalDatabase = valuePhysicalDatabase;
    }

    @Column(name = "ValueServerAndVirt", precision = 10)
    public Float getValueServerAndVirt() {
	return this.valueServerAndVirt;
    }

    public void setValueServerAndVirt(Float valueServerAndVirt) {
	this.valueServerAndVirt = valueServerAndVirt;
    }

    @Column(name = "ValueOtherInfra", precision = 10)
    public Float getValueOtherInfra() {
	return this.valueOtherInfra;
    }

    public void setValueOtherInfra(Float valueOtherInfra) {
	this.valueOtherInfra = valueOtherInfra;
    }

    @Column(name = "FTEIntegTest", precision = 10)
    public Float getFteintegTest() {
	return this.fteintegTest;
    }

    public void setFteintegTest(Float fteintegTest) {
	this.fteintegTest = fteintegTest;
    }

    @Column(name = "FTERegreTest", precision = 10)
    public Float getFteregreTest() {
	return this.fteregreTest;
    }

    public void setFteregreTest(Float fteregreTest) {
	this.fteregreTest = fteregreTest;
    }

    @Column(name = "FTEOtherTest", precision = 10)
    public Float getFteotherTest() {
	return this.fteotherTest;
    }

    public void setFteotherTest(Float fteotherTest) {
	this.fteotherTest = fteotherTest;
    }

    @Column(name = "FTEMisceSupp", precision = 10)
    public Float getFtemisceSupp() {
	return this.ftemisceSupp;
    }

    public void setFtemisceSupp(Float ftemisceSupp) {
	this.ftemisceSupp = ftemisceSupp;
    }

    @Column(name = "FTEPhysicalDatabase", precision = 10)
    public Float getFtephysicalDatabase() {
	return this.ftephysicalDatabase;
    }

    public void setFtephysicalDatabase(Float ftephysicalDatabase) {
	this.ftephysicalDatabase = ftephysicalDatabase;
    }

    @Column(name = "FTEServerAndVirt", precision = 10)
    public Float getFteserverAndVirt() {
	return this.fteserverAndVirt;
    }

    public void setFteserverAndVirt(Float fteserverAndVirt) {
	this.fteserverAndVirt = fteserverAndVirt;
    }

    @Column(name = "FTEOtherInfra", precision = 10)
    public Float getFteotherInfra() {
	return this.fteotherInfra;
    }

    public void setFteotherInfra(Float fteotherInfra) {
	this.fteotherInfra = fteotherInfra;
    }

    @Column(name = "BaseL3ServiceFTE", precision = 10)
    public Float getBaseL3serviceFte() {
	return this.baseL3serviceFte;
    }

    public void setBaseL3serviceFte(Float baseL3serviceFte) {
	this.baseL3serviceFte = baseL3serviceFte;
    }

    @Column(name = "AugmentedL3ServiceFTE", precision = 10)
    public Float getAugmentedL3serviceFte() {
	return this.augmentedL3serviceFte;
    }

    public void setAugmentedL3serviceFte(Float augmentedL3serviceFte) {
	this.augmentedL3serviceFte = augmentedL3serviceFte;
    }
    /**
   	 * @return the opportunityScope
   	 */
       @ManyToOne(fetch = FetchType.LAZY)
       @JoinColumn(name = "OpportunityScopeID")
   	public OpportunityScope getOpportunityScope() {
   		return opportunityScope;
   	}

   	/**
   	 * @param opportunityScope the opportunityScope to set
   	 */
   	public void setOpportunityScope(OpportunityScope opportunityScope) {
   		this.opportunityScope = opportunityScope;
   	}
}
