package com.ericsson.mssp.common.entity;

// Generated Feb 19, 2013 8:54:11 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SolutionEnhanDevRicefw generated by hbm2java
 */
@Entity
@Table(name = "SolutionEnhanDevRICEFW")
public class SolutionEnhanDevRicefw implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 600844228982082825L;
    private Integer solutionEnhanDevRicefwId;
    private Solution solution;
    private SolutionApproachDimension solutionApproachDimension;
    private Float qaunSimpleInterface;
    private Float qaunMediumInterface;
    private Float qaunComplexInterface;
    private Float qaunSimpleExtension;
    private Float qaunMediumExtension;
    private Float qaunComplexExtension;
    private Float qaunSimpleReport;
    private Float qaunMediumReport;
    private Float qaunComplexReport;
    private Float qaunSimpleWorkflow;
    private Float qaunMediumWorkflow;
    private Float qaunComplexWorkflow;
    private Float qaunSimpleTotal;
    private Float qaunMediumTotal;
    private Float qaunComplexTotal;
    private Float effortSimpleInterface;
    private Float effortMediumInterface;
    private Float effortComplexInterface;
    private Float effortSimpleExtension;
    private Float effortMediumExtension;
    private Float effortComplexExtension;
    private Float effortSimpleReport;
    private Float effortMediumReport;
    private Float effortComplexReport;
    private Float effortSimpleWorkflow;
    private Float effortMediumWorkflow;
    private Float effortComplexWorkflow;
    private Float effortSimpleTotal;
    private Float effortMediumTotal;
    private Float effortComplexTotal;
    private Float totalEffortHrsInterface;
    private Float totalEffortHrsExtension;
    private Float totalEffortHrsReport;
    private Float totalEffortHrsWorkflow;
    private Float totalEffortHrs;
    private Float effortManDays;
    private Float effortManWeeks;
    private Float effortManMonths;
    private Float durition;
    private String duritionUnit;
    private Float averageFte;
	private OpportunityScope opportunityScope;

    public SolutionEnhanDevRicefw() {
    }

    public SolutionEnhanDevRicefw(Solution solution) {
	this.solution = solution;
    }

    public SolutionEnhanDevRicefw(Solution solution,
	    SolutionApproachDimension solutionApproachDimension,
	    Float qaunSimpleInterface, Float qaunMediumInterface,
	    Float qaunComplexInterface, Float qaunSimpleExtension,
	    Float qaunMediumExtension, Float qaunComplexExtension,
	    Float qaunSimpleReport, Float qaunMediumReport,
	    Float qaunComplexReport, Float qaunSimpleWorkflow,
	    Float qaunMediumWorkflow, Float qaunComplexWorkflow,
	    Float qaunSimpleTotal, Float qaunMediumTotal,
	    Float qaunComplexTotal, Float effortSimpleInterface,
	    Float effortMediumInterface, Float effortComplexInterface,
	    Float effortSimpleExtension, Float effortMediumExtension,
	    Float effortComplexExtension, Float effortSimpleReport,
	    Float effortMediumReport, Float effortComplexReport,
	    Float effortSimpleWorkflow, Float effortMediumWorkflow,
	    Float effortComplexWorkflow, Float effortSimpleTotal,
	    Float effortMediumTotal, Float effortComplexTotal,
	    Float totalEffortHrsInterface, Float totalEffortHrsExtension,
	    Float totalEffortHrsReport, Float totalEffortHrsWorkflow,
	    Float totalEffortHrs, Float effortManDays, Float effortManWeeks,
	    Float effortManMonths, Float durition, String duritionUnit,
	    Float averageFte) {
	this.solution = solution;
	this.solutionApproachDimension = solutionApproachDimension;
	this.qaunSimpleInterface = qaunSimpleInterface;
	this.qaunMediumInterface = qaunMediumInterface;
	this.qaunComplexInterface = qaunComplexInterface;
	this.qaunSimpleExtension = qaunSimpleExtension;
	this.qaunMediumExtension = qaunMediumExtension;
	this.qaunComplexExtension = qaunComplexExtension;
	this.qaunSimpleReport = qaunSimpleReport;
	this.qaunMediumReport = qaunMediumReport;
	this.qaunComplexReport = qaunComplexReport;
	this.qaunSimpleWorkflow = qaunSimpleWorkflow;
	this.qaunMediumWorkflow = qaunMediumWorkflow;
	this.qaunComplexWorkflow = qaunComplexWorkflow;
	this.qaunSimpleTotal = qaunSimpleTotal;
	this.qaunMediumTotal = qaunMediumTotal;
	this.qaunComplexTotal = qaunComplexTotal;
	this.effortSimpleInterface = effortSimpleInterface;
	this.effortMediumInterface = effortMediumInterface;
	this.effortComplexInterface = effortComplexInterface;
	this.effortSimpleExtension = effortSimpleExtension;
	this.effortMediumExtension = effortMediumExtension;
	this.effortComplexExtension = effortComplexExtension;
	this.effortSimpleReport = effortSimpleReport;
	this.effortMediumReport = effortMediumReport;
	this.effortComplexReport = effortComplexReport;
	this.effortSimpleWorkflow = effortSimpleWorkflow;
	this.effortMediumWorkflow = effortMediumWorkflow;
	this.effortComplexWorkflow = effortComplexWorkflow;
	this.effortSimpleTotal = effortSimpleTotal;
	this.effortMediumTotal = effortMediumTotal;
	this.effortComplexTotal = effortComplexTotal;
	this.totalEffortHrsInterface = totalEffortHrsInterface;
	this.totalEffortHrsExtension = totalEffortHrsExtension;
	this.totalEffortHrsReport = totalEffortHrsReport;
	this.totalEffortHrsWorkflow = totalEffortHrsWorkflow;
	this.totalEffortHrs = totalEffortHrs;
	this.effortManDays = effortManDays;
	this.effortManWeeks = effortManWeeks;
	this.effortManMonths = effortManMonths;
	this.durition = durition;
	this.duritionUnit = duritionUnit;
	this.averageFte = averageFte;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "SolutionEnhanDevRicefwId", unique = true, nullable = false)
    public Integer getSolutionEnhanDevRicefwId() {
	return this.solutionEnhanDevRicefwId;
    }

    public void setSolutionEnhanDevRicefwId(Integer solutionEnhanDevRicefwId) {
	this.solutionEnhanDevRicefwId = solutionEnhanDevRicefwId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "SolutionID", nullable = false)
    public Solution getSolution() {
	return this.solution;
    }

    public void setSolution(Solution solution) {
	this.solution = solution;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "SolutionApproachDimensionID")
    public SolutionApproachDimension getSolutionApproachDimension() {
	return this.solutionApproachDimension;
    }

    public void setSolutionApproachDimension(
	    SolutionApproachDimension solutionApproachDimension) {
	this.solutionApproachDimension = solutionApproachDimension;
    }

    @Column(name = "QaunSimpleInterface", precision = 10)
    public Float getQaunSimpleInterface() {
	return this.qaunSimpleInterface;
    }

    public void setQaunSimpleInterface(Float qaunSimpleInterface) {
	this.qaunSimpleInterface = qaunSimpleInterface;
    }

    @Column(name = "QaunMediumInterface", precision = 10)
    public Float getQaunMediumInterface() {
	return this.qaunMediumInterface;
    }

    public void setQaunMediumInterface(Float qaunMediumInterface) {
	this.qaunMediumInterface = qaunMediumInterface;
    }

    @Column(name = "QaunComplexInterface", precision = 10)
    public Float getQaunComplexInterface() {
	return this.qaunComplexInterface;
    }

    public void setQaunComplexInterface(Float qaunComplexInterface) {
	this.qaunComplexInterface = qaunComplexInterface;
    }

    @Column(name = "QaunSimpleExtension", precision = 10)
    public Float getQaunSimpleExtension() {
	return this.qaunSimpleExtension;
    }

    public void setQaunSimpleExtension(Float qaunSimpleExtension) {
	this.qaunSimpleExtension = qaunSimpleExtension;
    }

    @Column(name = "QaunMediumExtension", precision = 10)
    public Float getQaunMediumExtension() {
	return this.qaunMediumExtension;
    }

    public void setQaunMediumExtension(Float qaunMediumExtension) {
	this.qaunMediumExtension = qaunMediumExtension;
    }

    @Column(name = "QaunComplexExtension", precision = 10)
    public Float getQaunComplexExtension() {
	return this.qaunComplexExtension;
    }

    public void setQaunComplexExtension(Float qaunComplexExtension) {
	this.qaunComplexExtension = qaunComplexExtension;
    }

    @Column(name = "QaunSimpleReport", precision = 10)
    public Float getQaunSimpleReport() {
	return this.qaunSimpleReport;
    }

    public void setQaunSimpleReport(Float qaunSimpleReport) {
	this.qaunSimpleReport = qaunSimpleReport;
    }

    @Column(name = "QaunMediumReport", precision = 10)
    public Float getQaunMediumReport() {
	return this.qaunMediumReport;
    }

    public void setQaunMediumReport(Float qaunMediumReport) {
	this.qaunMediumReport = qaunMediumReport;
    }

    @Column(name = "QaunComplexReport", precision = 10)
    public Float getQaunComplexReport() {
	return this.qaunComplexReport;
    }

    public void setQaunComplexReport(Float qaunComplexReport) {
	this.qaunComplexReport = qaunComplexReport;
    }

    @Column(name = "QaunSimpleWorkflow", precision = 10)
    public Float getQaunSimpleWorkflow() {
	return this.qaunSimpleWorkflow;
    }

    public void setQaunSimpleWorkflow(Float qaunSimpleWorkflow) {
	this.qaunSimpleWorkflow = qaunSimpleWorkflow;
    }

    @Column(name = "QaunMediumWorkflow", precision = 10)
    public Float getQaunMediumWorkflow() {
	return this.qaunMediumWorkflow;
    }

    public void setQaunMediumWorkflow(Float qaunMediumWorkflow) {
	this.qaunMediumWorkflow = qaunMediumWorkflow;
    }

    @Column(name = "QaunComplexWorkflow", precision = 10)
    public Float getQaunComplexWorkflow() {
	return this.qaunComplexWorkflow;
    }

    public void setQaunComplexWorkflow(Float qaunComplexWorkflow) {
	this.qaunComplexWorkflow = qaunComplexWorkflow;
    }

    @Column(name = "QaunSimpleTotal", precision = 10)
    public Float getQaunSimpleTotal() {
	return this.qaunSimpleTotal;
    }

    public void setQaunSimpleTotal(Float qaunSimpleTotal) {
	this.qaunSimpleTotal = qaunSimpleTotal;
    }

    @Column(name = "QaunMediumTotal", precision = 10)
    public Float getQaunMediumTotal() {
	return this.qaunMediumTotal;
    }

    public void setQaunMediumTotal(Float qaunMediumTotal) {
	this.qaunMediumTotal = qaunMediumTotal;
    }

    @Column(name = "QaunComplexTotal", precision = 10)
    public Float getQaunComplexTotal() {
	return this.qaunComplexTotal;
    }

    public void setQaunComplexTotal(Float qaunComplexTotal) {
	this.qaunComplexTotal = qaunComplexTotal;
    }

    @Column(name = "EffortSimpleInterface", precision = 10)
    public Float getEffortSimpleInterface() {
	return this.effortSimpleInterface;
    }

    public void setEffortSimpleInterface(Float effortSimpleInterface) {
	this.effortSimpleInterface = effortSimpleInterface;
    }

    @Column(name = "EffortMediumInterface", precision = 10)
    public Float getEffortMediumInterface() {
	return this.effortMediumInterface;
    }

    public void setEffortMediumInterface(Float effortMediumInterface) {
	this.effortMediumInterface = effortMediumInterface;
    }

    @Column(name = "EffortComplexInterface", precision = 10)
    public Float getEffortComplexInterface() {
	return this.effortComplexInterface;
    }

    public void setEffortComplexInterface(Float effortComplexInterface) {
	this.effortComplexInterface = effortComplexInterface;
    }

    @Column(name = "EffortSimpleExtension", precision = 10)
    public Float getEffortSimpleExtension() {
	return this.effortSimpleExtension;
    }

    public void setEffortSimpleExtension(Float effortSimpleExtension) {
	this.effortSimpleExtension = effortSimpleExtension;
    }

    @Column(name = "EffortMediumExtension", precision = 10)
    public Float getEffortMediumExtension() {
	return this.effortMediumExtension;
    }

    public void setEffortMediumExtension(Float effortMediumExtension) {
	this.effortMediumExtension = effortMediumExtension;
    }

    @Column(name = "EffortComplexExtension", precision = 10)
    public Float getEffortComplexExtension() {
	return this.effortComplexExtension;
    }

    public void setEffortComplexExtension(Float effortComplexExtension) {
	this.effortComplexExtension = effortComplexExtension;
    }

    @Column(name = "EffortSimpleReport", precision = 10)
    public Float getEffortSimpleReport() {
	return this.effortSimpleReport;
    }

    public void setEffortSimpleReport(Float effortSimpleReport) {
	this.effortSimpleReport = effortSimpleReport;
    }

    @Column(name = "EffortMediumReport", precision = 10)
    public Float getEffortMediumReport() {
	return this.effortMediumReport;
    }

    public void setEffortMediumReport(Float effortMediumReport) {
	this.effortMediumReport = effortMediumReport;
    }

    @Column(name = "EffortComplexReport", precision = 10)
    public Float getEffortComplexReport() {
	return this.effortComplexReport;
    }

    public void setEffortComplexReport(Float effortComplexReport) {
	this.effortComplexReport = effortComplexReport;
    }

    @Column(name = "EffortSimpleWorkflow", precision = 10)
    public Float getEffortSimpleWorkflow() {
	return this.effortSimpleWorkflow;
    }

    public void setEffortSimpleWorkflow(Float effortSimpleWorkflow) {
	this.effortSimpleWorkflow = effortSimpleWorkflow;
    }

    @Column(name = "EffortMediumWorkflow", precision = 10)
    public Float getEffortMediumWorkflow() {
	return this.effortMediumWorkflow;
    }

    public void setEffortMediumWorkflow(Float effortMediumWorkflow) {
	this.effortMediumWorkflow = effortMediumWorkflow;
    }

    @Column(name = "EffortComplexWorkflow", precision = 10)
    public Float getEffortComplexWorkflow() {
	return this.effortComplexWorkflow;
    }

    public void setEffortComplexWorkflow(Float effortComplexWorkflow) {
	this.effortComplexWorkflow = effortComplexWorkflow;
    }

    @Column(name = "EffortSimpleTotal", precision = 10)
    public Float getEffortSimpleTotal() {
	return this.effortSimpleTotal;
    }

    public void setEffortSimpleTotal(Float effortSimpleTotal) {
	this.effortSimpleTotal = effortSimpleTotal;
    }

    @Column(name = "EffortMediumTotal", precision = 10)
    public Float getEffortMediumTotal() {
	return this.effortMediumTotal;
    }

    public void setEffortMediumTotal(Float effortMediumTotal) {
	this.effortMediumTotal = effortMediumTotal;
    }

    @Column(name = "EffortComplexTotal", precision = 10)
    public Float getEffortComplexTotal() {
	return this.effortComplexTotal;
    }

    public void setEffortComplexTotal(Float effortComplexTotal) {
	this.effortComplexTotal = effortComplexTotal;
    }

    @Column(name = "TotalEffortHrsInterface", precision = 10)
    public Float getTotalEffortHrsInterface() {
	return this.totalEffortHrsInterface;
    }

    public void setTotalEffortHrsInterface(Float totalEffortHrsInterface) {
	this.totalEffortHrsInterface = totalEffortHrsInterface;
    }

    @Column(name = "TotalEffortHrsExtension", precision = 10)
    public Float getTotalEffortHrsExtension() {
	return this.totalEffortHrsExtension;
    }

    public void setTotalEffortHrsExtension(Float totalEffortHrsExtension) {
	this.totalEffortHrsExtension = totalEffortHrsExtension;
    }

    @Column(name = "TotalEffortHrsReport", precision = 10)
    public Float getTotalEffortHrsReport() {
	return this.totalEffortHrsReport;
    }

    public void setTotalEffortHrsReport(Float totalEffortHrsReport) {
	this.totalEffortHrsReport = totalEffortHrsReport;
    }

    @Column(name = "TotalEffortHrsWorkflow", precision = 10)
    public Float getTotalEffortHrsWorkflow() {
	return this.totalEffortHrsWorkflow;
    }

    public void setTotalEffortHrsWorkflow(Float totalEffortHrsWorkflow) {
	this.totalEffortHrsWorkflow = totalEffortHrsWorkflow;
    }

    @Column(name = "TotalEffortHrs", precision = 10)
    public Float getTotalEffortHrs() {
	return this.totalEffortHrs;
    }

    public void setTotalEffortHrs(Float totalEffortHrs) {
	this.totalEffortHrs = totalEffortHrs;
    }

    @Column(name = "EffortManDays", precision = 10)
    public Float getEffortManDays() {
	return this.effortManDays;
    }

    public void setEffortManDays(Float effortManDays) {
	this.effortManDays = effortManDays;
    }

    @Column(name = "EffortManWeeks", precision = 10)
    public Float getEffortManWeeks() {
	return this.effortManWeeks;
    }

    public void setEffortManWeeks(Float effortManWeeks) {
	this.effortManWeeks = effortManWeeks;
    }

    @Column(name = "EffortManMonths", precision = 10)
    public Float getEffortManMonths() {
	return this.effortManMonths;
    }

    public void setEffortManMonths(Float effortManMonths) {
	this.effortManMonths = effortManMonths;
    }

    @Column(name = "Durition", precision = 10)
    public Float getDurition() {
	return this.durition;
    }

    public void setDurition(Float durition) {
	this.durition = durition;
    }

    @Column(name = "DuritionUnit", length = 50)
    public String getDuritionUnit() {
	return this.duritionUnit;
    }

    public void setDuritionUnit(String duritionUnit) {
	this.duritionUnit = duritionUnit;
    }

    @Column(name = "AverageFTE", precision = 10)
    public Float getAverageFte() {
	return this.averageFte;
    }

    public void setAverageFte(Float averageFte) {
	this.averageFte = averageFte;
    }
    
    /**
   	 * @return the opportunityScope
   	 */
       @ManyToOne(fetch = FetchType.LAZY)
       @JoinColumn(name = "OpportunityScopeID")
   	public OpportunityScope getOpportunityScope() {
   		return opportunityScope;
   	}

   	/**
   	 * @param opportunityScope the opportunityScope to set
   	 */
   	public void setOpportunityScope(OpportunityScope opportunityScope) {
   		this.opportunityScope = opportunityScope;
   	}

}
