package com.ericsson.mssp.common.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SolutionApa generated by hbm2java
 */
@Entity
@Table(name = "SolutionAPA")
public class SolutionAPA implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6749782636341097750L;
	private Integer solutionApaid;
	private Solution solution;
	private OpportunityScope opportunityScope;
	private String businessFunction;
	private String applicationName;
	private Integer noUsers;
	private String platform;
	private String databasenm;
	private String primarySkill;
	private String secondarySkill;
	private Integer businessCriticalilty;
	private Integer levelofDocuments;
	private Integer stability;
	private Integer longivity;
	private Integer complexity;
	private Integer percentageShare;
	private Float computedRiskExposure;
	private Float computedRiskFactor;

	public SolutionAPA() {
	}

	public SolutionAPA(Solution solution, OpportunityScope opportunityScope) {
		this.solution = solution;
		this.opportunityScope = opportunityScope;
	}

	public SolutionAPA(Solution solution, OpportunityScope opportunityScope,
			String businessFunction, String applicationName, Integer noUsers,
			String platform, String databasenm, String primarySkill,
			String secondarySkill, Integer businessCriticalilty,
			Integer levelofDocuments, Integer stability, Integer longivity,
			Integer complexity, Integer percentageShare,
			Float computedRiskExposure, Float computedRiskFactor) {
		this.solution = solution;
		this.opportunityScope = opportunityScope;
		this.businessFunction = businessFunction;
		this.applicationName = applicationName;
		this.noUsers = noUsers;
		this.platform = platform;
		this.databasenm = databasenm;
		this.primarySkill = primarySkill;
		this.secondarySkill = secondarySkill;
		this.businessCriticalilty = businessCriticalilty;
		this.levelofDocuments = levelofDocuments;
		this.stability = stability;
		this.longivity = longivity;
		this.complexity = complexity;
		this.percentageShare = percentageShare;
		this.computedRiskExposure = computedRiskExposure;
		this.computedRiskFactor = computedRiskFactor;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "SolutionAPAID", unique = true, nullable = false)
	public Integer getSolutionApaid() {
		return this.solutionApaid;
	}

	public void setSolutionApaid(Integer solutionApaid) {
		this.solutionApaid = solutionApaid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SolutionID", nullable = false)
	public Solution getSolution() {
		return this.solution;
	}

	public void setSolution(Solution solution) {
		this.solution = solution;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OpportunityScopeID", nullable = false)
	public OpportunityScope getOpportunityScope() {
		return this.opportunityScope;
	}

	public void setOpportunityScope(OpportunityScope opportunityScope) {
		this.opportunityScope = opportunityScope;
	}

	@Column(name = "BusinessFunction", length = 100)
	public String getBusinessFunction() {
		return this.businessFunction;
	}

	public void setBusinessFunction(String businessFunction) {
		this.businessFunction = businessFunction;
	}

	@Column(name = "ApplicationName", length = 100)
	public String getApplicationName() {
		return this.applicationName;
	}

	public void setApplicationName(String applicationName) {
		this.applicationName = applicationName;
	}

	@Column(name = "NoUsers")
	public Integer getNoUsers() {
		return this.noUsers;
	}

	public void setNoUsers(Integer noUsers) {
		this.noUsers = noUsers;
	}

	@Column(name = "Platform", length = 100)
	public String getPlatform() {
		return this.platform;
	}

	public void setPlatform(String platform) {
		this.platform = platform;
	}

	@Column(name = "Databasenm", length = 100)
	public String getDatabasenm() {
		return this.databasenm;
	}

	public void setDatabasenm(String databasenm) {
		this.databasenm = databasenm;
	}

	@Column(name = "PrimarySkill", length = 100)
	public String getPrimarySkill() {
		return this.primarySkill;
	}

	public void setPrimarySkill(String primarySkill) {
		this.primarySkill = primarySkill;
	}

	@Column(name = "SecondarySkill", length = 100)
	public String getSecondarySkill() {
		return this.secondarySkill;
	}

	public void setSecondarySkill(String secondarySkill) {
		this.secondarySkill = secondarySkill;
	}

	@Column(name = "BusinessCriticalilty")
	public Integer getBusinessCriticalilty() {
		return this.businessCriticalilty;
	}

	public void setBusinessCriticalilty(Integer businessCriticalilty) {
		this.businessCriticalilty = businessCriticalilty;
	}

	@Column(name = "LevelofDocuments")
	public Integer getLevelofDocuments() {
		return this.levelofDocuments;
	}

	public void setLevelofDocuments(Integer levelofDocuments) {
		this.levelofDocuments = levelofDocuments;
	}

	@Column(name = "Stability")
	public Integer getStability() {
		return this.stability;
	}

	public void setStability(Integer stability) {
		this.stability = stability;
	}

	@Column(name = "Longivity")
	public Integer getLongivity() {
		return this.longivity;
	}

	public void setLongivity(Integer longivity) {
		this.longivity = longivity;
	}

	@Column(name = "Complexity")
	public Integer getComplexity() {
		return this.complexity;
	}

	public void setComplexity(Integer complexity) {
		this.complexity = complexity;
	}

	@Column(name = "PercentageShare")
	public Integer getPercentageShare() {
		return this.percentageShare;
	}

	public void setPercentageShare(Integer percentageShare) {
		this.percentageShare = percentageShare;
	}

	@Column(name = "ComputedRiskExposure", precision = 10)
	public Float getComputedRiskExposure() {
		return this.computedRiskExposure;
	}

	public void setComputedRiskExposure(Float computedRiskExposure) {
		this.computedRiskExposure = computedRiskExposure;
	}

	@Column(name = "ComputedRiskFactor", precision = 10)
	public Float getComputedRiskFactor() {
		return this.computedRiskFactor;
	}

	public void setComputedRiskFactor(Float computedRiskFactor) {
		this.computedRiskFactor = computedRiskFactor;
	}

}
