package com.ericsson.mssp.common.entity;

// Generated Jan 29, 2013 11:53:09 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SolutionL2operations generated by hbm2java
 */
@Entity
@Table(name = "SolutionL2Operations")
public class SolutionL2operations implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 9174770579922544720L;
    private Integer solutionL2operationsId;
    private Solution solution;
    private SupportWindowMatrix supportWindowMatrix;
    private SolutionApproachDimension solutionApproachDimension;
    private Float pcofL2incidents;
    private Float totalL2incidentsperYr;
    private Float pcsimpleIncidents;
    private Float pcmediumIncidents;
    private Float pccomplexIncidents;
    private Float hrsSimpleIncidents;
    private Float hrsMediumIncidents;
    private Float hrsComplexIncidents;
    private Float avgResolutionTimeHrs;
    private Float anualHrsSpent;
    private Float utilizationperYr;
    private Float baseL2operationFte;
    private Float augmentedL2operationFte;
	private OpportunityScope opportunityScope;

    public SolutionL2operations() {
    }

    public SolutionL2operations(Solution solution) {
	this.solution = solution;
    }

    public SolutionL2operations(Solution solution,
	    SupportWindowMatrix supportWindowMatrix,
	    SolutionApproachDimension solutionApproachDimension,
	    Float pcofL2incidents, Float totalL2incidentsperYr,
	    Float pcsimpleIncidents, Float pcmediumIncidents,
	    Float pccomplexIncidents, Float hrsSimpleIncidents,
	    Float hrsMediumIncidents, Float hrsComplexIncidents,
	    Float avgResolutionTimeHrs, Float anualHrsSpent,
	    Float utilizationperYr, Float baseL2operationFte,
	    Float augmentedL2operationFte) {
	this.solution = solution;
	this.supportWindowMatrix = supportWindowMatrix;
	this.solutionApproachDimension = solutionApproachDimension;
	this.pcofL2incidents = pcofL2incidents;
	this.totalL2incidentsperYr = totalL2incidentsperYr;
	this.pcsimpleIncidents = pcsimpleIncidents;
	this.pcmediumIncidents = pcmediumIncidents;
	this.pccomplexIncidents = pccomplexIncidents;
	this.hrsSimpleIncidents = hrsSimpleIncidents;
	this.hrsMediumIncidents = hrsMediumIncidents;
	this.hrsComplexIncidents = hrsComplexIncidents;
	this.avgResolutionTimeHrs = avgResolutionTimeHrs;
	this.anualHrsSpent = anualHrsSpent;
	this.utilizationperYr = utilizationperYr;
	this.baseL2operationFte = baseL2operationFte;
	this.augmentedL2operationFte = augmentedL2operationFte;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "solutionL2operationsID", unique = true, nullable = false)
    public Integer getSolutionL2operationsId() {
	return this.solutionL2operationsId;
    }

    public void setSolutionL2operationsId(Integer solutionL2inputsId) {
	this.solutionL2operationsId = solutionL2inputsId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "SolutionID", nullable = false)
    public Solution getSolution() {
	return this.solution;
    }

    public void setSolution(Solution solution) {
	this.solution = solution;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "SupportWindowMatrixID")
    public SupportWindowMatrix getSupportWindowMatrix() {
	return this.supportWindowMatrix;
    }

    public void setSupportWindowMatrix(SupportWindowMatrix supportWindowMatrix) {
	this.supportWindowMatrix = supportWindowMatrix;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "SolutionApproachDimensionID")
    public SolutionApproachDimension getSolutionApproachDimension() {
	return this.solutionApproachDimension;
    }

    public void setSolutionApproachDimension(
	    SolutionApproachDimension solutionApproachDimension) {
	this.solutionApproachDimension = solutionApproachDimension;
    }

    @Column(name = "PCofL2Incidents", precision = 10)
    public Float getPcofL2incidents() {
	return this.pcofL2incidents;
    }

    public void setPcofL2incidents(Float pcofL2incidents) {
	this.pcofL2incidents = pcofL2incidents;
    }

    @Column(name = "TotalL2IncidentsperYr", precision = 10)
    public Float getTotalL2incidentsperYr() {
	return this.totalL2incidentsperYr;
    }

    public void setTotalL2incidentsperYr(Float totalL2incidentsperYr) {
	this.totalL2incidentsperYr = totalL2incidentsperYr;
    }

    @Column(name = "PCSimpleIncidents", precision = 10)
    public Float getPcsimpleIncidents() {
	return this.pcsimpleIncidents;
    }

    public void setPcsimpleIncidents(Float pcsimpleIncidents) {
	this.pcsimpleIncidents = pcsimpleIncidents;
    }

    @Column(name = "PCMediumIncidents", precision = 10)
    public Float getPcmediumIncidents() {
	return this.pcmediumIncidents;
    }

    public void setPcmediumIncidents(Float pcmediumIncidents) {
	this.pcmediumIncidents = pcmediumIncidents;
    }

    @Column(name = "PCComplexIncidents", precision = 10)
    public Float getPccomplexIncidents() {
	return this.pccomplexIncidents;
    }

    public void setPccomplexIncidents(Float pccomplexIncidents) {
	this.pccomplexIncidents = pccomplexIncidents;
    }

    @Column(name = "HrsSimpleIncidents", precision = 10)
    public Float getHrsSimpleIncidents() {
	return this.hrsSimpleIncidents;
    }

    public void setHrsSimpleIncidents(Float hrsSimpleIncidents) {
	this.hrsSimpleIncidents = hrsSimpleIncidents;
    }

    @Column(name = "HrsMediumIncidents", precision = 10)
    public Float getHrsMediumIncidents() {
	return this.hrsMediumIncidents;
    }

    public void setHrsMediumIncidents(Float hrsMediumIncidents) {
	this.hrsMediumIncidents = hrsMediumIncidents;
    }

    @Column(name = "HrsComplexIncidents", precision = 10)
    public Float getHrsComplexIncidents() {
	return this.hrsComplexIncidents;
    }

    public void setHrsComplexIncidents(Float hrsComplexIncidents) {
	this.hrsComplexIncidents = hrsComplexIncidents;
    }

    @Column(name = "AvgResolutionTimeHrs", precision = 10)
    public Float getAvgResolutionTimeHrs() {
	return this.avgResolutionTimeHrs;
    }

    public void setAvgResolutionTimeHrs(Float avgResolutionTimeHrs) {
	this.avgResolutionTimeHrs = avgResolutionTimeHrs;
    }

    @Column(name = "AnualHrsSpent", precision = 10)
    public Float getAnualHrsSpent() {
	return this.anualHrsSpent;
    }

    public void setAnualHrsSpent(Float anualHrsSpent) {
	this.anualHrsSpent = anualHrsSpent;
    }

    @Column(name = "UtilizationperYr", precision = 10)
    public Float getUtilizationperYr() {
	return this.utilizationperYr;
    }

    public void setUtilizationperYr(Float utilizationperYr) {
	this.utilizationperYr = utilizationperYr;
    }

    @Column(name = "BaseL2OperationFTE", precision = 10)
    public Float getBaseL2operationFte() {
	return this.baseL2operationFte;
    }

    public void setBaseL2operationFte(Float baseL2operationFte) {
	this.baseL2operationFte = baseL2operationFte;
    }

    @Column(name = "AugmentedL2OperationFTE", precision = 10)
    public Float getAugmentedL2operationFte() {
	return this.augmentedL2operationFte;
    }

    public void setAugmentedL2operationFte(Float augmentedL2operationFte) {
	this.augmentedL2operationFte = augmentedL2operationFte;
    }
    /**
   	 * @return the opportunityScope
   	 */
       @ManyToOne(fetch = FetchType.LAZY)
       @JoinColumn(name = "OpportunityScopeID")
   	public OpportunityScope getOpportunityScope() {
   		return opportunityScope;
   	}

   	/**
   	 * @param opportunityScope the opportunityScope to set
   	 */
   	public void setOpportunityScope(OpportunityScope opportunityScope) {
   		this.opportunityScope = opportunityScope;
   	}
}
