package com.ericsson.mssp.common.entity;

// Generated Feb 13, 2013 12:26:59 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SolutionApprover generated by hbm2java
 */
@Entity
@Table(name = "SolutionApprover")
public class SolutionApprover implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 52251755566121032L;
    private Integer solutionApproverId;
    private Solution solution;
    private String approver;
    private Integer sequenceId;
    private Boolean activeId;
    private Date requestDate;
    private Set<SolutionApprovalStatus> solutionApprovalStatuses = new HashSet<SolutionApprovalStatus>(
	    0);

    public SolutionApprover() {
    }

    public SolutionApprover(Solution solution) {
	this.solution = solution;
    }

    public SolutionApprover(Solution solution, String approver,
	    Integer sequenceId, Boolean activeId, Date requestDate,
	    Set<SolutionApprovalStatus> solutionApprovalStatuses) {
	this.solution = solution;
	this.approver = approver;
	this.sequenceId = sequenceId;
	this.activeId = activeId;
	this.requestDate = requestDate;
	this.solutionApprovalStatuses = solutionApprovalStatuses;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "SolutionApproverID", unique = true, nullable = false)
    public Integer getSolutionApproverId() {
	return this.solutionApproverId;
    }

    public void setSolutionApproverId(Integer solutionApproverId) {
	this.solutionApproverId = solutionApproverId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "SolutionID", nullable = false)
    public Solution getSolution() {
	return this.solution;
    }

    public void setSolution(Solution solution) {
	this.solution = solution;
    }

    @Column(name = "Approver", length = 100)
    public String getApprover() {
	return this.approver;
    }

    public void setApprover(String approver) {
	this.approver = approver;
    }

    @Column(name = "SequenceID")
    public Integer getSequenceId() {
	return this.sequenceId;
    }

    public void setSequenceId(Integer sequenceId) {
	this.sequenceId = sequenceId;
    }

    @Column(name = "ActiveID")
    public Boolean getActiveId() {
	return this.activeId;
    }

    public void setActiveId(Boolean activeId) {
	this.activeId = activeId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "RequestDate", length = 19)
    public Date getRequestDate() {
	return this.requestDate;
    }

    public void setRequestDate(Date requestDate) {
	this.requestDate = requestDate;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "solutionApprover")
    public Set<SolutionApprovalStatus> getSolutionApprovalStatuses() {
	return this.solutionApprovalStatuses;
    }

    public void setSolutionApprovalStatuses(
	    Set<SolutionApprovalStatus> solutionApprovalStatuses) {
	this.solutionApprovalStatuses = solutionApprovalStatuses;
    }

}
