package com.ericsson.mssp.common.entity;

// Generated Feb 13, 2013 12:26:59 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SolutionApprovalStatus generated by hbm2java
 */
@Entity
@Table(name = "SolutionApprovalStatus")
public class SolutionApprovalStatus implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1048168005129533196L;
    private Integer solutionApprovalStatusId;
    private SolutionApprover solutionApprover;
    private Boolean approved;
    private Date responseDate;
    private String comments;

    public SolutionApprovalStatus() {
    }

    public SolutionApprovalStatus(SolutionApprover solutionApprover,
	    Boolean approved, Date responseDate, String comments) {
	this.solutionApprover = solutionApprover;
	this.approved = approved;
	this.responseDate = responseDate;
	this.comments = comments;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "SolutionApprovalStatusID", unique = true, nullable = false)
    public Integer getSolutionApprovalStatusId() {
	return this.solutionApprovalStatusId;
    }

    public void setSolutionApprovalStatusId(Integer solutionApprovalStatusId) {
	this.solutionApprovalStatusId = solutionApprovalStatusId;
    }

    @ManyToOne(fetch = FetchType.LAZY,cascade = CascadeType.ALL)
    @JoinColumn(name = "SolutionApproverID")
    public SolutionApprover getSolutionApprover() {
	return this.solutionApprover;
    }

    public void setSolutionApprover(SolutionApprover solutionApprover) {
	this.solutionApprover = solutionApprover;
    }

    @Column(name = "Approved")
    public Boolean getApproved() {
	return this.approved;
    }

    public void setApproved(Boolean approved) {
	this.approved = approved;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "ResponseDate", length = 19)
    public Date getResponseDate() {
	return this.responseDate;
    }

    public void setResponseDate(Date responseDate) {
	this.responseDate = responseDate;
    }

    @Column(name = "Comments")
    public String getComments() {
	return this.comments;
    }

    public void setComments(String comments) {
	this.comments = comments;
    }

}
