package com.ericsson.mssp.common.entity;

// Generated Feb 7, 2013 11:35:07 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SolutionL2addServices generated by hbm2java
 */
@Entity
@Table(name = "SolutionL2AddServices")
public class SolutionL2addServices implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 4043066623231734963L;
    private Integer solutionL2addServicesId;
    private Solution solution;
    private SolutionApproachDimension solutionApproachDimension;
    private String scopeAvailMgmt;
    private String scopeCapacityMgmt;
    private String scopeSecurityMgmt;
    private String scopeL2billOperation;
    private String scopeL2preventive;
    private String scopeL2change;
    private String scopeL2routine;
    private String scopeL2performance;
    private String scopeL2releaseDev;
    private Float effortAvailMgmt;
    private Float effortCapacityMgmt;
    private Float effortSecurityMgmt;
    private Float effortL2billOperation;
    private Float effortL2preventive;
    private Float effortL2change;
    private Float effortL2routine;
    private Float effortL2performance;
    private Float effortL2releaseDev;
    private Float fteavailMgmt;
    private Float ftecapacityMgmt;
    private Float ftesecurityMgmt;
    private Float ftel2billOperation;
    private Float ftel2preventive;
    private Float ftel2change;
    private Float ftel2routine;
    private Float ftel2performance;
    private Float ftel2releaseDev;
    private Float baseL2serviceFte;
    private Float augmentedL2serviceFte;
	private OpportunityScope opportunityScope;

    public SolutionL2addServices() {
    }

    public SolutionL2addServices(Solution solution,
	    SolutionApproachDimension solutionApproachDimension,
	    String scopeAvailMgmt, String scopeCapacityMgmt,
	    String scopeSecurityMgmt, String scopeL2billOperation,
	    String scopeL2preventive, String scopeL2change,
	    String scopeL2routine, String scopeL2performance,
	    String scopeL2releaseDev, Float effortAvailMgmt,
	    Float effortCapacityMgmt, Float effortSecurityMgmt,
	    Float effortL2billOperation, Float effortL2preventive,
	    Float effortL2change, Float effortL2routine,
	    Float effortL2performance, Float effortL2releaseDev,
	    Float fteavailMgmt, Float ftecapacityMgmt, Float ftesecurityMgmt,
	    Float ftel2billOperation, Float ftel2preventive, Float ftel2change,
	    Float ftel2routine, Float ftel2performance, Float ftel2releaseDev,
	    Float baseL2serviceFte, Float augmentedL2serviceFte) {
	this.solution = solution;
	this.solutionApproachDimension = solutionApproachDimension;
	this.scopeAvailMgmt = scopeAvailMgmt;
	this.scopeCapacityMgmt = scopeCapacityMgmt;
	this.scopeSecurityMgmt = scopeSecurityMgmt;
	this.scopeL2billOperation = scopeL2billOperation;
	this.scopeL2preventive = scopeL2preventive;
	this.scopeL2change = scopeL2change;
	this.scopeL2routine = scopeL2routine;
	this.scopeL2performance = scopeL2performance;
	this.scopeL2releaseDev = scopeL2releaseDev;
	this.effortAvailMgmt = effortAvailMgmt;
	this.effortCapacityMgmt = effortCapacityMgmt;
	this.effortSecurityMgmt = effortSecurityMgmt;
	this.effortL2billOperation = effortL2billOperation;
	this.effortL2preventive = effortL2preventive;
	this.effortL2change = effortL2change;
	this.effortL2routine = effortL2routine;
	this.effortL2performance = effortL2performance;
	this.effortL2releaseDev = effortL2releaseDev;
	this.fteavailMgmt = fteavailMgmt;
	this.ftecapacityMgmt = ftecapacityMgmt;
	this.ftesecurityMgmt = ftesecurityMgmt;
	this.ftel2billOperation = ftel2billOperation;
	this.ftel2preventive = ftel2preventive;
	this.ftel2change = ftel2change;
	this.ftel2routine = ftel2routine;
	this.ftel2performance = ftel2performance;
	this.ftel2releaseDev = ftel2releaseDev;
	this.baseL2serviceFte = baseL2serviceFte;
	this.augmentedL2serviceFte = augmentedL2serviceFte;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "SolutionL2AddServicesID", unique = true, nullable = false)
    public Integer getSolutionL2addServicesId() {
	return this.solutionL2addServicesId;
    }

    public void setSolutionL2addServicesId(Integer solutionL2addServicesId) {
	this.solutionL2addServicesId = solutionL2addServicesId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "SolutionID")
    public Solution getSolution() {
	return this.solution;
    }

    public void setSolution(Solution solution) {
	this.solution = solution;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "SolutionApproachDimensionID")
    public SolutionApproachDimension getSolutionApproachDimension() {
	return this.solutionApproachDimension;
    }

    public void setSolutionApproachDimension(
	    SolutionApproachDimension solutionApproachDimension) {
	this.solutionApproachDimension = solutionApproachDimension;
    }

    @Column(name = "ScopeAvailMgmt", length = 3)
    public String getScopeAvailMgmt() {
	return this.scopeAvailMgmt;
    }

    public void setScopeAvailMgmt(String scopeAvailMgmt) {
	this.scopeAvailMgmt = scopeAvailMgmt;
    }

    @Column(name = "ScopeCapacityMgmt", length = 3)
    public String getScopeCapacityMgmt() {
	return this.scopeCapacityMgmt;
    }

    public void setScopeCapacityMgmt(String scopeCapacityMgmt) {
	this.scopeCapacityMgmt = scopeCapacityMgmt;
    }

    @Column(name = "ScopeSecurityMgmt", length = 3)
    public String getScopeSecurityMgmt() {
	return this.scopeSecurityMgmt;
    }

    public void setScopeSecurityMgmt(String scopeSecurityMgmt) {
	this.scopeSecurityMgmt = scopeSecurityMgmt;
    }

    @Column(name = "ScopeL2BillOperation", length = 3)
    public String getScopeL2billOperation() {
	return this.scopeL2billOperation;
    }

    public void setScopeL2billOperation(String scopeL2billOperation) {
	this.scopeL2billOperation = scopeL2billOperation;
    }

    @Column(name = "ScopeL2Preventive", length = 3)
    public String getScopeL2preventive() {
	return this.scopeL2preventive;
    }

    public void setScopeL2preventive(String scopeL2preventive) {
	this.scopeL2preventive = scopeL2preventive;
    }

    @Column(name = "ScopeL2Change", length = 3)
    public String getScopeL2change() {
	return this.scopeL2change;
    }

    public void setScopeL2change(String scopeL2change) {
	this.scopeL2change = scopeL2change;
    }

    @Column(name = "ScopeL2Routine", length = 3)
    public String getScopeL2routine() {
	return this.scopeL2routine;
    }

    public void setScopeL2routine(String scopeL2routine) {
	this.scopeL2routine = scopeL2routine;
    }

    @Column(name = "ScopeL2Performance", length = 3)
    public String getScopeL2performance() {
	return this.scopeL2performance;
    }

    public void setScopeL2performance(String scopeL2performance) {
	this.scopeL2performance = scopeL2performance;
    }

    @Column(name = "ScopeL2ReleaseDev", length = 3)
    public String getScopeL2releaseDev() {
	return this.scopeL2releaseDev;
    }

    public void setScopeL2releaseDev(String scopeL2releaseDev) {
	this.scopeL2releaseDev = scopeL2releaseDev;
    }

    @Column(name = "EffortAvailMgmt", precision = 10)
    public Float getEffortAvailMgmt() {
	return this.effortAvailMgmt;
    }

    public void setEffortAvailMgmt(Float effortAvailMgmt) {
	this.effortAvailMgmt = effortAvailMgmt;
    }

    @Column(name = "EffortCapacityMgmt", precision = 10)
    public Float getEffortCapacityMgmt() {
	return this.effortCapacityMgmt;
    }

    public void setEffortCapacityMgmt(Float effortCapacityMgmt) {
	this.effortCapacityMgmt = effortCapacityMgmt;
    }

    @Column(name = "EffortSecurityMgmt", precision = 10)
    public Float getEffortSecurityMgmt() {
	return this.effortSecurityMgmt;
    }

    public void setEffortSecurityMgmt(Float effortSecurityMgmt) {
	this.effortSecurityMgmt = effortSecurityMgmt;
    }

    @Column(name = "EffortL2BillOperation", precision = 10)
    public Float getEffortL2billOperation() {
	return this.effortL2billOperation;
    }

    public void setEffortL2billOperation(Float effortL2billOperation) {
	this.effortL2billOperation = effortL2billOperation;
    }

    @Column(name = "EffortL2Preventive", precision = 10)
    public Float getEffortL2preventive() {
	return this.effortL2preventive;
    }

    public void setEffortL2preventive(Float effortL2preventive) {
	this.effortL2preventive = effortL2preventive;
    }

    @Column(name = "EffortL2Change", precision = 10)
    public Float getEffortL2change() {
	return this.effortL2change;
    }

    public void setEffortL2change(Float effortL2change) {
	this.effortL2change = effortL2change;
    }

    @Column(name = "EffortL2Routine", precision = 10)
    public Float getEffortL2routine() {
	return this.effortL2routine;
    }

    public void setEffortL2routine(Float effortL2routine) {
	this.effortL2routine = effortL2routine;
    }

    @Column(name = "EffortL2Performance", precision = 10)
    public Float getEffortL2performance() {
	return this.effortL2performance;
    }

    public void setEffortL2performance(Float effortL2performance) {
	this.effortL2performance = effortL2performance;
    }

    @Column(name = "EffortL2ReleaseDev", precision = 10)
    public Float getEffortL2releaseDev() {
	return this.effortL2releaseDev;
    }

    public void setEffortL2releaseDev(Float effortL2releaseDev) {
	this.effortL2releaseDev = effortL2releaseDev;
    }

    @Column(name = "FTEAvailMgmt", precision = 10)
    public Float getFteavailMgmt() {
	return this.fteavailMgmt;
    }

    public void setFteavailMgmt(Float fteavailMgmt) {
	this.fteavailMgmt = fteavailMgmt;
    }

    @Column(name = "FTECapacityMgmt", precision = 10)
    public Float getFtecapacityMgmt() {
	return this.ftecapacityMgmt;
    }

    public void setFtecapacityMgmt(Float ftecapacityMgmt) {
	this.ftecapacityMgmt = ftecapacityMgmt;
    }

    @Column(name = "FTESecurityMgmt", precision = 10)
    public Float getFtesecurityMgmt() {
	return this.ftesecurityMgmt;
    }

    public void setFtesecurityMgmt(Float ftesecurityMgmt) {
	this.ftesecurityMgmt = ftesecurityMgmt;
    }

    @Column(name = "FTEL2BillOperation", precision = 10)
    public Float getFtel2billOperation() {
	return this.ftel2billOperation;
    }

    public void setFtel2billOperation(Float ftel2billOperation) {
	this.ftel2billOperation = ftel2billOperation;
    }

    @Column(name = "FTEL2Preventive", precision = 10)
    public Float getFtel2preventive() {
	return this.ftel2preventive;
    }

    public void setFtel2preventive(Float ftel2preventive) {
	this.ftel2preventive = ftel2preventive;
    }

    @Column(name = "FTEL2Change", precision = 10)
    public Float getFtel2change() {
	return this.ftel2change;
    }

    public void setFtel2change(Float ftel2change) {
	this.ftel2change = ftel2change;
    }

    @Column(name = "FTEL2Routine", precision = 10)
    public Float getFtel2routine() {
	return this.ftel2routine;
    }

    public void setFtel2routine(Float ftel2routine) {
	this.ftel2routine = ftel2routine;
    }

    @Column(name = "FTEL2Performance", precision = 10)
    public Float getFtel2performance() {
	return this.ftel2performance;
    }

    public void setFtel2performance(Float ftel2performance) {
	this.ftel2performance = ftel2performance;
    }

    @Column(name = "FTEL2ReleaseDev", precision = 10)
    public Float getFtel2releaseDev() {
	return this.ftel2releaseDev;
    }

    public void setFtel2releaseDev(Float ftel2releaseDev) {
	this.ftel2releaseDev = ftel2releaseDev;
    }

    @Column(name = "BaseL2ServiceFTE", precision = 10)
    public Float getBaseL2serviceFte() {
	return this.baseL2serviceFte;
    }

    public void setBaseL2serviceFte(Float baseL2serviceFte) {
	this.baseL2serviceFte = baseL2serviceFte;
    }

    @Column(name = "AugmentedL2ServiceFTE", precision = 10)
    public Float getAugmentedL2serviceFte() {
	return this.augmentedL2serviceFte;
    }

    public void setAugmentedL2serviceFte(Float augmentedL2serviceFte) {
	this.augmentedL2serviceFte = augmentedL2serviceFte;
    }
    /**
   	 * @return the opportunityScope
   	 */
       @ManyToOne(fetch = FetchType.LAZY)
       @JoinColumn(name = "OpportunityScopeID")
   	public OpportunityScope getOpportunityScope() {
   		return opportunityScope;
   	}

   	/**
   	 * @param opportunityScope the opportunityScope to set
   	 */
   	public void setOpportunityScope(OpportunityScope opportunityScope) {
   		this.opportunityScope = opportunityScope;
   	}
}
