package com.ericsson.mssp.common.entity;
// Generated Jan 9, 2013 3:37:22 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * StartUpFte generated by hbm2java
 */
@Entity
@Table(name = "StartUpFTE")
public class StartUpFTE implements java.io.Serializable {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1495762681166531667L;
	
	private Integer startUpFteid;
    private Solution solution;
    private OpportunityScope opportunityScope;
    private Integer computedHrs;
    private Float computedFte;
    private Float rolledupFte;

    public StartUpFTE() {
    }

    public StartUpFTE(Solution solution, OpportunityScope opportunityScope) {
	this.solution = solution;
	this.opportunityScope = opportunityScope;
    }

    public StartUpFTE(Solution solution, OpportunityScope opportunityScope,
	    Integer computedHrs, Float computedFte, Float rolledupFte) {
	this.solution = solution;
	this.opportunityScope = opportunityScope;
	this.computedHrs = computedHrs;
	this.computedFte = computedFte;
	this.rolledupFte = rolledupFte;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "StartUpFTEID", unique = true, nullable = false)
    public Integer getStartUpFteid() {
	return this.startUpFteid;
    }

    public void setStartUpFteid(Integer startUpFteid) {
	this.startUpFteid = startUpFteid;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "SolutionID", nullable = false)
    public Solution getSolution() {
	return this.solution;
    }

    public void setSolution(Solution solution) {
	this.solution = solution;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "OpportunityScopeID", nullable = false)
    public OpportunityScope getOpportunityScope() {
	return this.opportunityScope;
    }

    public void setOpportunityScope(OpportunityScope opportunityScope) {
	this.opportunityScope = opportunityScope;
    }

    @Column(name = "ComputedHrs")
    public Integer getComputedHrs() {
	return this.computedHrs;
    }

    public void setComputedHrs(Integer computedHrs) {
	this.computedHrs = computedHrs;
    }

    @Column(name = "ComputedFTE", precision = 10)
    public Float getComputedFte() {
	return this.computedFte;
    }

    public void setComputedFte(Float computedFte) {
	this.computedFte = computedFte;
    }

    @Column(name = "RolledupFTE", precision = 10)
    public Float getRolledupFte() {
	return this.rolledupFte;
    }

    public void setRolledupFte(Float rolledupFte) {
	this.rolledupFte = rolledupFte;
    }

}
