package com.ericsson.mssp.common.entity;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Status generated by hbm2java
 */
@Entity
@Table(name = "Status")
public class Status implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8556321608719311056L;
	private Integer statusId;
	private String statusName;
	private Set<Solution> solutions = new HashSet<Solution>(0);

	public Status() {
	}

	public Status(String statusName, Set<Solution> solutions) {
		this.statusName = statusName;
		this.solutions = solutions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "StatusID", unique = true, nullable = false)
	public Integer getStatusId() {
		return this.statusId;
	}

	public void setStatusId(Integer statusId) {
		this.statusId = statusId;
	}

	@Column(name = "StatusName", length = 50)
	public String getStatusName() {
		return this.statusName;
	}

	public void setStatusName(String statusName) {
		this.statusName = statusName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "status")
	public Set<Solution> getSolutions() {
		return this.solutions;
	}

	public void setSolutions(Set<Solution> solutions) {
		this.solutions = solutions;
	}

}
