package com.ericsson.mssp.common.entity;

// Generated Jan 29, 2013 11:53:09 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SupportWindowMatrix generated by hbm2java
 */
@Entity
@Table(name = "SupportWindowMatrix")
public class SupportWindowMatrix implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = -3702861594231487606L;
    private Integer supportWindowMatrixId;
    private String supportWindow;
    private Float derivedFactor;
    private Set<SolutionL1operations> solutionL1operationses = new HashSet<SolutionL1operations>(
	    0);
    private Set<SolutionServiceDesk> solutionServiceDesks = new HashSet<SolutionServiceDesk>(
	    0);
    private Set<SolutionL2operations> solutionL2operationses = new HashSet<SolutionL2operations>(
	    0);

    public SupportWindowMatrix() {
    }

    public SupportWindowMatrix(String supportWindow, Float derivedFactor,
	    Set<SolutionL1operations> solutionL1operationses,
	    Set<SolutionServiceDesk> solutionServiceDesks,
	    Set<SolutionL2operations> solutionL2operationses) {
	this.supportWindow = supportWindow;
	this.derivedFactor = derivedFactor;
	this.solutionL1operationses = solutionL1operationses;
	this.solutionServiceDesks = solutionServiceDesks;
	this.solutionL2operationses = solutionL2operationses;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "SupportWindowMatrixID", unique = true, nullable = false)
    public Integer getSupportWindowMatrixId() {
	return this.supportWindowMatrixId;
    }

    public void setSupportWindowMatrixId(Integer supportWindowMatrixId) {
	this.supportWindowMatrixId = supportWindowMatrixId;
    }

    @Column(name = "SupportWindow", length = 50)
    public String getSupportWindow() {
	return this.supportWindow;
    }

    public void setSupportWindow(String supportWindow) {
	this.supportWindow = supportWindow;
    }

    @Column(name = "DerivedFactor", precision = 12, scale = 0)
    public Float getDerivedFactor() {
	return this.derivedFactor;
    }

    public void setDerivedFactor(Float derivedFactor) {
	this.derivedFactor = derivedFactor;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "supportWindowMatrix")
    public Set<SolutionL1operations> getSolutionL1operationses() {
	return this.solutionL1operationses;
    }

    public void setSolutionL1operationses(
	    Set<SolutionL1operations> solutionL1operationses) {
	this.solutionL1operationses = solutionL1operationses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "supportWindowMatrix")
    public Set<SolutionServiceDesk> getSolutionServiceDesks() {
	return this.solutionServiceDesks;
    }

    public void setSolutionServiceDesks(
	    Set<SolutionServiceDesk> solutionServiceDesks) {
	this.solutionServiceDesks = solutionServiceDesks;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "supportWindowMatrix")
    public Set<SolutionL2operations> getSolutionL2operationses() {
	return this.solutionL2operationses;
    }

    public void setSolutionL2operationses(
	    Set<SolutionL2operations> solutionL2operationses) {
	this.solutionL2operationses = solutionL2operationses;
    }

}
