package com.ericsson.mssp.common.entity;

// Generated Mar 18, 2013 3:47:44 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TestEffReduction generated by hbm2java
 */
@Entity
@Table(name = "TestEffReduction")
public class TestEffReduction implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 8032513260305939387L;
    private Integer testEffReductionId;
    private Solution solution;
    private Float secondYear;
    private Float thirdYear;
    private Float fourthYear;
    private Float fifthYear;
    private Float sixthYear;
    private Float seventhYear;

    public TestEffReduction() {
    }

    public TestEffReduction(Solution solution) {
	this.solution = solution;
    }

    public TestEffReduction(Solution solution, Float secondYear,
	    Float thirdYear, Float fourthYear, Float fifthYear,
	    Float sixthYear, Float seventhYear) {
	this.solution = solution;
	this.secondYear = secondYear;
	this.thirdYear = thirdYear;
	this.fourthYear = fourthYear;
	this.fifthYear = fifthYear;
	this.sixthYear = sixthYear;
	this.seventhYear = seventhYear;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "TestEffReductionID", unique = true, nullable = false)
    public Integer getTestEffReductionId() {
	return this.testEffReductionId;
    }

    public void setTestEffReductionId(Integer testEffReductionId) {
	this.testEffReductionId = testEffReductionId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "SolutionID", nullable = false)
    public Solution getSolution() {
	return this.solution;
    }

    public void setSolution(Solution solution) {
	this.solution = solution;
    }

    @Column(name = "SecondYear", precision = 10)
    public Float getSecondYear() {
	return this.secondYear;
    }

    public void setSecondYear(Float secondYear) {
	this.secondYear = secondYear;
    }

    @Column(name = "ThirdYear", precision = 10)
    public Float getThirdYear() {
	return this.thirdYear;
    }

    public void setThirdYear(Float thirdYear) {
	this.thirdYear = thirdYear;
    }

    @Column(name = "FourthYear", precision = 10)
    public Float getFourthYear() {
	return this.fourthYear;
    }

    public void setFourthYear(Float fourthYear) {
	this.fourthYear = fourthYear;
    }

    @Column(name = "FifthYear", precision = 10)
    public Float getFifthYear() {
	return this.fifthYear;
    }

    public void setFifthYear(Float fifthYear) {
	this.fifthYear = fifthYear;
    }

    @Column(name = "SixthYear", precision = 10)
    public Float getSixthYear() {
	return this.sixthYear;
    }

    public void setSixthYear(Float sixthYear) {
	this.sixthYear = sixthYear;
    }

    @Column(name = "SeventhYear", precision = 10)
    public Float getSeventhYear() {
	return this.seventhYear;
    }

    public void setSeventhYear(Float seventhYear) {
	this.seventhYear = seventhYear;
    }

}
