package com.ericsson.mssp.common.entity;

// Generated Feb 12, 2013 11:09:46 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TntpartitionDate generated by hbm2java
 */
@Entity
@Table(name = "TNTPartitionDate")
public class TNTPartitionDate implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1515427278248996267L;
    private Integer tNTPartitionDateID;
    private Solution solution;
    private Integer noOfPart;

    public TNTPartitionDate() {
    }

    public TNTPartitionDate(Solution solution, Integer noOfPart,
	    Date startDate, Date endDate) {
	this.solution = solution;
	this.noOfPart = noOfPart;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "TNTPartitionDateID", unique = true, nullable = false)
    public Integer getTntpartitionDateId() {
	return this.tNTPartitionDateID;
    }

    public void setTntpartitionDateId(Integer tntpartitionDateId) {
	this.tNTPartitionDateID = tntpartitionDateId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "SolutionID")
    public Solution getSolution() {
	return this.solution;
    }

    public void setSolution(Solution solution) {
	this.solution = solution;
    }

    @Column(name = "NoOfPart")
    public Integer getNoOfPart() {
	return this.noOfPart;
    }

    public void setNoOfPart(Integer noOfPart) {
	this.noOfPart = noOfPart;
    }
}
