package com.ericsson.mssp.common.entity;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WorkflowTimeline generated by hbm2java
 */
@Entity
@Table(name = "WorkflowTimeline")
public class WorkflowTimeline implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3146517135605253075L;
	private Integer workflowTimelineId;
	private Opportunity opportunity;
	private Date rfpreceiptDate;
	private Date questionnaireSubmissionDate;
	private Date solutionReviewDate;
	private Date submissionDate;
	private Date approvalDate;
	private String assignedTo;
	private String comments;

	public WorkflowTimeline() {
	}

	public WorkflowTimeline(Opportunity opportunity) {
		this.opportunity = opportunity;
	}

	public WorkflowTimeline(Opportunity opportunity, Date rfpreceiptDate,
			Date questionnaireSubmissionDate, Date solutionReviewDate,
			Date submissionDate, Date approvalDate, String assignedTo,
			String comments) {
		this.opportunity = opportunity;
		this.rfpreceiptDate = rfpreceiptDate;
		this.questionnaireSubmissionDate = questionnaireSubmissionDate;
		this.solutionReviewDate = solutionReviewDate;
		this.submissionDate = submissionDate;
		this.approvalDate = approvalDate;
		this.assignedTo = assignedTo;
		this.comments = comments;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "WorkflowTimelineID", unique = true, nullable = false)
	public Integer getWorkflowTimelineId() {
		return this.workflowTimelineId;
	}

	public void setWorkflowTimelineId(Integer workflowTimelineId) {
		this.workflowTimelineId = workflowTimelineId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OpportunityID", nullable = false)
	public Opportunity getOpportunity() {
		return this.opportunity;
	}

	public void setOpportunity(Opportunity opportunity) {
		this.opportunity = opportunity;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RFPReceiptDate", length = 19)
	public Date getRfpreceiptDate() {
		return this.rfpreceiptDate;
	}

	public void setRfpreceiptDate(Date rfpreceiptDate) {
		this.rfpreceiptDate = rfpreceiptDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "QuestionnaireSubmissionDate", length = 19)
	public Date getQuestionnaireSubmissionDate() {
		return this.questionnaireSubmissionDate;
	}

	public void setQuestionnaireSubmissionDate(Date questionnaireSubmissionDate) {
		this.questionnaireSubmissionDate = questionnaireSubmissionDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SolutionReviewDate", length = 19)
	public Date getSolutionReviewDate() {
		return this.solutionReviewDate;
	}

	public void setSolutionReviewDate(Date solutionReviewDate) {
		this.solutionReviewDate = solutionReviewDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SubmissionDate", length = 19)
	public Date getSubmissionDate() {
		return this.submissionDate;
	}

	public void setSubmissionDate(Date submissionDate) {
		this.submissionDate = submissionDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ApprovalDate", length = 19)
	public Date getApprovalDate() {
		return this.approvalDate;
	}

	public void setApprovalDate(Date approvalDate) {
		this.approvalDate = approvalDate;
	}

	@Column(name = "AssignedTo", length = 50)
	public String getAssignedTo() {
		return this.assignedTo;
	}

	public void setAssignedTo(String assignedTo) {
		this.assignedTo = assignedTo;
	}

	@Column(name = "Comments", length = 65535)
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

}
