package com.ericsson.mssp.common.entity;

// Generated Dec 11, 2012 4:20:07 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AdditionalFte generated by hbm2java
 */
@Entity
@Table(name = "AdditionalFTE")
public class AdditionalFTE implements java.io.Serializable {

    /**
	 * 
	 */
    private static final long serialVersionUID = 7758833837795211562L;
    private Integer additionalFteid;
    private Solution solution;
    private Integer opportunityScopeId;
    //private Integer jobRoleStageID;
    private JobRoleStages jobRoleStageID;
    private String location;
    private Date fromMonthYear;
    private Date toMonthYear;
    private Float noofFte;
    private String subLocation;

    public AdditionalFTE() {
    }

    public AdditionalFTE(Solution solution) {
	this.solution = solution;
    }

    public AdditionalFTE(Solution solution, Integer opportunityScopeId,
    		JobRoleStages jobRoleStageID, String location, Date fromMonthYear,
	    Date toMonthYear, Float noofFte) {
	this.solution = solution;
	this.opportunityScopeId = opportunityScopeId;
	this.jobRoleStageID = jobRoleStageID;
	this.location = location;
	this.fromMonthYear = fromMonthYear;
	this.toMonthYear = toMonthYear;
	this.noofFte = noofFte;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "AdditionalFTEID", unique = true, nullable = false)
    public Integer getAdditionalFteid() {
	return this.additionalFteid;
    }

    public void setAdditionalFteid(Integer additionalFteid) {
	this.additionalFteid = additionalFteid;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "SolutionID", nullable = false)
    public Solution getSolution() {
	return this.solution;
    }

    public void setSolution(Solution solution) {
	this.solution = solution;
    }

    @Column(name = "OpportunityScopeID")
    public Integer getOpportunityScopeId() {
	return this.opportunityScopeId;
    }

    public void setOpportunityScopeId(Integer opportunityScopeId) {
	this.opportunityScopeId = opportunityScopeId;
    }

    @ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "JobRoleStageID", nullable = false)
    public JobRoleStages getJobRoleStageID() {
	return this.jobRoleStageID;
    }

    public void setJobRoleStageID(JobRoleStages jobRoleStageID) {
	this.jobRoleStageID = jobRoleStageID;
    }

    @Column(name = "Location", length = 20)
    public String getLocation() {
	return this.location;
    }

    public void setLocation(String location) {
	this.location = location;
    }

    @Column(name = "FromMonthYear")
    public Date getFromMonthYear() {
	return this.fromMonthYear;
    }

    public void setFromMonthYear(Date fromMonthYear) {
	this.fromMonthYear = fromMonthYear;
    }

    @Column(name = "ToMonthYear")
    public Date getToMonthYear() {
	return this.toMonthYear;
    }

    public void setToMonthYear(Date toMonthYear) {
	this.toMonthYear = toMonthYear;
    }

    @Column(name = "NoofFTE", precision = 10)
    public Float getNoofFte() {
	return this.noofFte;
    }

    public void setNoofFte(Float noofFte) {
	this.noofFte = noofFte;
    }

    @Column(name = "SubLocation", length = 50)
	public String getSubLocation() {
		return subLocation;
	}

	public void setSubLocation(String subLocation) {
		this.subLocation = subLocation;
	}

}
