package com.ericsson.mssp.common.entity;

// Generated Mar 18, 2013 3:47:44 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Apaweightage generated by hbm2java
 */
@Entity
@Table(name = "APAWeightage")
public class Apaweightage implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 5249210929630130207L;
    private Integer apaweightageId;
    private Solution solution;
    private Integer businessCriticalilty;
    private Integer levelofDocuments;
    private Integer stability;
    private Integer longivity;
    private Integer complexity;

    public Apaweightage() {
    }

    public Apaweightage(Solution solution) {
	this.solution = solution;
    }

    public Apaweightage(Solution solution, Integer businessCriticalilty,
	    Integer levelofDocuments, Integer stability, Integer longivity,
	    Integer complexity) {
	this.solution = solution;
	this.businessCriticalilty = businessCriticalilty;
	this.levelofDocuments = levelofDocuments;
	this.stability = stability;
	this.longivity = longivity;
	this.complexity = complexity;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "APAWeightageID", unique = true, nullable = false)
    public Integer getApaweightageId() {
	return this.apaweightageId;
    }

    public void setApaweightageId(Integer apaweightageId) {
	this.apaweightageId = apaweightageId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "SolutionID", nullable = false)
    public Solution getSolution() {
	return this.solution;
    }

    public void setSolution(Solution solution) {
	this.solution = solution;
    }

    @Column(name = "BusinessCriticalilty")
    public Integer getBusinessCriticalilty() {
	return this.businessCriticalilty;
    }

    public void setBusinessCriticalilty(Integer businessCriticalilty) {
	this.businessCriticalilty = businessCriticalilty;
    }

    @Column(name = "LevelofDocuments")
    public Integer getLevelofDocuments() {
	return this.levelofDocuments;
    }

    public void setLevelofDocuments(Integer levelofDocuments) {
	this.levelofDocuments = levelofDocuments;
    }

    @Column(name = "Stability")
    public Integer getStability() {
	return this.stability;
    }

    public void setStability(Integer stability) {
	this.stability = stability;
    }

    @Column(name = "Longivity")
    public Integer getLongivity() {
	return this.longivity;
    }

    public void setLongivity(Integer longivity) {
	this.longivity = longivity;
    }

    @Column(name = "Complexity")
    public Integer getComplexity() {
	return this.complexity;
    }

    public void setComplexity(Integer complexity) {
	this.complexity = complexity;
    }

}
