package com.ericsson.mssp.common.entity;

//Generated May 22, 2014 11:53:09 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
* AvailabilityManagement generated by hbm2java
*/
@Entity
@Table(name = "AvailabilityManagement")
@NamedQueries({
	@NamedQuery(
	name = "get.availabilityManagement.bySolutionID",
	query = "from AvailabilityManagement where solutionId = ?"
	)
})
public class AvailabilityManagement implements java.io.Serializable {

/**
* 
*/
private static final long serialVersionUID = -7676448561170657940L;
private Integer availabilityManagementID;
private Solution solution;
private OpportunityScope opportunityScope;
private float manageAvailability;
private float manageOutageAndRisks;
private float fteAvailabilityManagement;



@Id
@GeneratedValue(strategy = IDENTITY)
@Column(name = "AvailabilityManagementID", unique = true, nullable = false)
public Integer getAvailabilityManagementID() {
	return this.availabilityManagementID;
}

public void setAvailabilityManagementID(Integer availabilityManagementID) {
	this.availabilityManagementID = availabilityManagementID;
}

@ManyToOne(fetch = FetchType.LAZY)
@JoinColumn(name = "SolutionID", nullable = false)
public Solution getSolution() {
	return this.solution;
}

public void setSolution(Solution solution) {
	this.solution = solution;
}


@ManyToOne(fetch = FetchType.LAZY)
@JoinColumn(name = "OpportunityScopeID")
	public OpportunityScope getOpportunityScope() {
		return opportunityScope;
	}


	public void setOpportunityScope(OpportunityScope opportunityScope) {
		this.opportunityScope = opportunityScope;
	}

	@Column(name="ManageAvailability")
	public float getManageAvailability() {
		return manageAvailability;
	}

	public void setManageAvailability(float manageAvailability) {
		this.manageAvailability = manageAvailability;
	}

	@Column(name="ManageOutageAndRisks")
	public float getManageOutageAndRisks() {
		return manageOutageAndRisks;
	}

	public void setManageOutageAndRisks(float manageOutageAndRisks) {
		this.manageOutageAndRisks = manageOutageAndRisks;
	}

	@Column(name="FteAvailabilityManagement")
	public float getFteAvailabilityManagement() {
		return fteAvailabilityManagement;
	}

	public void setFteAvailabilityManagement(float fteAvailabilityManagement) {
		this.fteAvailabilityManagement = fteAvailabilityManagement;
	}
	
	

}


