package com.ericsson.mssp.common.entity;
// Generated Dec 11, 2012 4:20:07 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CostSummary generated by hbm2java
 */
@Entity
@Table(name = "CostSummary")
public class CostSummary implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2045463957063844519L;
	private Integer costSummaryId;
	private OpportunityScope opportunityScope;
	private Integer jobeRoleId;
	private String location;
	private Float costInr;

	public CostSummary() {
	}

	public CostSummary(OpportunityScope opportunityScope) {
		this.opportunityScope = opportunityScope;
	}

	public CostSummary(OpportunityScope opportunityScope, Integer jobeRoleId,
			String location, Float costInr) {
		this.opportunityScope = opportunityScope;
		this.jobeRoleId = jobeRoleId;
		this.location = location;
		this.costInr = costInr;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "CostSummaryID", unique = true, nullable = false)
	public Integer getCostSummaryId() {
		return this.costSummaryId;
	}

	public void setCostSummaryId(Integer costSummaryId) {
		this.costSummaryId = costSummaryId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OpportunityScopeID", nullable = false)
	public OpportunityScope getOpportunityScope() {
		return this.opportunityScope;
	}

	public void setOpportunityScope(OpportunityScope opportunityScope) {
		this.opportunityScope = opportunityScope;
	}

	@Column(name = "JobeRoleID")
	public Integer getJobeRoleId() {
		return this.jobeRoleId;
	}

	public void setJobeRoleId(Integer jobeRoleId) {
		this.jobeRoleId = jobeRoleId;
	}

	@Column(name = "Location", length = 20)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "CostINR", precision = 10)
	public Float getCostInr() {
		return this.costInr;
	}

	public void setCostInr(Float costInr) {
		this.costInr = costInr;
	}

}
