package com.ericsson.mssp.common.entity;
// Generated Dec 11, 2012 4:20:07 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ftestaging generated by hbm2java
 */
@Entity
@Table(name = "FTEStaging")
public class FTEStaging implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 310352833817600413L;
	private Long ftestagingId;
	private Solution solution;
	private OpportunityScope opportunityScope;
	private JobRoleStages jobRoleStage;
	private Date monthYear;
	private String location;
	private Float ftecount;
	private String subLocation;

	public FTEStaging() {
	}

	public FTEStaging(Solution solution, OpportunityScope opportunityScope,
			JobRoleStages jobRoleStage) {
		this.solution = solution;
		this.opportunityScope = opportunityScope;
		this.jobRoleStage = jobRoleStage;
	}

	public FTEStaging(Solution solution, OpportunityScope opportunityScope,
			JobRoleStages jobRoleStage, Date monthYear, String location, Float ftecount) {
		this.solution = solution;
		this.opportunityScope = opportunityScope;
		this.jobRoleStage = jobRoleStage;
		this.monthYear = monthYear;
		this.location = location;
		this.ftecount = ftecount;
	}

	public FTEStaging(Solution solution, OpportunityScope opportunityScope,
			JobRoleStages jobRoleStage, Date monthYear, String location, Float ftecount, String subLocation) {
		this.solution = solution;
		this.opportunityScope = opportunityScope;
		this.jobRoleStage = jobRoleStage;
		this.monthYear = monthYear;
		this.location = location;
		this.ftecount = ftecount;
		this.subLocation = subLocation;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "FTEStagingID", unique = true, nullable = false)
	public Long getFtestagingId() {
		return this.ftestagingId;
	}

	public void setFtestagingId(Long ftestagingId) {
		this.ftestagingId = ftestagingId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "SolutionID", nullable = false)
	public Solution getSolution() {
		return this.solution;
	}

	public void setSolution(Solution solution) {
		this.solution = solution;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "OpportunityScopeID", nullable = false)
	public OpportunityScope getOpportunityScope() {
		return this.opportunityScope;
	}

	public void setOpportunityScope(OpportunityScope opportunityScope) {
		this.opportunityScope = opportunityScope;
	}

	/*@ManyToOne(fetch = FetchType.LAZY)*/
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "JobRoleStageID", nullable = false)
	public JobRoleStages getJobRoleStage() {
		return this.jobRoleStage;
	}

	public void setJobRoleStage(JobRoleStages jobRoleStage) {
		this.jobRoleStage = jobRoleStage;
	}

	@Column(name = "MonthYear")
	public Date getMonthYear() {
		return this.monthYear;
	}

	public void setMonthYear(Date monthYear) {
		this.monthYear = monthYear;
	}

	@Column(name = "Location", length = 20)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "FTECount", precision = 10)
	public Float getFtecount() {
		return this.ftecount;
	}

	public void setFtecount(Float ftecount) {
		this.ftecount = ftecount;
	}


	@Column(name = "SubLocation", length = 50)
	public String getSubLocation() {
		return subLocation;
	}

	public void setSubLocation(String subLocation) {
		this.subLocation = subLocation;
	}

}
