package com.ericsson.mssp.common.entity;

// Generated Mar 12, 2013 8:53:41 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * GenericTestingInputs generated by hbm2java
 */
@Entity
@Table(name = "GenericTestingInputs")
public class GenericTestingInputs implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 6416328811717794089L;
    private Integer genericTestingInputsId;
    private Solution solution;
    private String complexity;
    private Float ratio;
    private Float testDesignProductivity;
    private Float testExecutionProductivity;
    private Float automationProductivity;

    public GenericTestingInputs() {
    }

    public GenericTestingInputs(Solution solution, String complexity,
	    Float ratio, Float testDesignProductivity,
	    Float testExecutionProductivity, Float automationProductivity) {
	this.solution = solution;
	this.complexity = complexity;
	this.ratio = ratio;
	this.testDesignProductivity = testDesignProductivity;
	this.testExecutionProductivity = testExecutionProductivity;
	this.automationProductivity = automationProductivity;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "GenericTestingInputsID", unique = true, nullable = false)
    public Integer getGenericTestingInputsId() {
	return this.genericTestingInputsId;
    }

    public void setGenericTestingInputsId(Integer genericTestingInputsId) {
	this.genericTestingInputsId = genericTestingInputsId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "SolutionID")
    public Solution getSolution() {
	return this.solution;
    }

    public void setSolution(Solution solution) {
	this.solution = solution;
    }

    @Column(name = "Complexity", length = 10)
    public String getComplexity() {
	return this.complexity;
    }

    public void setComplexity(String complexity) {
	this.complexity = complexity;
    }

    @Column(name = "Ratio", precision = 10)
    public Float getRatio() {
	return this.ratio;
    }

    public void setRatio(Float ratio) {
	this.ratio = ratio;
    }

    @Column(name = "TestDesignProductivity", precision = 10)
    public Float getTestDesignProductivity() {
	return this.testDesignProductivity;
    }

    public void setTestDesignProductivity(Float testDesignProductivity) {
	this.testDesignProductivity = testDesignProductivity;
    }

    @Column(name = "TestExecutionProductivity", precision = 10)
    public Float getTestExecutionProductivity() {
	return this.testExecutionProductivity;
    }

    public void setTestExecutionProductivity(Float testExecutionProductivity) {
	this.testExecutionProductivity = testExecutionProductivity;
    }

    @Column(name = "AutomationProductivity", precision = 10)
    public Float getAutomationProductivity() {
	return this.automationProductivity;
    }

    public void setAutomationProductivity(Float automationProductivity) {
	this.automationProductivity = automationProductivity;
    }

}
