package com.ericsson.mssp.common.entity;

// Generated Mar 12, 2013 8:53:41 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * GenericTestingOverhead generated by hbm2java
 */
@Entity
@Table(name = "GenericTestingOverhead")
public class GenericTestingOverhead implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = -2629659978044739284L;
    private Integer genericTestingOverheadId;
    private Solution solution;
    private Float testMgmtEffort;
    private Float ratpeffort;
    private Float automationExecEffort;
    private Float automationMaintEffort;

    public GenericTestingOverhead() {
    }

    public GenericTestingOverhead(Solution solution, Float testMgmtEffort,
	    Float ratpeffort, Float automationExecEffort,
	    Float automationMaintEffort) {
	this.solution = solution;
	this.testMgmtEffort = testMgmtEffort;
	this.ratpeffort = ratpeffort;
	this.automationExecEffort = automationExecEffort;
	this.automationMaintEffort = automationMaintEffort;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "GenericTestingOverheadID", unique = true, nullable = false)
    public Integer getGenericTestingOverheadId() {
	return this.genericTestingOverheadId;
    }

    public void setGenericTestingOverheadId(Integer genericTestingOverheadId) {
	this.genericTestingOverheadId = genericTestingOverheadId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "SolutionID")
    public Solution getSolution() {
	return this.solution;
    }

    public void setSolution(Solution solution) {
	this.solution = solution;
    }

    @Column(name = "TestMgmtEffort", precision = 10)
    public Float getTestMgmtEffort() {
	return this.testMgmtEffort;
    }

    public void setTestMgmtEffort(Float testMgmtEffort) {
	this.testMgmtEffort = testMgmtEffort;
    }

    @Column(name = "RATPEffort", precision = 10)
    public Float getRatpeffort() {
	return this.ratpeffort;
    }

    public void setRatpeffort(Float ratpeffort) {
	this.ratpeffort = ratpeffort;
    }

    @Column(name = "AutomationExecEffort", precision = 10)
    public Float getAutomationExecEffort() {
	return this.automationExecEffort;
    }

    public void setAutomationExecEffort(Float automationExecEffort) {
	this.automationExecEffort = automationExecEffort;
    }

    @Column(name = "AutomationMaintEffort", precision = 10)
    public Float getAutomationMaintEffort() {
	return this.automationMaintEffort;
    }

    public void setAutomationMaintEffort(Float automationMaintEffort) {
	this.automationMaintEffort = automationMaintEffort;
    }

}
