package com.ericsson.mssp.common.entity;

// Generated Mar 13, 2013 1:33:14 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * InputVolumetricsDefinedBy generated by hbm2java
 */
@Entity
@Table(name = "InputVolumetricsDefinedBy")
public class InputVolumetricsDefinedBy implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = -1338302552310140687L;
    private Integer inputVolumetricsDefinedById;
    private String name;
    private String description;
   
    public InputVolumetricsDefinedBy() {
    }

    public InputVolumetricsDefinedBy(String name, String description,
	    Set<OpportunityDetail> opportunityDetails) {
	this.name = name;
	this.description = description;
	 }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "InputVolumetricsDefinedByID", unique = true, nullable = false)
    public Integer getInputVolumetricsDefinedById() {
	return this.inputVolumetricsDefinedById;
    }

    public void setInputVolumetricsDefinedById(
	    Integer inputVolumetricsDefinedById) {
	this.inputVolumetricsDefinedById = inputVolumetricsDefinedById;
    }

    @Column(name = "Name", length = 30)
    public String getName() {
	return this.name;
    }

    public void setName(String name) {
	this.name = name;
    }

    @Column(name = "Description", length = 50)
    public String getDescription() {
	return this.description;
    }

    public void setDescription(String description) {
	this.description = description;
    }
}
