package com.ericsson.mssp.common.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * NonLabourCost generated by hbm2java
 */
@Entity
@Table(name = "NonLabourCost")
public class NonLabourCost implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2713345683850171969L;
	private Integer nonlabourCostId;
	private Solution solution;
	private Integer year;
	private Integer itnoofTravels;
	private Integer itstayDuration;
	private Integer itshortVisaCost;
	private Integer ittickectCost;
	private Integer itdailyPerDiem;
	private Integer ithotelCostPerNight;
	private Integer itconveyancePerDay;
	private Integer dtnoofTravels;
	private Integer dtstayDuration;
	private Integer dttickectCost;
	private Integer dtdailyPerDiem;
	private Integer dthotelCostPerNight;
	private Integer dtconveyancePerDay;
	private Integer egiconnectivityCost;
	private Integer gscconnectivityCost;
	private Integer otherConnectivityCost;
	private Integer monthlyNightAllowance;
	private Integer pcpeopleAtNight;
	private Integer monthlyWeekendAllowance;
	private Integer pcpeopleAtWeekend;
	private Integer monthMobileCost;
	private Integer monthlyDataCardCost;
	private Integer hwsw3ppcost;
	private Integer trainingCost;
	private Integer otherCost;

	public NonLabourCost() {
	}

	public NonLabourCost(Solution solution) {
		this.solution = solution;
	}

	public NonLabourCost(Solution solution, Integer year,
			Integer itnoofTravels, Integer itstayDuration,
			Integer itshortVisaCost, Integer ittickectCost,
			Integer itdailyPerDiem, Integer ithotelCostPerNight,
			Integer itconveyancePerDay, Integer dtnoofTravels,
			Integer dtstayDuration, Integer dttickectCost,
			Integer dtdailyPerDiem, Integer dthotelCostPerNight,
			Integer dtconveyancePerDay, Integer egiconnectivityCost,
			Integer gscconnectivityCost, Integer otherConnectivityCost,
			Integer monthlyNightAllowance, Integer pcpeopleAtNight,
			Integer monthlyWeekendAllowance, Integer pcpeopleAtWeekend,
			Integer monthMobileCost, Integer monthlyDataCardCost,
			Integer hwsw3ppcost, Integer trainingCost, Integer otherCost) {
		this.solution = solution;
		this.year = year;
		this.itnoofTravels = itnoofTravels;
		this.itstayDuration = itstayDuration;
		this.itshortVisaCost = itshortVisaCost;
		this.ittickectCost = ittickectCost;
		this.itdailyPerDiem = itdailyPerDiem;
		this.ithotelCostPerNight = ithotelCostPerNight;
		this.itconveyancePerDay = itconveyancePerDay;
		this.dtnoofTravels = dtnoofTravels;
		this.dtstayDuration = dtstayDuration;
		this.dttickectCost = dttickectCost;
		this.dtdailyPerDiem = dtdailyPerDiem;
		this.dthotelCostPerNight = dthotelCostPerNight;
		this.dtconveyancePerDay = dtconveyancePerDay;
		this.egiconnectivityCost = egiconnectivityCost;
		this.gscconnectivityCost = gscconnectivityCost;
		this.otherConnectivityCost = otherConnectivityCost;
		this.monthlyNightAllowance = monthlyNightAllowance;
		this.pcpeopleAtNight = pcpeopleAtNight;
		this.monthlyWeekendAllowance = monthlyWeekendAllowance;
		this.pcpeopleAtWeekend = pcpeopleAtWeekend;
		this.monthMobileCost = monthMobileCost;
		this.monthlyDataCardCost = monthlyDataCardCost;
		this.hwsw3ppcost = hwsw3ppcost;
		this.trainingCost = trainingCost;
		this.otherCost = otherCost;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "NonlabourCostID", unique = true, nullable = false)
	public Integer getNonlabourCostId() {
		return this.nonlabourCostId;
	}

	public void setNonlabourCostId(Integer nonlabourCostId) {
		this.nonlabourCostId = nonlabourCostId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SolutionID", nullable = false)
	public Solution getSolution() {
		return this.solution;
	}

	public void setSolution(Solution solution) {
		this.solution = solution;
	}

	@Column(name = "Year")
	public Integer getYear() {
		return this.year;
	}

	public void setYear(Integer year) {
		this.year = year;
	}

	@Column(name = "ITNoofTravels")
	public Integer getItnoofTravels() {
		return this.itnoofTravels;
	}

	public void setItnoofTravels(Integer itnoofTravels) {
		this.itnoofTravels = itnoofTravels;
	}

	@Column(name = "ITStayDuration")
	public Integer getItstayDuration() {
		return this.itstayDuration;
	}

	public void setItstayDuration(Integer itstayDuration) {
		this.itstayDuration = itstayDuration;
	}

	@Column(name = "ITShortVisaCost")
	public Integer getItshortVisaCost() {
		return this.itshortVisaCost;
	}

	public void setItshortVisaCost(Integer itshortVisaCost) {
		this.itshortVisaCost = itshortVisaCost;
	}

	@Column(name = "ITTickectCost")
	public Integer getIttickectCost() {
		return this.ittickectCost;
	}

	public void setIttickectCost(Integer ittickectCost) {
		this.ittickectCost = ittickectCost;
	}

	@Column(name = "ITDailyPerDiem")
	public Integer getItdailyPerDiem() {
		return this.itdailyPerDiem;
	}

	public void setItdailyPerDiem(Integer itdailyPerDiem) {
		this.itdailyPerDiem = itdailyPerDiem;
	}

	@Column(name = "ITHotelCostPerNight")
	public Integer getIthotelCostPerNight() {
		return this.ithotelCostPerNight;
	}

	public void setIthotelCostPerNight(Integer ithotelCostPerNight) {
		this.ithotelCostPerNight = ithotelCostPerNight;
	}

	@Column(name = "ITConveyancePerDay")
	public Integer getItconveyancePerDay() {
		return this.itconveyancePerDay;
	}

	public void setItconveyancePerDay(Integer itconveyancePerDay) {
		this.itconveyancePerDay = itconveyancePerDay;
	}

	@Column(name = "DTNoofTravels")
	public Integer getDtnoofTravels() {
		return this.dtnoofTravels;
	}

	public void setDtnoofTravels(Integer dtnoofTravels) {
		this.dtnoofTravels = dtnoofTravels;
	}

	@Column(name = "DTStayDuration")
	public Integer getDtstayDuration() {
		return this.dtstayDuration;
	}

	public void setDtstayDuration(Integer dtstayDuration) {
		this.dtstayDuration = dtstayDuration;
	}

	@Column(name = "DTTickectCost")
	public Integer getDttickectCost() {
		return this.dttickectCost;
	}

	public void setDttickectCost(Integer dttickectCost) {
		this.dttickectCost = dttickectCost;
	}

	@Column(name = "DTDailyPerDiem")
	public Integer getDtdailyPerDiem() {
		return this.dtdailyPerDiem;
	}

	public void setDtdailyPerDiem(Integer dtdailyPerDiem) {
		this.dtdailyPerDiem = dtdailyPerDiem;
	}

	@Column(name = "DTHotelCostPerNight")
	public Integer getDthotelCostPerNight() {
		return this.dthotelCostPerNight;
	}

	public void setDthotelCostPerNight(Integer dthotelCostPerNight) {
		this.dthotelCostPerNight = dthotelCostPerNight;
	}

	@Column(name = "DTConveyancePerDay")
	public Integer getDtconveyancePerDay() {
		return this.dtconveyancePerDay;
	}

	public void setDtconveyancePerDay(Integer dtconveyancePerDay) {
		this.dtconveyancePerDay = dtconveyancePerDay;
	}

	@Column(name = "EGIConnectivityCost")
	public Integer getEgiconnectivityCost() {
		return this.egiconnectivityCost;
	}

	public void setEgiconnectivityCost(Integer egiconnectivityCost) {
		this.egiconnectivityCost = egiconnectivityCost;
	}

	@Column(name = "GSCConnectivityCost")
	public Integer getGscconnectivityCost() {
		return this.gscconnectivityCost;
	}

	public void setGscconnectivityCost(Integer gscconnectivityCost) {
		this.gscconnectivityCost = gscconnectivityCost;
	}

	@Column(name = "OtherConnectivityCost")
	public Integer getOtherConnectivityCost() {
		return this.otherConnectivityCost;
	}

	public void setOtherConnectivityCost(Integer otherConnectivityCost) {
		this.otherConnectivityCost = otherConnectivityCost;
	}

	@Column(name = "MonthlyNightAllowance")
	public Integer getMonthlyNightAllowance() {
		return this.monthlyNightAllowance;
	}

	public void setMonthlyNightAllowance(Integer monthlyNightAllowance) {
		this.monthlyNightAllowance = monthlyNightAllowance;
	}

	@Column(name = "PCPeopleAtNight")
	public Integer getPcpeopleAtNight() {
		return this.pcpeopleAtNight;
	}

	public void setPcpeopleAtNight(Integer pcpeopleAtNight) {
		this.pcpeopleAtNight = pcpeopleAtNight;
	}

	@Column(name = "MonthlyWeekendAllowance")
	public Integer getMonthlyWeekendAllowance() {
		return this.monthlyWeekendAllowance;
	}

	public void setMonthlyWeekendAllowance(Integer monthlyWeekendAllowance) {
		this.monthlyWeekendAllowance = monthlyWeekendAllowance;
	}

	@Column(name = "PCPeopleAtWeekend")
	public Integer getPcpeopleAtWeekend() {
		return this.pcpeopleAtWeekend;
	}

	public void setPcpeopleAtWeekend(Integer pcpeopleAtWeekend) {
		this.pcpeopleAtWeekend = pcpeopleAtWeekend;
	}

	@Column(name = "MonthMobileCost")
	public Integer getMonthMobileCost() {
		return this.monthMobileCost;
	}

	public void setMonthMobileCost(Integer monthMobileCost) {
		this.monthMobileCost = monthMobileCost;
	}

	@Column(name = "MonthlyDataCardCost")
	public Integer getMonthlyDataCardCost() {
		return this.monthlyDataCardCost;
	}

	public void setMonthlyDataCardCost(Integer monthlyDataCardCost) {
		this.monthlyDataCardCost = monthlyDataCardCost;
	}

	@Column(name = "HWSW3PPCost")
	public Integer getHwsw3ppcost() {
		return this.hwsw3ppcost;
	}

	public void setHwsw3ppcost(Integer hwsw3ppcost) {
		this.hwsw3ppcost = hwsw3ppcost;
	}

	@Column(name = "TrainingCost")
	public Integer getTrainingCost() {
		return this.trainingCost;
	}

	public void setTrainingCost(Integer trainingCost) {
		this.trainingCost = trainingCost;
	}

	@Column(name = "OtherCost")
	public Integer getOtherCost() {
		return this.otherCost;
	}

	public void setOtherCost(Integer otherCost) {
		this.otherCost = otherCost;
	}

}
