package com.ericsson.mssp.common.entity;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OpportunityLocation generated by hbm2java
 */
@Entity
@Table(name = "OpportunityLocation")
public class OpportunityLocation implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8063714741926968122L;
	private Integer opportunityLocationId;
	private OpportunityDetail opportunityDetail;
	private Integer customerCountry;
	private Integer nearShore;
	private Integer gsc1;
	private Integer gsc2;

	public OpportunityLocation() {
	}

	public OpportunityLocation(OpportunityDetail opportunityDetail) {
		this.opportunityDetail = opportunityDetail;
	}

	public OpportunityLocation(OpportunityDetail opportunityDetail,
			Integer customerCountry, Integer nearShore, Integer gsc1, Integer gsc2) {
		this.opportunityDetail = opportunityDetail;
		this.customerCountry = customerCountry;
		this.nearShore = nearShore;
		this.gsc1 = gsc1;
		this.gsc2 = gsc2;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "OpportunityLocationID", unique = true, nullable = false)
	public Integer getOpportunityLocationId() {
		return this.opportunityLocationId;
	}

	public void setOpportunityLocationId(Integer opportunityLocationId) {
		this.opportunityLocationId = opportunityLocationId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OpportunityDetailID", nullable = false)
	public OpportunityDetail getOpportunityDetail() {
		return this.opportunityDetail;
	}

	public void setOpportunityDetail(OpportunityDetail opportunityDetail) {
		this.opportunityDetail = opportunityDetail;
	}

	@Column(name = "CustomerCountry", length = 50)
	public Integer getCustomerCountry() {
		return this.customerCountry;
	}

	public void setCustomerCountry(Integer customerCountry) {
		this.customerCountry = customerCountry;
	}

	@Column(name = "NearShore", length = 50)
	public Integer getNearShore() {
		return this.nearShore;
	}

	public void setNearShore(Integer nearShore) {
		this.nearShore = nearShore;
	}

	@Column(name = "GSC1", length = 50)
	public Integer getGsc1() {
		return this.gsc1;
	}

	public void setGsc1(Integer gsc1) {
		this.gsc1 = gsc1;
	}

	@Column(name = "GSC2", length = 50)
	public Integer getGsc2() {
		return this.gsc2;
	}

	public void setGsc2(Integer gsc2) {
		this.gsc2 = gsc2;
	}

}
