package com.ericsson.mssp.common.entity;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OtherDefaults generated by hbm2java
 */
@Entity
@Table(name = "OtherDefaults")
public class OtherDefaults implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1310931066065548566L;
	private Integer otherDefaultsId;
	private String applicationArea;
	private String otherFieldsName;
	private String defaultValues;
	private String createdBy;
	private Date createdTimestamp;
	private String updatedBy;
	private Date updatedTimestamp;
	private Integer serviceScopeID;

	public OtherDefaults() {
	}

	public OtherDefaults(String applicationArea, String otherFieldsName,
			String defaultValues, String createdBy, Date createdTimestamp,
			String updatedBy, Date updatedTimestamp) {
		this.applicationArea = applicationArea;
		this.otherFieldsName = otherFieldsName;
		this.defaultValues = defaultValues;
		this.createdBy = createdBy;
		this.createdTimestamp = createdTimestamp;
		this.updatedBy = updatedBy;
		this.updatedTimestamp = updatedTimestamp;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "OtherDefaultsID", unique = true, nullable = false)
	public Integer getOtherDefaultsId() {
		return this.otherDefaultsId;
	}

	public void setOtherDefaultsId(Integer otherDefaultsId) {
		this.otherDefaultsId = otherDefaultsId;
	}

	@Column(name = "ApplicationArea", length = 50)
	public String getApplicationArea() {
		return this.applicationArea;
	}

	public void setApplicationArea(String applicationArea) {
		this.applicationArea = applicationArea;
	}

	@Column(name = "OtherFieldsName", length = 50)
	public String getOtherFieldsName() {
		return this.otherFieldsName;
	}

	public void setOtherFieldsName(String otherFieldsName) {
		this.otherFieldsName = otherFieldsName;
	}

	@Column(name = "DefaultValues", length = 50)
	public String getDefaultValues() {
		return this.defaultValues;
	}

	public void setDefaultValues(String defaultValues) {
		this.defaultValues = defaultValues;
	}

	@Column(name = "CreatedBy", length = 50)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedTimestamp", length = 19)
	public Date getCreatedTimestamp() {
		return this.createdTimestamp;
	}

	public void setCreatedTimestamp(Date createdTimestamp) {
		this.createdTimestamp = createdTimestamp;
	}

	@Column(name = "UpdatedBy", length = 50)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UpdatedTimestamp", length = 19)
	public Date getUpdatedTimestamp() {
		return this.updatedTimestamp;
	}

	public void setUpdatedTimestamp(Date updatedTimestamp) {
		this.updatedTimestamp = updatedTimestamp;
	}
	
	@Column(name="ServiceScopeID")
	public Integer getServiceScopeID() {
		return serviceScopeID;
	}

	public void setServiceScopeID(Integer serviceScopeID) {
		this.serviceScopeID = serviceScopeID;
	}
	
	

}
