package com.ericsson.mssp.common.entity;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RateCard generated by hbm2java
 */
@Entity
@Table(name = "RateCardHistory")
public class RateCardHistory implements java.io.Serializable {




	/**
	 * 
	 */
	private static final long serialVersionUID = -6895894001339863033L;
	
	private Double 			rate;
	private Country 		country;
	private String 			location;
	private Integer 		rateCardHistoryId;
	private Date			createdTimestamp;
	private Date 			updatedTimestamp;
	private JobRoleStages 	jobRoleStages;
	private String 			gsc;
	private String 			subLocation;
	private String			statusFlag;
	
	

	public RateCardHistory() {
	}

	
	public RateCardHistory(String location, Double rate,
			Date updatedTimestamp,String gsc,String subLocation, Date createdTimestamp) {
		this.location = location;
		this.rate = rate;
		this.updatedTimestamp = updatedTimestamp;
		this.createdTimestamp = createdTimestamp;
		this.gsc = gsc;
		this.subLocation = subLocation;
	}

	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "RateCardHistoryID", unique = true, nullable = false)
	public Integer getRateCardHistoryId() {
		return rateCardHistoryId;
	}


	public void setRateCardHistoryId(Integer rateCardHistoryId) {
		this.rateCardHistoryId = rateCardHistoryId;
	}
	
	@OneToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "JobRoleStageID", nullable = false)
	public JobRoleStages getJobRoleStages() {
		return jobRoleStages;
	}

	public void setJobRoleStages(JobRoleStages jobRoleStages) {
		this.jobRoleStages = jobRoleStages;
	}

	@Column(name = "Location", length = 50)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@OneToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CountryID", nullable = false)
	public Country getCountry() {
		return country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	

	@Column(name = "Rate", precision = 16, scale = 4)
	public Double getRate() {
		return this.rate;
	}

	public void setRate(Double rate) {
		this.rate = rate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UpdatedTimestamp", length = 19)
	public Date getUpdatedTimestamp() {
		return this.updatedTimestamp;
	}

	public void setUpdatedTimestamp(Date updatedTimestamp) {
		this.updatedTimestamp = updatedTimestamp;
	}

	@Column(name = "Gsc", length = 10)
	public String getGsc() {
		return gsc;
	}


	public void setGsc(String gsc) {
		this.gsc = gsc;
	}


	@Column(name = "SubLocation", length = 30)
	public String getSubLocation() {
		return subLocation;
	}


	public void setSubLocation(String subLocation) {
		this.subLocation = subLocation;
	}

	@Column(name = "StatusFlag", length = 1)
	public String getStatusFlag() {
		return statusFlag;
	}

	public void setStatusFlag(String statusFlag) {
		this.statusFlag = statusFlag;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedTimestamp", length = 19)
	public Date getCreatedTimestamp() {
		return createdTimestamp;
	}


	public void setCreatedTimestamp(Date createdTimestamp) {
		this.createdTimestamp = createdTimestamp;
	}

}

