package com.ericsson.mssp.common.entity;

// Generated Mar 12, 2013 8:53:41 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RegressionLever generated by hbm2java
 */
@Entity
@Table(name = "RegressionLever")
public class RegressionLever implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = -5826406684383260032L;
    private Integer regressionLeverId;
    private Solution solution;
    private Float pcregression;
    private Float pcnewFunctionality;
    private Float pcautomatedRegression;

    public RegressionLever() {
    }

    public RegressionLever(Solution solution, Float pcregression,
	    Float pcnewFunctionality, Float pcautomatedRegression) {
	this.solution = solution;
	this.pcregression = pcregression;
	this.pcnewFunctionality = pcnewFunctionality;
	this.pcautomatedRegression = pcautomatedRegression;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "RegressionLeverID", unique = true, nullable = false)
    public Integer getRegressionLeverId() {
	return this.regressionLeverId;
    }

    public void setRegressionLeverId(Integer regressionLeverId) {
	this.regressionLeverId = regressionLeverId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "SolutionID")
    public Solution getSolution() {
	return this.solution;
    }

    public void setSolution(Solution solution) {
	this.solution = solution;
    }

    @Column(name = "PCRegression", precision = 10)
    public Float getPcregression() {
	return this.pcregression;
    }

    public void setPcregression(Float pcregression) {
	this.pcregression = pcregression;
    }

    @Column(name = "PCNewFunctionality", precision = 10)
    public Float getPcnewFunctionality() {
	return this.pcnewFunctionality;
    }

    public void setPcnewFunctionality(Float pcnewFunctionality) {
	this.pcnewFunctionality = pcnewFunctionality;
    }

    @Column(name = "PCAutomatedRegression", precision = 10)
    public Float getPcautomatedRegression() {
	return this.pcautomatedRegression;
    }

    public void setPcautomatedRegression(Float pcautomatedRegression) {
	this.pcautomatedRegression = pcautomatedRegression;
    }

}
