package com.ericsson.mssp.common.entity;

//Generated May 22, 2014 11:53:09 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
* SecurityManagement generated by hbm2java
*/
@Entity
@Table(name = "SecurityManagement")
@NamedQueries({
	@NamedQuery(
	name = "get.securityManagement.bySolutionID",
	query = "from SecurityManagement where SolutionID = ?"
	)
})
public class SecurityManagement implements java.io.Serializable {

/**
* 
*/
private static final long serialVersionUID = -7676448561170657940L;
private Integer securityManagementID;
private Solution solution;
private OpportunityScope opportunityScope;
private float manageSecurity;
private float fteSecurityManagement; 


@Id
@GeneratedValue(strategy = IDENTITY)
@Column(name = "SecurityManagementID", unique = true, nullable = false)
public Integer getSecurityManagementID() {
	return this.securityManagementID;
}

public void setSecurityManagementID(Integer securityManagementID) {
	this.securityManagementID = securityManagementID;
}

@ManyToOne(fetch = FetchType.LAZY)
@JoinColumn(name = "SolutionID", nullable = false)
public Solution getSolution() {
	return this.solution;
}

public void setSolution(Solution solution) {
	this.solution = solution;
}


@ManyToOne(fetch = FetchType.LAZY)
@JoinColumn(name = "OpportunityScopeID")
	public OpportunityScope getOpportunityScope() {
		return opportunityScope;
	}

	/**
	 * @param opportunityScope the opportunityScope to set
	 */
	public void setOpportunityScope(OpportunityScope opportunityScope) {
		this.opportunityScope = opportunityScope;
	}

	@Column(name="ManageSecurity")
	public float getManageSecurity() {
		return manageSecurity;
	}

	public void setManageSecurity(float manageSecurity) {
		this.manageSecurity = manageSecurity;
	}

	@Column(name="FteSecurityManagement")
	public float getFteSecurityManagement() {
		return fteSecurityManagement;
	}

	public void setFteSecurityManagement(float fteSecurityManagement) {
		this.fteSecurityManagement = fteSecurityManagement;
	}


}


