package com.ericsson.mssp.common.entity;

import java.sql.Timestamp;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ServiceScope generated by hbm2java
 */
@Entity
@Table(name = "ServiceScope")
public class ServiceScope implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -330614778634165293L;
	private Integer serviceScopeId;
	private String serviceScopeCategory;
	private String serviceScopeName;
	private String createdBy;
	private Timestamp createdTimestamp;
	private String updatedBy;
	private Timestamp updatedTimestamp;
	private Set<OpportunityScope> opportunityScopes = new HashSet<OpportunityScope>(0);
	private ServiceElement serviceElement;
	private String serviceScopeDescription;
	private Integer serviceElementDefaultValue;
	private String active;

	public ServiceScope() {
	}

	public ServiceScope(String serviceScopeCategory, String serviceScopeName,
			String createdBy, Timestamp createdTimestamp, String updatedBy,
			Timestamp updatedTimestamp, Set<OpportunityScope> opportunityScopes
			,Integer serviceElementDefaultValue) {
		this.serviceScopeCategory = serviceScopeCategory;
		this.serviceScopeName = serviceScopeName;
		this.createdBy = createdBy;
		this.createdTimestamp = createdTimestamp;
		this.updatedBy = updatedBy;
		this.updatedTimestamp = updatedTimestamp;
		this.opportunityScopes = opportunityScopes;
		this.serviceElementDefaultValue = serviceElementDefaultValue;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ServiceScopeID", unique = true, nullable = false)
	public Integer getServiceScopeId() {
		return this.serviceScopeId;
	}

	public void setServiceScopeId(Integer serviceScopeId) {
		this.serviceScopeId = serviceScopeId;
	}

	@Column(name = "ServiceScopeCategory", length = 50)
	public String getServiceScopeCategory() {
		return this.serviceScopeCategory;
	}

	public void setServiceScopeCategory(String serviceScopeCategory) {
		this.serviceScopeCategory = serviceScopeCategory;
	}

	@Column(name = "ServiceScopeName", length = 50)
	public String getServiceScopeName() {
		return this.serviceScopeName;
	}

	public void setServiceScopeName(String serviceScopeName) {
		this.serviceScopeName = serviceScopeName;
	}

	@Column(name = "CreatedBy", length = 50)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	
	@Column(name = "CreatedTimestamp", length = 19)
	public Timestamp getCreatedTimestamp() {
		return this.createdTimestamp;
	}

	public void setCreatedTimestamp(Timestamp createdTimestamp) {
		this.createdTimestamp = createdTimestamp;
	}

	@Column(name = "UpdatedBy", length = 50)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	
	@Column(name = "UpdatedTimestamp", length = 19)
	public Timestamp getUpdatedTimestamp() {
		return this.updatedTimestamp;
	}

	public void setUpdatedTimestamp(Timestamp updatedTimestamp) {
		this.updatedTimestamp = updatedTimestamp;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "serviceScope")
	public Set<OpportunityScope> getOpportunityScopes() {
		return this.opportunityScopes;
	}

	public void setOpportunityScopes(Set<OpportunityScope> opportunityScopes) {
		this.opportunityScopes = opportunityScopes;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ServiceElementID", nullable = false)
	public ServiceElement getServiceElement() {
		return serviceElement;
	}

	public void setServiceElement(ServiceElement serviceElement) {
		this.serviceElement = serviceElement;
	}

	@Column(name = "ServiceScopeDescription", length = 500)
	public String getServiceScopeDescription() {
		return serviceScopeDescription;
	}

	public void setServiceScopeDescription(String serviceScopeDescription) {
		this.serviceScopeDescription = serviceScopeDescription;
	}

	@Column(name = "Active", length = 1)
	public String getActive() {
		return active;
	}

	public void setActive(String active) {
		this.active = active;
	}

	@Column(name = "ServiceElementDefaultValue")
	public Integer getServiceElementDefaultValue() {
		return serviceElementDefaultValue;
	}

	public void setServiceElementDefaultValue(Integer serviceElementDefaultValue) {
		this.serviceElementDefaultValue = serviceElementDefaultValue;
	}
	
}
