package com.ericsson.mssp.common.entity;

// Generated Feb 22, 2013 11:53:01 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SolutionEnhanDevFixedCapacity generated by hbm2java
 */
@Entity
@Table(name = "SolutionEnhanDevFixedDeposite")
public class SolutionEnhanDevFixedCapacity implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 7197743964946556461L;
    private Integer solutionEnhanDevFixedCapacityId;
    private Solution solution;
    private SolutionApproachDimension solutionApproachDimension;
    private Integer customerBuying;
    private Integer customerBuyingUnit;
    private Float pcqaunSimpleCr;
    private Float pcqaunMediumCr;
    private Float pcqaunComplexCr;
    private Float qaunSimpleCr;
    private Float qaunMediumCr;
    private Float qaunComplexCr;
    private Float effortSimpleCr;
    private Float effortMediumCr;
    private Float effortComplexCr;
    private Float totalEffortHrsCr;
    private Float effortManDays;
    private Float effortManWeeks;
    private Float effortManMonths;
    private Float durition;
    private String duritionUnit;
    private Float averageFtecr;
    private Float averageFtehrs;
	private OpportunityScope opportunityScope;

    public SolutionEnhanDevFixedCapacity() {
    }

    public SolutionEnhanDevFixedCapacity(Solution solution) {
	this.solution = solution;
    }

    public SolutionEnhanDevFixedCapacity(Solution solution,
	    SolutionApproachDimension solutionApproachDimension,
	    Integer customerBuying, Integer customerBuyingUnit,
	    Float pcqaunSimpleCr, Float pcqaunMediumCr, Float pcqaunComplexCr,
	    Float qaunSimpleCr, Float qaunMediumCr, Float qaunComplexCr,
	    Float effortSimpleCr, Float effortMediumCr, Float effortComplexCr,
	    Float totalEffortHrsCr, Float effortManDays, Float effortManWeeks,
	    Float effortManMonths, Float durition, String duritionUnit,
	    Float averageFtecr, Float averageFtehrs) {
	this.solution = solution;
	this.solutionApproachDimension = solutionApproachDimension;
	this.customerBuying = customerBuying;
	this.customerBuyingUnit = customerBuyingUnit;
	this.pcqaunSimpleCr = pcqaunSimpleCr;
	this.pcqaunMediumCr = pcqaunMediumCr;
	this.pcqaunComplexCr = pcqaunComplexCr;
	this.qaunSimpleCr = qaunSimpleCr;
	this.qaunMediumCr = qaunMediumCr;
	this.qaunComplexCr = qaunComplexCr;
	this.effortSimpleCr = effortSimpleCr;
	this.effortMediumCr = effortMediumCr;
	this.effortComplexCr = effortComplexCr;
	this.totalEffortHrsCr = totalEffortHrsCr;
	this.effortManDays = effortManDays;
	this.effortManWeeks = effortManWeeks;
	this.effortManMonths = effortManMonths;
	this.durition = durition;
	this.duritionUnit = duritionUnit;
	this.averageFtecr = averageFtecr;
	this.averageFtehrs = averageFtehrs;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "SolutionEnhanDevFixedDepositeID", unique = true, nullable = false)
    public Integer getSolutionEnhanDevFixedCapacityId() {
	return this.solutionEnhanDevFixedCapacityId;
    }

    public void setSolutionEnhanDevFixedCapacityId(
	    Integer solutionEnhanDevFixedCapacityId) {
	this.solutionEnhanDevFixedCapacityId = solutionEnhanDevFixedCapacityId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "SolutionID", nullable = false)
    public Solution getSolution() {
	return this.solution;
    }

    public void setSolution(Solution solution) {
	this.solution = solution;
    }
    
    /**
   	 * @return the opportunityScope
   	 */
       @ManyToOne(fetch = FetchType.LAZY)
       @JoinColumn(name = "OpportunityScopeID")
   	public OpportunityScope getOpportunityScope() {
   		return opportunityScope;
   	}

   	/**
   	 * @param opportunityScope the opportunityScope to set
   	 */
   	public void setOpportunityScope(OpportunityScope opportunityScope) {
   		this.opportunityScope = opportunityScope;
   	}
   	

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "SolutionApproachDimensionID")
    public SolutionApproachDimension getSolutionApproachDimension() {
	return this.solutionApproachDimension;
    }

    public void setSolutionApproachDimension(
	    SolutionApproachDimension solutionApproachDimension) {
	this.solutionApproachDimension = solutionApproachDimension;
    }

    @Column(name = "CustomerBuying")
    public Integer getCustomerBuying() {
	return this.customerBuying;
    }

    public void setCustomerBuying(Integer customerBuying) {
	this.customerBuying = customerBuying;
    }

    @Column(name = "CustomerBuyingUnit")
    public Integer getCustomerBuyingUnit() {
	return this.customerBuyingUnit;
    }

    public void setCustomerBuyingUnit(Integer customerBuyingUnit) {
	this.customerBuyingUnit = customerBuyingUnit;
    }

    @Column(name = "PCQaunSimpleCR", precision = 10)
    public Float getPcqaunSimpleCr() {
	return this.pcqaunSimpleCr;
    }

    public void setPcqaunSimpleCr(Float pcqaunSimpleCr) {
	this.pcqaunSimpleCr = pcqaunSimpleCr;
    }

    @Column(name = "PCQaunMediumCR", precision = 10)
    public Float getPcqaunMediumCr() {
	return this.pcqaunMediumCr;
    }

    public void setPcqaunMediumCr(Float pcqaunMediumCr) {
	this.pcqaunMediumCr = pcqaunMediumCr;
    }

    @Column(name = "PCQaunComplexCR", precision = 10)
    public Float getPcqaunComplexCr() {
	return this.pcqaunComplexCr;
    }

    public void setPcqaunComplexCr(Float pcqaunComplexCr) {
	this.pcqaunComplexCr = pcqaunComplexCr;
    }

    @Column(name = "QaunSimpleCR", precision = 10)
    public Float getQaunSimpleCr() {
	return this.qaunSimpleCr;
    }

    public void setQaunSimpleCr(Float qaunSimpleCr) {
	this.qaunSimpleCr = qaunSimpleCr;
    }

    @Column(name = "QaunMediumCR", precision = 10)
    public Float getQaunMediumCr() {
	return this.qaunMediumCr;
    }

    public void setQaunMediumCr(Float qaunMediumCr) {
	this.qaunMediumCr = qaunMediumCr;
    }

    @Column(name = "QaunComplexCR", precision = 10)
    public Float getQaunComplexCr() {
	return this.qaunComplexCr;
    }

    public void setQaunComplexCr(Float qaunComplexCr) {
	this.qaunComplexCr = qaunComplexCr;
    }

    @Column(name = "EffortSimpleCR", precision = 10)
    public Float getEffortSimpleCr() {
	return this.effortSimpleCr;
    }

    public void setEffortSimpleCr(Float effortSimpleCr) {
	this.effortSimpleCr = effortSimpleCr;
    }

    @Column(name = "EffortMediumCR", precision = 10)
    public Float getEffortMediumCr() {
	return this.effortMediumCr;
    }

    public void setEffortMediumCr(Float effortMediumCr) {
	this.effortMediumCr = effortMediumCr;
    }

    @Column(name = "EffortComplexCR", precision = 10)
    public Float getEffortComplexCr() {
	return this.effortComplexCr;
    }

    public void setEffortComplexCr(Float effortComplexCr) {
	this.effortComplexCr = effortComplexCr;
    }

    @Column(name = "TotalEffortHrsCR", precision = 10)
    public Float getTotalEffortHrsCr() {
	return this.totalEffortHrsCr;
    }

    public void setTotalEffortHrsCr(Float totalEffortHrsCr) {
	this.totalEffortHrsCr = totalEffortHrsCr;
    }

    @Column(name = "EffortManDays", precision = 10)
    public Float getEffortManDays() {
	return this.effortManDays;
    }

    public void setEffortManDays(Float effortManDays) {
	this.effortManDays = effortManDays;
    }

    @Column(name = "EffortManWeeks", precision = 10)
    public Float getEffortManWeeks() {
	return this.effortManWeeks;
    }

    public void setEffortManWeeks(Float effortManWeeks) {
	this.effortManWeeks = effortManWeeks;
    }

    @Column(name = "EffortManMonths", precision = 10)
    public Float getEffortManMonths() {
	return this.effortManMonths;
    }

    public void setEffortManMonths(Float effortManMonths) {
	this.effortManMonths = effortManMonths;
    }

    @Column(name = "Durition", precision = 10)
    public Float getDurition() {
	return this.durition;
    }

    public void setDurition(Float durition) {
	this.durition = durition;
    }

    @Column(name = "DuritionUnit", length = 50)
    public String getDuritionUnit() {
	return this.duritionUnit;
    }

    public void setDuritionUnit(String duritionUnit) {
	this.duritionUnit = duritionUnit;
    }

    @Column(name = "AverageFTECR", precision = 10)
    public Float getAverageFtecr() {
	return this.averageFtecr;
    }

    public void setAverageFtecr(Float averageFtecr) {
	this.averageFtecr = averageFtecr;
    }

    @Column(name = "AverageFTEHrs", precision = 10)
    public Float getAverageFtehrs() {
	return this.averageFtehrs;
    }

    public void setAverageFtehrs(Float averageFtehrs) {
	this.averageFtehrs = averageFtehrs;
    }

}
