package com.ericsson.mssp.common.entity;

// Generated Feb 7, 2013 11:35:07 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SolutionL3operations generated by hbm2java
 */
@Entity
@Table(name = "SolutionL3Operations")
public class SolutionL3operations implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = -2229860806023767524L;
    private Integer solutionL3operationsId;
    private Solution solution;
    private SupportWindowMatrix supportWindowMatrix;
    private SolutionApproachDimension solutionApproachDimension;
    private Float pcofL2incidentsConvL3;
    private Float totalL3bugFixesPerYear;
    private Float pcsimpleIncidents;
    private Float pcmediumIncidents;
    private Float pccomplexIncidents;
    private Float hrsSimpleIncidents;
    private Float hrsMediumIncidents;
    private Float hrsComplexIncidents;
    private Float avgResolutionTimeHrs;
    private Float anualHrsSpent;
    private Float utilizationperYr;
    private Float baseL3operationFte;
    private Float augmentedL3operationFte;
	private OpportunityScope opportunityScope;

    public SolutionL3operations() {
    }

    public SolutionL3operations(Solution solution) {
	this.solution = solution;
    }

    public SolutionL3operations(Solution solution,
	    SupportWindowMatrix supportWindowMatrix,
	    SolutionApproachDimension solutionApproachDimension,
	    Float pcofL2incidentsConvL3, Float totalL3bugFixesPerYear,
	    Float pcsimpleIncidents, Float pcmediumIncidents,
	    Float pccomplexIncidents, Float hrsSimpleIncidents,
	    Float hrsMediumIncidents, Float hrsComplexIncidents,
	    Float avgResolutionTimeHrs, Float anualHrsSpent,
	    Float utilizationperYr, Float baseL3operationFte,
	    Float augmentedL3operationFte) {
	this.solution = solution;
	this.supportWindowMatrix = supportWindowMatrix;
	this.solutionApproachDimension = solutionApproachDimension;
	this.pcofL2incidentsConvL3 = pcofL2incidentsConvL3;
	this.totalL3bugFixesPerYear = totalL3bugFixesPerYear;
	this.pcsimpleIncidents = pcsimpleIncidents;
	this.pcmediumIncidents = pcmediumIncidents;
	this.pccomplexIncidents = pccomplexIncidents;
	this.hrsSimpleIncidents = hrsSimpleIncidents;
	this.hrsMediumIncidents = hrsMediumIncidents;
	this.hrsComplexIncidents = hrsComplexIncidents;
	this.avgResolutionTimeHrs = avgResolutionTimeHrs;
	this.anualHrsSpent = anualHrsSpent;
	this.utilizationperYr = utilizationperYr;
	this.baseL3operationFte = baseL3operationFte;
	this.augmentedL3operationFte = augmentedL3operationFte;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "SolutionL3OperationsID", unique = true, nullable = false)
    public Integer getSolutionL3operationsId() {
	return this.solutionL3operationsId;
    }

    public void setSolutionL3operationsId(Integer solutionL3operationsId) {
	this.solutionL3operationsId = solutionL3operationsId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "SolutionID", nullable = false)
    public Solution getSolution() {
	return this.solution;
    }

    public void setSolution(Solution solution) {
	this.solution = solution;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "SupportWindowMatrixID")
    public SupportWindowMatrix getSupportWindowMatrix() {
	return this.supportWindowMatrix;
    }

    public void setSupportWindowMatrix(SupportWindowMatrix supportWindowMatrix) {
	this.supportWindowMatrix = supportWindowMatrix;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "SolutionApproachDimensionID")
    public SolutionApproachDimension getSolutionApproachDimension() {
	return this.solutionApproachDimension;
    }

    public void setSolutionApproachDimension(
	    SolutionApproachDimension solutionApproachDimension) {
	this.solutionApproachDimension = solutionApproachDimension;
    }

    @Column(name = "PCofL2IncidentsConvL3", precision = 10)
    public Float getPcofL2incidentsConvL3() {
	return this.pcofL2incidentsConvL3;
    }

    public void setPcofL2incidentsConvL3(Float pcofL2incidentsConvL3) {
	this.pcofL2incidentsConvL3 = pcofL2incidentsConvL3;
    }

    @Column(name = "TotalL3BugFixesPerYear", precision = 10)
    public Float getTotalL3bugFixesPerYear() {
	return this.totalL3bugFixesPerYear;
    }

    public void setTotalL3bugFixesPerYear(Float totalL3bugFixesPerYear) {
	this.totalL3bugFixesPerYear = totalL3bugFixesPerYear;
    }

    @Column(name = "PCSimpleIncidents", precision = 10)
    public Float getPcsimpleIncidents() {
	return this.pcsimpleIncidents;
    }

    public void setPcsimpleIncidents(Float pcsimpleIncidents) {
	this.pcsimpleIncidents = pcsimpleIncidents;
    }

    @Column(name = "PCMediumIncidents", precision = 10)
    public Float getPcmediumIncidents() {
	return this.pcmediumIncidents;
    }

    public void setPcmediumIncidents(Float pcmediumIncidents) {
	this.pcmediumIncidents = pcmediumIncidents;
    }

    @Column(name = "PCComplexIncidents", precision = 10)
    public Float getPccomplexIncidents() {
	return this.pccomplexIncidents;
    }

    public void setPccomplexIncidents(Float pccomplexIncidents) {
	this.pccomplexIncidents = pccomplexIncidents;
    }

    @Column(name = "HrsSimpleIncidents", precision = 10)
    public Float getHrsSimpleIncidents() {
	return this.hrsSimpleIncidents;
    }

    public void setHrsSimpleIncidents(Float hrsSimpleIncidents) {
	this.hrsSimpleIncidents = hrsSimpleIncidents;
    }

    @Column(name = "HrsMediumIncidents", precision = 10)
    public Float getHrsMediumIncidents() {
	return this.hrsMediumIncidents;
    }

    public void setHrsMediumIncidents(Float hrsMediumIncidents) {
	this.hrsMediumIncidents = hrsMediumIncidents;
    }

    @Column(name = "HrsComplexIncidents", precision = 10)
    public Float getHrsComplexIncidents() {
	return this.hrsComplexIncidents;
    }

    public void setHrsComplexIncidents(Float hrsComplexIncidents) {
	this.hrsComplexIncidents = hrsComplexIncidents;
    }

    @Column(name = "AvgResolutionTimeHrs", precision = 10)
    public Float getAvgResolutionTimeHrs() {
	return this.avgResolutionTimeHrs;
    }

    public void setAvgResolutionTimeHrs(Float avgResolutionTimeHrs) {
	this.avgResolutionTimeHrs = avgResolutionTimeHrs;
    }

    @Column(name = "AnualHrsSpent", precision = 10)
    public Float getAnualHrsSpent() {
	return this.anualHrsSpent;
    }

    public void setAnualHrsSpent(Float anualHrsSpent) {
	this.anualHrsSpent = anualHrsSpent;
    }

    @Column(name = "UtilizationperYr", precision = 10)
    public Float getUtilizationperYr() {
	return this.utilizationperYr;
    }

    public void setUtilizationperYr(Float utilizationperYr) {
	this.utilizationperYr = utilizationperYr;
    }

    @Column(name = "BaseL3OperationFTE", precision = 10)
    public Float getBaseL3operationFte() {
	return this.baseL3operationFte;
    }

    public void setBaseL3operationFte(Float baseL3operationFte) {
	this.baseL3operationFte = baseL3operationFte;
    }

    @Column(name = "AugmentedL3OperationFTE", precision = 10)
    public Float getAugmentedL3operationFte() {
	return this.augmentedL3operationFte;
    }

    public void setAugmentedL3operationFte(Float augmentedL3operationFte) {
	this.augmentedL3operationFte = augmentedL3operationFte;
    }
    /**
   	 * @return the opportunityScope
   	 */
       @ManyToOne(fetch = FetchType.LAZY)
       @JoinColumn(name = "OpportunityScopeID")
   	public OpportunityScope getOpportunityScope() {
   		return opportunityScope;
   	}

   	/**
   	 * @param opportunityScope the opportunityScope to set
   	 */
   	public void setOpportunityScope(OpportunityScope opportunityScope) {
   		this.opportunityScope = opportunityScope;
   	}
}
