package com.ericsson.mssp.common.entity;

// Generated Jan 29, 2013 11:53:09 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SolutionL1addServices generated by hbm2java
 */
@Entity
@Table(name = "SolutionL1AddServices")
public class SolutionL1addServices implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1484506463752107815L;
    private Integer solutionL1addServicesId;
    private Solution solution;
    private SolutionApproachDimension solutionApproachDimension;
    private String scopeAccessMgmt;
    private String scopeRequestMgmt;
    private String scopeEventMgmt;
    private String scopeL1billOperation;
    private String scopeL1preventive;
    private String scopeL1change;
    private String scopeL1routine;
    private String scopeL1performance;
    private Float effortAccessMgmt;
    private Float effortRequestMgmt;
    private Float effortEventMgmt;
    private Float effortL1billOperation;
    private Float effortL1preventive;
    private Float effortL1change;
    private Float effortL1routine;
    private Float effortL1performance;
    private Float fteaccessMgmt;
    private Float fterequestMgmt;
    private Float fteeventMgmt;
    private Float ftel1billOperation;
    private Float ftel1preventive;
    private Float ftel1change;
    private Float ftel1routine;
    private Float ftel1performance;
    private Float baseL1serviceFte;
    private Float augmentedL1serviceFte;
	private OpportunityScope opportunityScope;

    public SolutionL1addServices() {
    }

    public SolutionL1addServices(Solution solution,
	    SolutionApproachDimension solutionApproachDimension,
	    String scopeAccessMgmt, String scopeRequestMgmt,
	    String scopeEventMgmt, String scopeL1billOperation,
	    String scopeL1preventive, String scopeL1change,
	    String scopeL1routine, String scopeL1performance,
	    Float effortAccessMgmt, Float effortRequestMgmt,
	    Float effortEventMgmt, Float effortL1billOperation,
	    Float effortL1preventive, Float effortL1change,
	    Float effortL1routine, Float effortL1performance,
	    Float fteaccessMgmt, Float fterequestMgmt, Float fteeventMgmt,
	    Float ftel1billOperation, Float ftel1preventive, Float ftel1change,
	    Float ftel1routine, Float ftel1performance, Float baseL1serviceFte,
	    Float augmentedL1serviceFte) {
	this.solution = solution;
	this.solutionApproachDimension = solutionApproachDimension;
	this.scopeAccessMgmt = scopeAccessMgmt;
	this.scopeRequestMgmt = scopeRequestMgmt;
	this.scopeEventMgmt = scopeEventMgmt;
	this.scopeL1billOperation = scopeL1billOperation;
	this.scopeL1preventive = scopeL1preventive;
	this.scopeL1change = scopeL1change;
	this.scopeL1routine = scopeL1routine;
	this.scopeL1performance = scopeL1performance;
	this.effortAccessMgmt = effortAccessMgmt;
	this.effortRequestMgmt = effortRequestMgmt;
	this.effortEventMgmt = effortEventMgmt;
	this.effortL1billOperation = effortL1billOperation;
	this.effortL1preventive = effortL1preventive;
	this.effortL1change = effortL1change;
	this.effortL1routine = effortL1routine;
	this.effortL1performance = effortL1performance;
	this.fteaccessMgmt = fteaccessMgmt;
	this.fterequestMgmt = fterequestMgmt;
	this.fteeventMgmt = fteeventMgmt;
	this.ftel1billOperation = ftel1billOperation;
	this.ftel1preventive = ftel1preventive;
	this.ftel1change = ftel1change;
	this.ftel1routine = ftel1routine;
	this.ftel1performance = ftel1performance;
	this.baseL1serviceFte = baseL1serviceFte;
	this.augmentedL1serviceFte = augmentedL1serviceFte;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "SolutionL1AddServicesID", unique = true, nullable = false)
    public Integer getSolutionL1addServicesId() {
	return this.solutionL1addServicesId;
    }

    public void setSolutionL1addServicesId(Integer solutionL1addServicesId) {
	this.solutionL1addServicesId = solutionL1addServicesId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "SolutionID")
    public Solution getSolution() {
	return this.solution;
    }

    public void setSolution(Solution solution) {
	this.solution = solution;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "SolutionApproachDimensionID")
    public SolutionApproachDimension getSolutionApproachDimension() {
	return this.solutionApproachDimension;
    }

    public void setSolutionApproachDimension(
	    SolutionApproachDimension solutionApproachDimension) {
	this.solutionApproachDimension = solutionApproachDimension;
    }

    @Column(name = "ScopeAccessMgmt", length = 3)
    public String getScopeAccessMgmt() {
	return this.scopeAccessMgmt;
    }

    public void setScopeAccessMgmt(String scopeAccessMgmt) {
	this.scopeAccessMgmt = scopeAccessMgmt;
    }

    @Column(name = "ScopeRequestMgmt", length = 3)
    public String getScopeRequestMgmt() {
	return this.scopeRequestMgmt;
    }

    public void setScopeRequestMgmt(String scopeRequestMgmt) {
	this.scopeRequestMgmt = scopeRequestMgmt;
    }

    @Column(name = "ScopeEventMgmt", length = 3)
    public String getScopeEventMgmt() {
	return this.scopeEventMgmt;
    }

    public void setScopeEventMgmt(String scopeEventMgmt) {
	this.scopeEventMgmt = scopeEventMgmt;
    }

    @Column(name = "ScopeL1BillOperation", length = 3)
    public String getScopeL1billOperation() {
	return this.scopeL1billOperation;
    }

    public void setScopeL1billOperation(String scopeL1billOperation) {
	this.scopeL1billOperation = scopeL1billOperation;
    }

    @Column(name = "ScopeL1Preventive", length = 3)
    public String getScopeL1preventive() {
	return this.scopeL1preventive;
    }

    public void setScopeL1preventive(String scopeL1preventive) {
	this.scopeL1preventive = scopeL1preventive;
    }

    @Column(name = "ScopeL1Change", length = 3)
    public String getScopeL1change() {
	return this.scopeL1change;
    }

    public void setScopeL1change(String scopeL1change) {
	this.scopeL1change = scopeL1change;
    }

    @Column(name = "ScopeL1Routine", length = 3)
    public String getScopeL1routine() {
	return this.scopeL1routine;
    }

    public void setScopeL1routine(String scopeL1routine) {
	this.scopeL1routine = scopeL1routine;
    }

    @Column(name = "ScopeL1Performance", length = 3)
    public String getScopeL1performance() {
	return this.scopeL1performance;
    }

    public void setScopeL1performance(String scopeL1performance) {
	this.scopeL1performance = scopeL1performance;
    }

    @Column(name = "EffortAccessMgmt", precision = 10)
    public Float getEffortAccessMgmt() {
	return this.effortAccessMgmt;
    }

    public void setEffortAccessMgmt(Float effortAccessMgmt) {
	this.effortAccessMgmt = effortAccessMgmt;
    }

    @Column(name = "EffortRequestMgmt", precision = 10)
    public Float getEffortRequestMgmt() {
	return this.effortRequestMgmt;
    }

    public void setEffortRequestMgmt(Float effortRequestMgmt) {
	this.effortRequestMgmt = effortRequestMgmt;
    }

    @Column(name = "EffortEventMgmt", precision = 10)
    public Float getEffortEventMgmt() {
	return this.effortEventMgmt;
    }

    public void setEffortEventMgmt(Float effortEventMgmt) {
	this.effortEventMgmt = effortEventMgmt;
    }

    @Column(name = "EffortL1BillOperation", precision = 10)
    public Float getEffortL1billOperation() {
	return this.effortL1billOperation;
    }

    public void setEffortL1billOperation(Float effortL1billOperation) {
	this.effortL1billOperation = effortL1billOperation;
    }

    @Column(name = "EffortL1Preventive", precision = 10)
    public Float getEffortL1preventive() {
	return this.effortL1preventive;
    }

    public void setEffortL1preventive(Float effortL1preventive) {
	this.effortL1preventive = effortL1preventive;
    }

    @Column(name = "EffortL1Change", precision = 10)
    public Float getEffortL1change() {
	return this.effortL1change;
    }

    public void setEffortL1change(Float effortL1change) {
	this.effortL1change = effortL1change;
    }

    @Column(name = "EffortL1Routine", precision = 10)
    public Float getEffortL1routine() {
	return this.effortL1routine;
    }

    public void setEffortL1routine(Float effortL1routine) {
	this.effortL1routine = effortL1routine;
    }

    @Column(name = "EffortL1Performance", precision = 10)
    public Float getEffortL1performance() {
	return this.effortL1performance;
    }

    public void setEffortL1performance(Float effortL1performance) {
	this.effortL1performance = effortL1performance;
    }

    @Column(name = "FTEAccessMgmt", precision = 10)
    public Float getFteaccessMgmt() {
	return this.fteaccessMgmt;
    }

    public void setFteaccessMgmt(Float fteaccessMgmt) {
	this.fteaccessMgmt = fteaccessMgmt;
    }

    @Column(name = "FTERequestMgmt", precision = 10)
    public Float getFterequestMgmt() {
	return this.fterequestMgmt;
    }

    public void setFterequestMgmt(Float fterequestMgmt) {
	this.fterequestMgmt = fterequestMgmt;
    }

    @Column(name = "FTEEventMgmt", precision = 10)
    public Float getFteeventMgmt() {
	return this.fteeventMgmt;
    }

    public void setFteeventMgmt(Float fteeventMgmt) {
	this.fteeventMgmt = fteeventMgmt;
    }

    @Column(name = "FTEL1BillOperation", precision = 10)
    public Float getFtel1billOperation() {
	return this.ftel1billOperation;
    }

    public void setFtel1billOperation(Float ftel1billOperation) {
	this.ftel1billOperation = ftel1billOperation;
    }

    @Column(name = "FTEL1Preventive", precision = 10)
    public Float getFtel1preventive() {
	return this.ftel1preventive;
    }

    public void setFtel1preventive(Float ftel1preventive) {
	this.ftel1preventive = ftel1preventive;
    }

    @Column(name = "FTEL1Change", precision = 10)
    public Float getFtel1change() {
	return this.ftel1change;
    }

    public void setFtel1change(Float ftel1change) {
	this.ftel1change = ftel1change;
    }

    @Column(name = "FTEL1Routine", precision = 10)
    public Float getFtel1routine() {
	return this.ftel1routine;
    }

    public void setFtel1routine(Float ftel1routine) {
	this.ftel1routine = ftel1routine;
    }

    @Column(name = "FTEL1Performance", precision = 10)
    public Float getFtel1performance() {
	return this.ftel1performance;
    }

    public void setFtel1performance(Float ftel1performance) {
	this.ftel1performance = ftel1performance;
    }

    @Column(name = "BaseL1ServiceFTE", precision = 10)
    public Float getBaseL1serviceFte() {
	return this.baseL1serviceFte;
    }

    public void setBaseL1serviceFte(Float baseL1serviceFte) {
	this.baseL1serviceFte = baseL1serviceFte;
    }

    @Column(name = "AugmentedL1ServiceFTE", precision = 10)
    public Float getAugmentedL1serviceFte() {
	return this.augmentedL1serviceFte;
    }

    public void setAugmentedL1serviceFte(Float augmentedL1serviceFte) {
	this.augmentedL1serviceFte = augmentedL1serviceFte;
    }
    /**
   	 * @return the opportunityScope
   	 */
       @ManyToOne(fetch = FetchType.LAZY)
       @JoinColumn(name = "OpportunityScopeID")
   	public OpportunityScope getOpportunityScope() {
   		return opportunityScope;
   	}

   	/**
   	 * @param opportunityScope the opportunityScope to set
   	 */
   	public void setOpportunityScope(OpportunityScope opportunityScope) {
   		this.opportunityScope = opportunityScope;
   	}
}
