package com.ericsson.mssp.common.entity;

// Generated Jan 29, 2013 11:53:09 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SolutionServiceDesk generated by hbm2java
 */
@Entity
@Table(name = "SolutionServiceDesk")
@NamedQueries({
	@NamedQuery(
	name = "get.serviceDesk",
	query = "from SolutionServiceDesk as sd left join sd.solution as sol where sol.solutionId = 2"
	)
})
public class SolutionServiceDesk implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = -7676448561170657940L;
    private Integer serviceDeskId;
    private Solution solution;
    private TouchPointChannel touchPointChannel;
    private SupportWindowMatrix supportWindowMatrix;
    private SolutionApproachDimension solutionApproachDimension;
    private Float transactionsPerMonth;
    private Float averageHandlingTime;
    private Float totalTransPerYear;
    private Float durationOfCallsPerYear;
    private Float utilizationPerYear;
    private Float baseServiceDeskFte;
    private Float augmentedHeads;
    private OpportunityScope opportunityScope;
    
    public SolutionServiceDesk() {
    }

    public SolutionServiceDesk(Solution solution) {
	this.solution = solution;
    }

    public SolutionServiceDesk(Solution solution,
	    TouchPointChannel touchPointChannel,
	    SupportWindowMatrix supportWindowMatrix,
	    SolutionApproachDimension solutionApproachDimension,
	    Float transactionsPerMonth, Float averageHandlingTime,
	    Float totalTransPerYear, Float durationOfCallsPerYear,
	    Float utilizationPerYear, Float baseServiceDeskFte,
	    Float augmentedHeads) {
	this.solution = solution;
	this.touchPointChannel = touchPointChannel;
	this.supportWindowMatrix = supportWindowMatrix;
	this.solutionApproachDimension = solutionApproachDimension;
	this.transactionsPerMonth = transactionsPerMonth;
	this.averageHandlingTime = averageHandlingTime;
	this.totalTransPerYear = totalTransPerYear;
	this.durationOfCallsPerYear = durationOfCallsPerYear;
	this.utilizationPerYear = utilizationPerYear;
	this.baseServiceDeskFte = baseServiceDeskFte;
	this.augmentedHeads = augmentedHeads;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "ServiceDeskID", unique = true, nullable = false)
    public Integer getServiceDeskId() {
	return this.serviceDeskId;
    }

    public void setServiceDeskId(Integer serviceDeskId) {
	this.serviceDeskId = serviceDeskId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "SolutionID", nullable = false)
    public Solution getSolution() {
	return this.solution;
    }

    public void setSolution(Solution solution) {
	this.solution = solution;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "TouchPointChannelID")
    public TouchPointChannel getTouchPointChannel() {
	return this.touchPointChannel;
    }

    public void setTouchPointChannel(TouchPointChannel touchPointChannel) {
	this.touchPointChannel = touchPointChannel;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "SupportWindowMatrixID")
    public SupportWindowMatrix getSupportWindowMatrix() {
	return this.supportWindowMatrix;
    }

    public void setSupportWindowMatrix(SupportWindowMatrix supportWindowMatrix) {
	this.supportWindowMatrix = supportWindowMatrix;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "SolutionApproachDimensionID")
    public SolutionApproachDimension getSolutionApproachDimension() {
	return this.solutionApproachDimension;
    }

    public void setSolutionApproachDimension(
	    SolutionApproachDimension solutionApproachDimension) {
	this.solutionApproachDimension = solutionApproachDimension;
    }
    
    /**
	 * @return the opportunityScope
	 */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "OpportunityScopeID")
	public OpportunityScope getOpportunityScope() {
		return opportunityScope;
	}

	/**
	 * @param opportunityScope the opportunityScope to set
	 */
	public void setOpportunityScope(OpportunityScope opportunityScope) {
		this.opportunityScope = opportunityScope;
	}

	@Column(name = "TransactionsPerMonth", precision = 10)
    public Float getTransactionsPerMonth() {
	return this.transactionsPerMonth;
    }

    public void setTransactionsPerMonth(Float transactionsPerMonth) {
	this.transactionsPerMonth = transactionsPerMonth;
    }

    @Column(name = "AverageHandlingTime", precision = 10)
    public Float getAverageHandlingTime() {
	return this.averageHandlingTime;
    }

    public void setAverageHandlingTime(Float averageHandlingTime) {
	this.averageHandlingTime = averageHandlingTime;
    }

    @Column(name = "TotalTransPerYear", precision = 10)
    public Float getTotalTransPerYear() {
	return this.totalTransPerYear;
    }

    public void setTotalTransPerYear(Float totalTransPerYear) {
	this.totalTransPerYear = totalTransPerYear;
    }

    @Column(name = "DurationOfCallsPerYear", precision = 10)
    public Float getDurationOfCallsPerYear() {
	return this.durationOfCallsPerYear;
    }

    public void setDurationOfCallsPerYear(Float durationOfCallsPerYear) {
	this.durationOfCallsPerYear = durationOfCallsPerYear;
    }

    @Column(name = "UtilizationPerYear")
    public Float getUtilizationPerYear() {
	return this.utilizationPerYear;
    }

    public void setUtilizationPerYear(Float utilizationPerYear) {
	this.utilizationPerYear = utilizationPerYear;
    }

    @Column(name = "BaseServiceDeskFTE", precision = 10)
    public Float getBaseServiceDeskFte() {
	return this.baseServiceDeskFte;
    }

    public void setBaseServiceDeskFte(Float baseServiceDeskFte) {
	this.baseServiceDeskFte = baseServiceDeskFte;
    }

    @Column(name = "AugmentedHeads", precision = 10)
    public Float getAugmentedHeads() {
	return this.augmentedHeads;
    }

    public void setAugmentedHeads(Float augmentedHeads) {
	this.augmentedHeads = augmentedHeads;
    }

}
