package com.ericsson.mssp.common.entity;

// Generated Jan 29, 2013 11:53:09 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SolutionL1operations generated by hbm2java
 */
@Entity
@Table(name = "SolutionL1Operations")
public class SolutionL1operations implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 2662282315276928030L;
    private Integer solutionL1operationsId;
    private Solution solution;
    private SupportWindowMatrix supportWindowMatrix;
    private SolutionApproachDimension solutionApproachDimension;
    private Float pcofL1incidents;
    private Float totalL1incidentsperYr;
    private Float pcsimpleIncidents;
    private Float pcmediumIncidents;
    private Float pccomplexIncidents;
    private Float hrsSimpleIncidents;
    private Float hrsMediumIncidents;
    private Float hrsComplexIncidents;
    private Float avgResolutionTimeHrs;
    private Float anualHrsSpent;
    private Float utilizationperYr;
    private Float baseL1operationFte;
    private Float augmentedL1operationFte;
	private OpportunityScope opportunityScope;

    public SolutionL1operations() {
    }

    public SolutionL1operations(Solution solution,
	    SupportWindowMatrix supportWindowMatrix,
	    SolutionApproachDimension solutionApproachDimension,
	    Float pcofL1incidents, Float totalL1incidentsperYr,
	    Float pcsimpleIncidents, Float pcmediumIncidents,
	    Float pccomplexIncidents, Float hrsSimpleIncidents,
	    Float hrsMediumIncidents, Float hrsComplexIncidents,
	    Float avgResolutionTimeHrs, Float anualHrsSpent,
	    Float utilizationperYr, Float baseL1operationFte,
	    Float augmentedL1operationFte) {
	this.solution = solution;
	this.supportWindowMatrix = supportWindowMatrix;
	this.solutionApproachDimension = solutionApproachDimension;
	this.pcofL1incidents = pcofL1incidents;
	this.totalL1incidentsperYr = totalL1incidentsperYr;
	this.pcsimpleIncidents = pcsimpleIncidents;
	this.pcmediumIncidents = pcmediumIncidents;
	this.pccomplexIncidents = pccomplexIncidents;
	this.hrsSimpleIncidents = hrsSimpleIncidents;
	this.hrsMediumIncidents = hrsMediumIncidents;
	this.hrsComplexIncidents = hrsComplexIncidents;
	this.avgResolutionTimeHrs = avgResolutionTimeHrs;
	this.anualHrsSpent = anualHrsSpent;
	this.utilizationperYr = utilizationperYr;
	this.baseL1operationFte = baseL1operationFte;
	this.augmentedL1operationFte = augmentedL1operationFte;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "SolutionL1operationsID", unique = true, nullable = false)
    public Integer getSolutionL1operationsId() {
	return this.solutionL1operationsId;
    }

    public void setSolutionL1operationsId(Integer solutionL1operationsId) {
	this.solutionL1operationsId = solutionL1operationsId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "SolutionID")
    public Solution getSolution() {
	return this.solution;
    }

    public void setSolution(Solution solution) {
	this.solution = solution;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "SupportWindowMatrixID")
    public SupportWindowMatrix getSupportWindowMatrix() {
	return this.supportWindowMatrix;
    }

    public void setSupportWindowMatrix(SupportWindowMatrix supportWindowMatrix) {
	this.supportWindowMatrix = supportWindowMatrix;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "SolutionApproachDimensionID")
    public SolutionApproachDimension getSolutionApproachDimension() {
	return this.solutionApproachDimension;
    }

    public void setSolutionApproachDimension(
	    SolutionApproachDimension solutionApproachDimension) {
	this.solutionApproachDimension = solutionApproachDimension;
    }

    @Column(name = "PCofL1Incidents", precision = 10)
    public Float getPcofL1incidents() {
	return this.pcofL1incidents;
    }

    public void setPcofL1incidents(Float pcofL1incidents) {
	this.pcofL1incidents = pcofL1incidents;
    }

    @Column(name = "TotalL1IncidentsperYr", precision = 10)
    public Float getTotalL1incidentsperYr() {
	return this.totalL1incidentsperYr;
    }

    public void setTotalL1incidentsperYr(Float totalL1incidentsperYr) {
	this.totalL1incidentsperYr = totalL1incidentsperYr;
    }

    @Column(name = "PCSimpleIncidents", precision = 10)
    public Float getPcsimpleIncidents() {
	return this.pcsimpleIncidents;
    }

    public void setPcsimpleIncidents(Float pcsimpleIncidents) {
	this.pcsimpleIncidents = pcsimpleIncidents;
    }

    @Column(name = "PCMediumIncidents", precision = 10)
    public Float getPcmediumIncidents() {
	return this.pcmediumIncidents;
    }

    public void setPcmediumIncidents(Float pcmediumIncidents) {
	this.pcmediumIncidents = pcmediumIncidents;
    }

    @Column(name = "PCComplexIncidents", precision = 10)
    public Float getPccomplexIncidents() {
	return this.pccomplexIncidents;
    }

    public void setPccomplexIncidents(Float pccomplexIncidents) {
	this.pccomplexIncidents = pccomplexIncidents;
    }

    @Column(name = "HrsSimpleIncidents", precision = 10)
    public Float getHrsSimpleIncidents() {
	return this.hrsSimpleIncidents;
    }

    public void setHrsSimpleIncidents(Float hrsSimpleIncidents) {
	this.hrsSimpleIncidents = hrsSimpleIncidents;
    }

    @Column(name = "HrsMediumIncidents", precision = 10)
    public Float getHrsMediumIncidents() {
	return this.hrsMediumIncidents;
    }

    public void setHrsMediumIncidents(Float hrsMediumIncidents) {
	this.hrsMediumIncidents = hrsMediumIncidents;
    }

    @Column(name = "HrsComplexIncidents", precision = 10)
    public Float getHrsComplexIncidents() {
	return this.hrsComplexIncidents;
    }

    public void setHrsComplexIncidents(Float hrsComplexIncidents) {
	this.hrsComplexIncidents = hrsComplexIncidents;
    }

    @Column(name = "AvgResolutionTimeHrs", precision = 10)
    public Float getAvgResolutionTimeHrs() {
	return this.avgResolutionTimeHrs;
    }

    public void setAvgResolutionTimeHrs(Float avgResolutionTimeHrs) {
	this.avgResolutionTimeHrs = avgResolutionTimeHrs;
    }

    @Column(name = "AnualHrsSpent", precision = 10)
    public Float getAnualHrsSpent() {
	return this.anualHrsSpent;
    }

    public void setAnualHrsSpent(Float anualHrsSpent) {
	this.anualHrsSpent = anualHrsSpent;
    }

    @Column(name = "UtilizationperYr", precision = 10)
    public Float getUtilizationperYr() {
	return this.utilizationperYr;
    }

    public void setUtilizationperYr(Float utilizationperYr) {
	this.utilizationperYr = utilizationperYr;
    }

    @Column(name = "BaseL1OperationFTE", precision = 10)
    public Float getBaseL1operationFte() {
	return this.baseL1operationFte;
    }

    public void setBaseL1operationFte(Float baseL1operationFte) {
	this.baseL1operationFte = baseL1operationFte;
    }

    @Column(name = "AugmentedL1OperationFTE", precision = 10)
    public Float getAugmentedL1operationFte() {
	return this.augmentedL1operationFte;
    }

    public void setAugmentedL1operationFte(Float augmentedL1operationFte) {
	this.augmentedL1operationFte = augmentedL1operationFte;
    }
    /**
   	 * @return the opportunityScope
   	 */
       @ManyToOne(fetch = FetchType.LAZY)
       @JoinColumn(name = "OpportunityScopeID")
   	public OpportunityScope getOpportunityScope() {
   		return opportunityScope;
   	}

   	/**
   	 * @param opportunityScope the opportunityScope to set
   	 */
   	public void setOpportunityScope(OpportunityScope opportunityScope) {
   		this.opportunityScope = opportunityScope;
   	}
}
