package com.ericsson.mssp.common.entity;

// Generated Jan 29, 2013 11:53:09 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TouchPointChannel generated by hbm2java
 */
@Entity
@Table(name = "TouchPointChannel")
public class TouchPointChannel implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 5171413058962820474L;
    private Integer touchPointChannelId;
    private String channelName;
    private Set<SolutionServiceDesk> solutionServiceDesks = new HashSet<SolutionServiceDesk>(
	    0);

    public TouchPointChannel() {
    }

    public TouchPointChannel(String channelName) {
	this.channelName = channelName;
    }

    public TouchPointChannel(String channelName,
	    Set<SolutionServiceDesk> solutionServiceDesks) {
	this.channelName = channelName;
	this.solutionServiceDesks = solutionServiceDesks;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "TouchPointChannelID", unique = true, nullable = false)
    public Integer getTouchPointChannelId() {
	return this.touchPointChannelId;
    }

    public void setTouchPointChannelId(Integer touchPointChannelId) {
	this.touchPointChannelId = touchPointChannelId;
    }

    @Column(name = "ChannelName", nullable = false, length = 50)
    public String getChannelName() {
	return this.channelName;
    }

    public void setChannelName(String channelName) {
	this.channelName = channelName;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "touchPointChannel")
    public Set<SolutionServiceDesk> getSolutionServiceDesks() {
	return this.solutionServiceDesks;
    }

    public void setSolutionServiceDesks(
	    Set<SolutionServiceDesk> solutionServiceDesks) {
	this.solutionServiceDesks = solutionServiceDesks;
    }

}
