package com.ericsson.mssp.common.entity;

// Generated May 7, 2013 8:30:07 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TtjobRoleDistribution generated by hbm2java
 */
@Entity
@Table(name = "TTJobRoleDistribution")
public class TTJobRoleDistribution implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 7384865259664885270L;
    private Integer ttjobRoleDistributionId;
    private TTPlanning ttplanning;
    private JobRole jobRole;
    private Date weekDate;
    private Float distributionPc;
    private Float ftecount;

    public TTJobRoleDistribution() {
    }

    public TTJobRoleDistribution(TTPlanning ttplanning, JobRole jobRole,
	    Date weekDate, Float distributionPc, Float ftecount) {
	this.ttplanning = ttplanning;
	this.jobRole = jobRole;
	this.weekDate = weekDate;
	this.distributionPc = distributionPc;
	this.ftecount = ftecount;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "TTJobRoleDistributionID", unique = true, nullable = false)
    public Integer getTtjobRoleDistributionId() {
	return this.ttjobRoleDistributionId;
    }

    public void setTtjobRoleDistributionId(Integer ttjobRoleDistributionId) {
	this.ttjobRoleDistributionId = ttjobRoleDistributionId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "TTPlanningID")
    public TTPlanning getTtplanning() {
	return this.ttplanning;
    }

    public void setTtplanning(TTPlanning ttplanning) {
	this.ttplanning = ttplanning;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "JobRoleID")
    public JobRole getJobRole() {
	return this.jobRole;
    }

    public void setJobRole(JobRole jobRole) {
	this.jobRole = jobRole;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "WeekDate", length = 19)
    public Date getWeekDate() {
	return this.weekDate;
    }

    public void setWeekDate(Date weekDate) {
	this.weekDate = weekDate;
    }

    @Column(name = "DistributionPC", precision = 10)
    public Float getDistributionPc() {
	return this.distributionPc;
    }

    public void setDistributionPc(Float distributionPc) {
	this.distributionPc = distributionPc;
    }

    @Column(name = "FTECount", precision = 10)
    public Float getFtecount() {
	return this.ftecount;
    }

    public void setFtecount(Float ftecount) {
	this.ftecount = ftecount;
    }

}
