package com.ericsson.mssp.common.entity;

// Generated May 7, 2013 8:30:07 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TtpartitionDetail generated by hbm2java
 */
@Entity
@Table(name = "TTPartitionDetail")
public class TTPartitionDetail implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 9159554288555645907L;
    private Integer ttpartitionDetailId;
    private TTPartitionName ttpartitionName;
    private Date planStartDate;
    private Date planEndDate;
    private Float planFtecount;
    private Date learnStartDate;
    private Date learnEndDate;
    private Float learnFtecount;
    private Date assistStartDate;
    private Date assistEndDate;
    private Float assistFtecount;
    private Date performStartDate;
    private Date performEndDate;
    private Float performFtecount;
    private Date deliverStartDate;
    private Date deliverEndDate;
    private Float deliverFtecount;

    public TTPartitionDetail() {
    }

    public TTPartitionDetail(TTPartitionName ttpartitionName,
	    Date planStartDate, Date planEndDate, Float planFtecount,
	    Date learnStartDate, Date learnEndDate, Float learnFtecount,
	    Date assistStartDate, Date assistEndDate, Float assistFtecount,
	    Date performStartDate, Date performEndDate, Float performFtecount,
	    Date deliverStartDate, Date deliverEndDate, Float deliverFtecount) {
	this.ttpartitionName = ttpartitionName;
	this.planStartDate = planStartDate;
	this.planEndDate = planEndDate;
	this.planFtecount = planFtecount;
	this.learnStartDate = learnStartDate;
	this.learnEndDate = learnEndDate;
	this.learnFtecount = learnFtecount;
	this.assistStartDate = assistStartDate;
	this.assistEndDate = assistEndDate;
	this.assistFtecount = assistFtecount;
	this.performStartDate = performStartDate;
	this.performEndDate = performEndDate;
	this.performFtecount = performFtecount;
	this.deliverStartDate = deliverStartDate;
	this.deliverEndDate = deliverEndDate;
	this.deliverFtecount = deliverFtecount;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "TTPartitionDetailID", unique = true, nullable = false)
    public Integer getTtpartitionDetailId() {
	return this.ttpartitionDetailId;
    }

    public void setTtpartitionDetailId(Integer ttpartitionDetailId) {
	this.ttpartitionDetailId = ttpartitionDetailId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "TTPartitionNameID")
    public TTPartitionName getTtpartitionName() {
	return this.ttpartitionName;
    }

    public void setTtpartitionName(TTPartitionName ttpartitionName) {
	this.ttpartitionName = ttpartitionName;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "PlanStartDate", length = 19)
    public Date getPlanStartDate() {
	return this.planStartDate;
    }

    public void setPlanStartDate(Date planStartDate) {
	this.planStartDate = planStartDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "PlanEndDate", length = 19)
    public Date getPlanEndDate() {
	return this.planEndDate;
    }

    public void setPlanEndDate(Date planEndDate) {
	this.planEndDate = planEndDate;
    }

    @Column(name = "PlanFTECount", precision = 10)
    public Float getPlanFtecount() {
	return this.planFtecount;
    }

    public void setPlanFtecount(Float planFtecount) {
	this.planFtecount = planFtecount;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "LearnStartDate", length = 19)
    public Date getLearnStartDate() {
	return this.learnStartDate;
    }

    public void setLearnStartDate(Date learnStartDate) {
	this.learnStartDate = learnStartDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "LearnEndDate", length = 19)
    public Date getLearnEndDate() {
	return this.learnEndDate;
    }

    public void setLearnEndDate(Date learnEndDate) {
	this.learnEndDate = learnEndDate;
    }

    @Column(name = "LearnFTECount", precision = 10)
    public Float getLearnFtecount() {
	return this.learnFtecount;
    }

    public void setLearnFtecount(Float learnFtecount) {
	this.learnFtecount = learnFtecount;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "AssistStartDate", length = 19)
    public Date getAssistStartDate() {
	return this.assistStartDate;
    }

    public void setAssistStartDate(Date assistStartDate) {
	this.assistStartDate = assistStartDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "AssistEndDate", length = 19)
    public Date getAssistEndDate() {
	return this.assistEndDate;
    }

    public void setAssistEndDate(Date assistEndDate) {
	this.assistEndDate = assistEndDate;
    }

    @Column(name = "AssistFTECount", precision = 10)
    public Float getAssistFtecount() {
	return this.assistFtecount;
    }

    public void setAssistFtecount(Float assistFtecount) {
	this.assistFtecount = assistFtecount;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "PerformStartDate", length = 19)
    public Date getPerformStartDate() {
	return this.performStartDate;
    }

    public void setPerformStartDate(Date performStartDate) {
	this.performStartDate = performStartDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "PerformEndDate", length = 19)
    public Date getPerformEndDate() {
	return this.performEndDate;
    }

    public void setPerformEndDate(Date performEndDate) {
	this.performEndDate = performEndDate;
    }

    @Column(name = "PerformFTECount", precision = 10)
    public Float getPerformFtecount() {
	return this.performFtecount;
    }

    public void setPerformFtecount(Float performFtecount) {
	this.performFtecount = performFtecount;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "DeliverStartDate", length = 19)
    public Date getDeliverStartDate() {
	return this.deliverStartDate;
    }

    public void setDeliverStartDate(Date deliverStartDate) {
	this.deliverStartDate = deliverStartDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "DeliverEndDate", length = 19)
    public Date getDeliverEndDate() {
	return this.deliverEndDate;
    }

    public void setDeliverEndDate(Date deliverEndDate) {
	this.deliverEndDate = deliverEndDate;
    }

    @Column(name = "DeliverFTECount", precision = 10)
    public Float getDeliverFtecount() {
	return this.deliverFtecount;
    }

    public void setDeliverFtecount(Float deliverFtecount) {
	this.deliverFtecount = deliverFtecount;
    }

}
