package com.ericsson.mssp.common.entity;

// Generated May 7, 2013 8:30:07 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ttsummary generated by hbm2java
 */
@Entity
@Table(name = "TTSummary")
public class TTSummary implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 2072226906222575084L;
    private Integer ttsummaryId;
    private TTPlanning ttplanning;
    private Date weekDate;
    private Float onshoreFte;
    private Float offshoreFte;
    private Float totalFte;

    public TTSummary() {
    }

    public TTSummary(TTPlanning ttplanning, Date weekDate, Float onshoreFte,
	    Float offshoreFte, Float totalFte) {
	this.ttplanning = ttplanning;
	this.weekDate = weekDate;
	this.onshoreFte = onshoreFte;
	this.offshoreFte = offshoreFte;
	this.totalFte = totalFte;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "TTSummaryID", unique = true, nullable = false)
    public Integer getTtsummaryId() {
	return this.ttsummaryId;
    }

    public void setTtsummaryId(Integer ttsummaryId) {
	this.ttsummaryId = ttsummaryId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "TTPlanningID")
    public TTPlanning getTtplanning() {
	return this.ttplanning;
    }

    public void setTtplanning(TTPlanning ttplanning) {
	this.ttplanning = ttplanning;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "WeekDate", length = 19)
    public Date getWeekDate() {
	return this.weekDate;
    }

    public void setWeekDate(Date weekDate) {
	this.weekDate = weekDate;
    }

    @Column(name = "OnshoreFTE", precision = 10)
    public Float getOnshoreFte() {
	return this.onshoreFte;
    }

    public void setOnshoreFte(Float onshoreFte) {
	this.onshoreFte = onshoreFte;
    }

    @Column(name = "OffshoreFTE", precision = 10)
    public Float getOffshoreFte() {
	return this.offshoreFte;
    }

    public void setOffshoreFte(Float offshoreFte) {
	this.offshoreFte = offshoreFte;
    }

    @Column(name = "TotalFTE", precision = 10)
    public Float getTotalFte() {
	return this.totalFte;
    }

    public void setTotalFte(Float totalFte) {
	this.totalFte = totalFte;
    }

}
