package com.ericsson.mssp.common.entity;

// Generated May 7, 2013 8:30:07 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TtsummaryStaging generated by hbm2java
 */
@Entity
@Table(name = "TTSummaryStaging")
public class TTSummaryStaging implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = -8591019390123117489L;
    private Integer ttsummaryStagingId;
    private TTPartitionName ttpartitionName;
    private Date weekDate;
    private Float onshoreFte;
    private Float offshoreFte;

    public TTSummaryStaging() {
    }

    public TTSummaryStaging(TTPartitionName ttpartitionName, Date weekDate,
	    Float onshoreFte, Float offshoreFte) {
	this.ttpartitionName = ttpartitionName;
	this.weekDate = weekDate;
	this.onshoreFte = onshoreFte;
	this.offshoreFte = offshoreFte;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "TTSummaryStagingID", unique = true, nullable = false)
    public Integer getTtsummaryStagingId() {
	return this.ttsummaryStagingId;
    }

    public void setTtsummaryStagingId(Integer ttsummaryStagingId) {
	this.ttsummaryStagingId = ttsummaryStagingId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "TTPartitionNameID")
    public TTPartitionName getTtpartitionName() {
	return this.ttpartitionName;
    }

    public void setTtpartitionName(TTPartitionName ttpartitionName) {
	this.ttpartitionName = ttpartitionName;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "WeekDate", length = 19)
    public Date getWeekDate() {
	return this.weekDate;
    }

    public void setWeekDate(Date weekDate) {
	this.weekDate = weekDate;
    }

    @Column(name = "OnshoreFTE", precision = 10)
    public Float getOnshoreFte() {
	return this.onshoreFte;
    }

    public void setOnshoreFte(Float onshoreFte) {
	this.onshoreFte = onshoreFte;
    }

    @Column(name = "OffshoreFTE", precision = 10)
    public Float getOffshoreFte() {
	return this.offshoreFte;
    }

    public void setOffshoreFte(Float offshoreFte) {
	this.offshoreFte = offshoreFte;
    }

}
